import {expect,it}from"@effect/vitest";
import {Schema}from"effect";
import {vi}from"vitest";
import {isSafeDcMediaUrl}from"../../src/contracts/media";
import {CommentData}from"../../src/contracts/product";
const hosts=["dcimg5.dcinside.com","dcimg4.dcinside.com","dcimg1.dcinside.com","dccon.dcinside.com","image.dcinside.com"];
const decode=Schema.decodeUnknownSync(CommentData);
const model=(url:string)=>({id:"c",parentId:null,kind:"dccon",text:"[디시콘]",postedAt:null,mediaUrls:[url]});
for(const host of hosts)for(const tail of ["","/test.png?file=a%20b#media"]){const url="https://"+host+tail;it("DC media accepts exact verified origin "+url,()=>{expect(isSafeDcMediaUrl(url)).toBe(true);expect(decode(model(url)).mediaUrls).toEqual([url]);});}
for(const url of ["https://DCIMG5.DCINSIDE.COM/a.png","https://dccon.dcinside.com/한글😀.png?x=@user:443","https://dcimg5.dcinside.com/?a=%00"]){it("DC media accepts safe authority with literal path "+url,()=>{expect(isSafeDcMediaUrl(url)).toBe(true);expect(decode(model(url)).mediaUrls).toEqual([url]);});}
for(const url of ["","/image.png","//dcimg5.dcinside.com/a","http://dcimg5.dcinside.com/a","HTTPS://dcimg5.dcinside.com/a","javascript:alert(1)","data:image/png;base64,x","blob:https://dcimg5.dcinside.com/x","file:///image.png","https:///dcimg5.dcinside.com/a","https://evil.invalid/a","https://dcimg5.dcinside.com.evil.invalid/a","https://dcimg5.dcinside.com./a","https://dcimg5.dcinside.com:443/a","https://dcimg5.dcinside.com:0/a","https://dcimg5.dcinside.com:/a","https://user@dcimg5.dcinside.com/a","https://:pass@dcimg5.dcinside.com/a","https://@dcimg5.dcinside.com/a","https://dcimg5.dcinside.com@evil.invalid/a","https://%64cimg5.dcinside.com/a","https://dcimg5%2edcinside.com/a"," https://dcimg5.dcinside.com/a","https://dcimg5.dcinside.com/a b","https://dcimg5.dcinside.com/a\n","https://dcimg5.dcinside.com/a\t","https://dcimg5.dcinside.com/a\u007f","https://dcimg5.dcinside.com\\@evil.invalid/a","https://dcimg5.dcinside.com/a%","https://dcimg5.dcinside.com/a%2","https://dcimg5.dcinside.com/a%2x","https://dcimg5.dcinside.com/a\\b"]){it("DC media rejects malicious or malformed DTO URI "+JSON.stringify(url),()=>{expect(isSafeDcMediaUrl(url)).toBe(false);expect(()=>decode(model(url))).toThrow();});}
it("empty media list remains required and malformed list has no partial decode",()=>{expect(decode({...model("unused"),mediaUrls:[]}).mediaUrls).toEqual([]);for(const mediaUrls of [undefined,null,"https://dccon.dcinside.com/a",[null],[1],["https://dccon.dcinside.com/a","https://evil.invalid/a"]])expect(()=>decode({...model("unused"),mediaUrls})).toThrow();});
it("URL parser dependency exception fails closed and restores the native constructor",()=>{const original=globalThis.URL;let calls=0;vi.stubGlobal("URL",class{constructor(){calls++;throw new Error("private-parser-fault");}});try{expect(isSafeDcMediaUrl("https://dccon.dcinside.com/a.png")).toBe(false);expect(()=>decode(model("https://dccon.dcinside.com/a.png"))).toThrow();expect(calls).toBe(2);}finally{vi.unstubAllGlobals();}expect(globalThis.URL).toBe(original);});