// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Product DTOs expose read projections only. Frozen inputs and verifiers never
 * cross IPC; the application constructs them from its confirmed draft.
 */
export interface ArticleData {
    "url": string;
    "title": string;
    "galleryId": string;
    "galleryName": string;
    "galleryKind": string;
    "number": string;
    "authorNickname": string;
    "authorIdentifier": string | null;
    "postedAt": string | null;
}

export interface ArticleExportRequest {
    "url": string;
}

export type ArticleGeneration = number;

export type BackendSessionID = string;

/**
 * BadgeCategory is presentation/classification metadata. It never changes the
 * fixed/semi-fixed/anonymous identity namespace used to deduplicate participants.
 */
export enum BadgeCategory {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    BadgeFixed = "fixed",
    BadgeSemiFixed = "semi_fixed",
    BadgeMainManager = "main_manager",
    BadgeSubManager = "sub_manager",
    BadgeNewAccount = "new_account",
    BadgeAnonymous = "anonymous",
};

export interface BadgeRule {
    "excluded": boolean;
    "weight": number;
}

export interface BadgeRules {
    "weightingEnabled": boolean;
    "fixed": BadgeRule;
    "semiFixed": BadgeRule;
    "mainManager": BadgeRule;
    "subManager": BadgeRule;
    "newAccount": BadgeRule;
    "anonymous": BadgeRule;
}

export interface BootstrapData {
    "backendNow": string;
    "theme": string;
    "activeDraft": DraftSummary | null;
    "pendingOperations": OperationDescriptor[] | null;
    "pendingCursor": string | null;
    "recentResults": ResultReference[] | null;
}

/**
 * A defined concrete DTO has no custom JSON marshaler. Wails can therefore
 * generate its actual structure rather than degrading a json.Marshaler to any.
 * The service validates it before returning it to the binding serializer.
 */
export interface BootstrapResponse {
    "protocolVersion": number;
    "backendSessionId": BackendSessionID;
    "occurredAt": string;
    "ok": boolean;
    "operationId"?: OperationID | null;
    "revision"?: Revision | null;
    "data"?: BootstrapData | null;
    "code"?: ErrorCode;
    "messageKey"?: string;
}

export interface CollectionCommandRequest {
    "quickDelaySeconds": number | null;
    "protocolVersion": number;
    "backendSessionId": BackendSessionID;
    "operationId": OperationID;
    "expectedRevision": Revision | null;
    "collectionId": CollectionID;
    "roundId": RoundID;
    "expectedVersion": RoundVersion | null;
    "prizes": PrizeInput[] | null;
    "message": string;
    "mode": string;
    "scheduledAt": string | null;
}

export interface CollectionData {
    "collectionId": CollectionID;
    "revision": Revision;
    "article": ArticleData;
    "snapshot": SnapshotSummary;
    "filters": FilterConfiguration;
    "participantCount": number;
    "selectedCount": number;
    "remainingCount": number;
    "rounds": RoundData[] | null;
    "roundTotal": number;
    "roundOffset": number;
    "latestRound": RoundData;
}

export type CollectionID = string;

export interface CollectionQuery {
    "collectionId": CollectionID;
    "roundOffset": number;
    "roundLimit": number;
    "roundId": RoundID;
}

export interface CollectionResponse {
    "protocolVersion": number;
    "backendSessionId": BackendSessionID;
    "occurredAt": string;
    "ok": boolean;
    "operationId"?: OperationID | null;
    "revision"?: Revision | null;
    "data"?: CollectionData | null;
    "code"?: ErrorCode;
    "messageKey"?: string;
}

export interface CommentData {
    "id": string;
    "parentId": string | null;
    "kind": string;
    "text": string;
    "postedAt": string | null;
    "mediaUrls": string[] | null;
}

export interface CommentsPage {
    "context": DraftContext;
    "participantId": ParticipantID;
    "total": number;
    "offset": number;
    "rows": CommentData[] | null;
}

export interface CommentsResponse {
    "protocolVersion": number;
    "backendSessionId": BackendSessionID;
    "occurredAt": string;
    "ok": boolean;
    "operationId"?: OperationID | null;
    "revision"?: Revision | null;
    "data"?: CommentsPage | null;
    "code"?: ErrorCode;
    "messageKey"?: string;
}

export interface CreateCollectionRequest {
    "protocolVersion": number;
    "backendSessionId": BackendSessionID;
    "operationId": OperationID;
    "expectedRevision": Revision | null;
    "draftId": DraftID;
    "articleGeneration": ArticleGeneration | null;
    "afterSequence": number;
    "mode": string;
}

export interface CreateDraftRequest {
    "protocolVersion": number;
    "backendSessionId": BackendSessionID;
    "operationId": OperationID;
    "expectedRevision": Revision | null;
}

/**
 * DraftContext pins a command to one Go session, one draft snapshot and one revision.
 */
export interface DraftContext {
    "backendSessionId": BackendSessionID;
    "draftId": DraftID;
    "revision": Revision;
    "articleGeneration": ArticleGeneration;
}

export interface DraftData {
    "summary": DraftSummary;
    "article": ArticleData | null;
    "filters": FilterConfiguration;
    "prizes": PrizeConfiguration;
    "participants": number;
    "included": number;
    "excluded": number;
    "authorIdentifiable": boolean;
    "load": LoadProgress | null;
}

export interface DraftEditRequest {
    "protocolVersion": number;
    "backendSessionId": BackendSessionID;
    "operationId": OperationID;
    "expectedRevision": Revision | null;
    "draftId": DraftID;
    "articleGeneration": ArticleGeneration | null;
    "kind": string;
    "filters": FilterConfiguration | null;
    "prizes": PrizeConfiguration | null;
    "participantId": ParticipantID;
    "included": boolean | null;
}

export type DraftID = string;

export interface DraftOperationData {
    "operationId": OperationID;
    "state": OperationState;
    "summary": DraftSummary | null;
    "failureCode": ErrorCode | null;
}

export interface DraftOperationResponse {
    "protocolVersion": number;
    "backendSessionId": BackendSessionID;
    "occurredAt": string;
    "ok": boolean;
    "operationId"?: OperationID | null;
    "revision"?: Revision | null;
    "data"?: DraftOperationData | null;
    "code"?: ErrorCode;
    "messageKey"?: string;
}

export interface DraftQuery {
    "backendSessionId": BackendSessionID;
    "draftId": DraftID;
}

export interface DraftResponse {
    "protocolVersion": number;
    "backendSessionId": BackendSessionID;
    "occurredAt": string;
    "ok": boolean;
    "operationId"?: OperationID | null;
    "revision"?: Revision | null;
    "data"?: DraftData | null;
    "code"?: ErrorCode;
    "messageKey"?: string;
}

export enum DraftState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DraftEmpty = "empty",
    DraftLoading = "loading",
    DraftReady = "ready",
    DraftFinalized = "finalized",
};

export interface DraftSummary {
    "backendSessionId": BackendSessionID;
    "draftId": DraftID;
    "revision": Revision;
    "articleGeneration": ArticleGeneration;
    "state": DraftState;
    "snapshot": SnapshotSummary | null;
    "collectionId": CollectionID | null;
}

export enum ErrorCode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    InvalidInput = "InvalidInput",
    InvalidState = "InvalidState",
    StaleRevision = "StaleRevision",
    StaleArticleContext = "StaleArticleContext",
    BackendSessionChanged = "BackendSessionChanged",
    ProtocolError = "ProtocolError",
    StorageUnavailable = "StorageUnavailable",
};

export enum EventEntityKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DraftEntity = "draft",
    CollectionEntity = "collection",
};

export interface ExportData {
    "status": string;
}

export interface ExportResponse {
    "protocolVersion": number;
    "backendSessionId": BackendSessionID;
    "occurredAt": string;
    "ok": boolean;
    "operationId"?: OperationID | null;
    "revision"?: Revision | null;
    "data"?: ExportData | null;
    "code"?: ErrorCode;
    "messageKey"?: string;
}

export interface FilterConfiguration {
    "badgeRules"?: BadgeRules | null;
    "excludeAnonymous": boolean;
    "excludeAuthor": boolean;
    "excludeDcconOnly": boolean;
    "timeCut": string | null;
    "includeKeywords": string[] | null;
    "excludeKeywords": string[] | null;
}

export interface FrozenCommentsPage {
    "collectionId": CollectionID;
    "revision": Revision;
    "participantId": ParticipantID;
    "total": number;
    "offset": number;
    "rows": CommentData[] | null;
}

export interface FrozenCommentsQuery {
    "collectionId": CollectionID;
    "expectedRevision": Revision | null;
    "participantId": ParticipantID;
    "offset": number;
    "limit": number;
}

export interface FrozenCommentsResponse {
    "protocolVersion": number;
    "backendSessionId": BackendSessionID;
    "occurredAt": string;
    "ok": boolean;
    "operationId"?: OperationID | null;
    "revision"?: Revision | null;
    "data"?: FrozenCommentsPage | null;
    "code"?: ErrorCode;
    "messageKey"?: string;
}

export interface FrozenParticipantsPage {
    "collectionId": CollectionID;
    "revision": Revision;
    "total": number;
    "matched": number;
    "offset": number;
    "rows": ParticipantData[] | null;
}

/**
 * Frozen queries address only the immutable durable collection, so read access
 * survives a Go session restart. A supplied revision fences the whole page.
 */
export interface FrozenParticipantsQuery {
    "collectionId": CollectionID;
    "expectedRevision": Revision | null;
    "query": string;
    "group": string;
    "offset": number;
    "limit": number;
}

export interface FrozenParticipantsResponse {
    "protocolVersion": number;
    "backendSessionId": BackendSessionID;
    "occurredAt": string;
    "ok": boolean;
    "operationId"?: OperationID | null;
    "revision"?: Revision | null;
    "data"?: FrozenParticipantsPage | null;
    "code"?: ErrorCode;
    "messageKey"?: string;
}

export interface LoadArticleRequest {
    "protocolVersion": number;
    "backendSessionId": BackendSessionID;
    "operationId": OperationID;
    "expectedRevision": Revision | null;
    "draftId": DraftID;
    "articleGeneration": ArticleGeneration | null;
    "url": string;
}

export interface LoadProgress {
    "operationId": OperationID;
    "sequence": number;
    "pages": number;
    "comments": number;
    "state": string;
    "failureCode": ErrorCode | null;
}

export interface OperationDescriptor {
    "operationId": OperationID;
    "kind": string;
    "collectionId": CollectionID;
    "roundId": RoundID;
    "status": OperationState;
    "revision": Revision;
}

export type OperationID = string;

export interface OperationLookupRequest {
    "operationId": OperationID;
}

export interface OperationLookupResponse {
    "protocolVersion": number;
    "backendSessionId": BackendSessionID;
    "occurredAt": string;
    "ok": boolean;
    "operationId"?: OperationID | null;
    "revision"?: Revision | null;
    "data"?: OperationObservation | null;
    "code"?: ErrorCode;
    "messageKey"?: string;
}

/**
 * Lookup is an observation of the stored operation. Unknown never means failed.
 * It contains neither request payload, fingerprint nor credential material.
 */
export interface OperationObservation {
    "operationId": OperationID;
    "state": OperationState;
    "kind": string | null;
    "collectionId": CollectionID | null;
    "roundId": RoundID | null;
    "revision": Revision | null;
    "failureCode": ErrorCode | null;
}

export enum OperationState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OperationUnknown = "unknown",
    OperationPending = "pending",
    OperationSucceeded = "succeeded",
    OperationFailed = "failed",
};

export interface PNGRequest {
    "suggestedFilename": string;
    "dataBase64": string;
}

export interface ParticipantCommentsQuery {
    "backendSessionId": BackendSessionID;
    "draftId": DraftID;
    "revision": Revision;
    "articleGeneration": ArticleGeneration;
    "participantId": ParticipantID;
    "offset": number;
    "limit": number;
}

export interface ParticipantData {
    "badgeCategory": BadgeCategory;
    "id": ParticipantID;
    "nickname": string;
    "publicIdentifier": string;
    "kind": string;
    "classification": string;
    "reason": string;
    "included": boolean;
    "commentCount": number;
    "previews": string[] | null;
}

export type ParticipantID = string;

export interface ParticipantQuery {
    "backendSessionId": BackendSessionID;
    "draftId": DraftID;
    "revision": Revision;
    "articleGeneration": ArticleGeneration;
    "query": string;
    "offset": number;
    "limit": number;
    "group": string;
}

export interface ParticipantsPage {
    "context": DraftContext;
    "total": number;
    "matched": number;
    "offset": number;
    "rows": ParticipantData[] | null;
}

export interface ParticipantsResponse {
    "protocolVersion": number;
    "backendSessionId": BackendSessionID;
    "occurredAt": string;
    "ok": boolean;
    "operationId"?: OperationID | null;
    "revision"?: Revision | null;
    "data"?: ParticipantsPage | null;
    "code"?: ErrorCode;
    "messageKey"?: string;
}

export interface PendingOperationsPage {
    "operations": OperationDescriptor[] | null;
    "cursor": string | null;
}

export interface PendingOperationsRequest {
    "cursor": string | null;
    "limit": number | null;
}

export interface PendingOperationsResponse {
    "protocolVersion": number;
    "backendSessionId": BackendSessionID;
    "occurredAt": string;
    "ok": boolean;
    "operationId"?: OperationID | null;
    "revision"?: Revision | null;
    "data"?: PendingOperationsPage | null;
    "code"?: ErrorCode;
    "messageKey"?: string;
}

export interface PrizeConfiguration {
    "mode": string;
    "single": PrizeInput;
    "multiple": PrizeInput[] | null;
    "drawMode": string;
}

export interface PrizeInput {
    "id": string;
    "name": string;
    "count": number;
}

export interface ResultReference {
    "collectionId": CollectionID;
    "roundId": RoundID;
    "revision": Revision;
}

export type Revision = number;

export interface RoundData {
    "collectionId": CollectionID;
    "roundId": RoundID;
    "number": number;
    "attempt": number;
    "state": RoundState;
    "revision": Revision;
    "roundVersion": RoundVersion;
    "mode": string;
    "message": string;
    "prizes": PrizeInput[] | null;
    "scheduledAt": string | null;
    "executedAt": string | null;
    "failureCode": ErrorCode | null;
    "winners": WinnerData[] | null;
    "algorithmVersion": string;
    "appVersion": string;
}

export type RoundID = string;

export enum RoundState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PendingSchedule = "pending_schedule",
    Scheduled = "scheduled",
    Executing = "executing",
    Completed = "completed",
    Cancelled = "cancelled",
    Failed = "failed",
};

export type RoundVersion = number;

export type SnapshotID = string;

/**
 * SnapshotSummary is a small read model. Full comments stay behind paged queries.
 * The collector owns completeness and the domain must reject incomplete snapshots at admission.
 */
export interface SnapshotSummary {
    "snapshotId": SnapshotID;
    "collectedAt": string;
    "complete": boolean;
    "pages": number;
    "acceptedComments": number;
    "deletedComments": number;
    "unsupportedComments": number;
}

/**
 * StateNotice is a committed-state hint, never a result or a secret payload.
 * The consumer reconciles through reads; notification delivery is not a commit.
 */
export interface StateNotice {
    "backendSessionId": BackendSessionID;
    "entityKind": EventEntityKind;
    "entityId": string;
    "revision": Revision;
    "operationId": OperationID | null;
}

export interface TextExportRequest {
    "text": string;
}

export interface WinnerData {
    "participant": ParticipantData;
    "prizeId": string;
    "prizeName": string;
    "slot": number;
}
