import test from "node:test";
import assert from "node:assert/strict";
import { installCanvasLayoutProbe, verifyCanvasPaintBounds, readResultCanvasFont, findResultSummaryPaint } from "./canvas.layout.mjs";
function fixture({ failureAt = 0, continuous = false, blobFailure = false, clockFailure = false, late = false } = {}) {
  let calls = 0, ticks = 0; const failure = new Error("owned-native-failure"); const metric = { width: 3, actualBoundingBoxLeft: 0, actualBoundingBoxRight: 3, actualBoundingBoxAscent: -1, actualBoundingBoxDescent: 9 }; const blob = { size: 10, type: "image/png" };
  class Context { constructor() { this.font = '400 31px "Jackpot Result"'; this.textBaseline = "top"; this.textAlign = "start"; this.fillStyle = "#000000"; } measureText(...args) { this.lastArgs = args; calls++; if (continuous || calls === failureAt) throw failure; return metric; } fillText(...args) { this.lastFillArgs = args; return "fill-return"; } }
  class Canvas { constructor() { this.width = 1200; this.height = 500; this.context = new Context(); } getContext(type) { this.lastType = type; return type === "2d" ? this.context : null; } toBlob(callback, type, quality) { this.lastEncoding = [type,quality]; if(blobFailure) throw failure; if(late) this.callback=callback; else callback.call(this,blob); return "encode-return"; } }
  const surface = { HTMLCanvasElement: Canvas, CanvasRenderingContext2D: Context, performance: { now() { if(clockFailure)throw failure; return ++ticks; } } };
  return { Canvas, Context, surface, failure, metric, blob, calls: () => calls };
}
test("original native result/receiver/arguments and callback identity remain observable", () => {
 const f=fixture(), original=f.Context.prototype.measureText, originalBlob=f.Canvas.prototype.toBlob; const control=installCanvasLayoutProbe({},f.surface); const canvas=new f.Canvas(),context=canvas.getContext("2d");
 assert.equal(context.measureText("AB",{unchanged:true}),f.metric); assert.deepEqual(context.lastArgs,["AB",{unchanged:true}]); context.measureText("AB");context.measureText("ABC");assert.equal(context.fillText("line",4,5),"fill-return");assert.deepEqual(context.lastFillArgs,["line",4,5]);
 let receiver,result;assert.equal(canvas.toBlob(function(blob){receiver=this;result=blob},"image/png",1),"encode-return");assert.equal(receiver,canvas);assert.equal(result,f.blob);assert.deepEqual(canvas.lastEncoding,["image/png",1]);canvas.width=0;canvas.height=0;
 const snap=control.snapshot();assert.equal(snap.records[0].calls,3);assert.equal(snap.records[0].uniqueMeasured,2);assert.equal(snap.records[0].duplicateMeasured,1);assert.equal(snap.records[0].measuredUTF16,7);assert.equal(snap.records[0].fillCalls,1);assert.equal(snap.records[0].blobBytes,10);assert.equal(snap.records[0].pixelsReleased,true);assert.equal(snap.observerFaults,0);assert.equal(JSON.stringify(snap).includes('"AB"'),false);
 control.dispose();control.dispose();assert.equal(f.Context.prototype.measureText,original);assert.equal(f.Canvas.prototype.toBlob,originalBlob);assert.equal(f.surface.__jackpotCanvasLayoutProbe,undefined);assert.equal(control.snapshot().records.length,0);
});
for(const options of [{failureAt:1},{failureAt:3},{continuous:true}])test("first/Nth/continuous measure failure propagates exact native failure "+JSON.stringify(options),()=>{
 const f=fixture(options),control=installCanvasLayoutProbe({},f.surface),context=new f.Canvas().getContext("2d");let failures=0;for(let i=0;i<4;i++){try{context.measureText("same")}catch(error){assert.equal(error,f.failure);failures++}}
 assert.equal(f.calls(),4);assert.equal(control.snapshot().records[0].measureFailures,failures);assert.ok(failures>0);control.dispose();
});
test("encoding failure is preserved with no fabricated callback/blob",()=>{const f=fixture({blobFailure:true}),control=installCanvasLayoutProbe({},f.surface),canvas=new f.Canvas();canvas.getContext("2d").measureText("value");assert.throws(()=>canvas.toBlob(()=>assert.fail("fabricated callback")),error=>error===f.failure);assert.equal(control.snapshot().records[0].toBlobFailures,1);assert.equal(control.snapshot().records[0].callbacks,0);control.dispose();});
test("late callback after observer disposal still reaches original caller exactly once",()=>{const f=fixture({late:true}),control=installCanvasLayoutProbe({},f.surface),canvas=new f.Canvas();canvas.getContext("2d").measureText("value");let calls=0;canvas.toBlob(blob=>{assert.equal(blob,f.blob);calls++});control.dispose();canvas.callback(f.blob);assert.equal(calls,1);assert.equal(control.snapshot().records.length,0);});
test("observer clock failure cannot change native behavior",()=>{const f=fixture({clockFailure:true}),control=installCanvasLayoutProbe({},f.surface),context=new f.Canvas().getContext("2d");assert.equal(context.measureText("x"),f.metric);assert.equal(control.snapshot().records[0].calls,1);assert.ok(control.snapshot().observerFaults>0);control.dispose();});
test("zero and bounded raw-prefix tracking exposes truncation and retains no raw text in output",()=>{for(const maxTrackedUnits of [0,3]){const f=fixture(),control=installCanvasLayoutProbe({maxRecords:1,maxTrackedUnits},f.surface);for(let i=0;i<100;i++){const context=new f.Canvas().getContext("2d");context.measureText("private-prefix")}const snapshot=control.snapshot();assert.equal(snapshot.records.length,1);assert.equal(snapshot.totalContexts,100);assert.equal(snapshot.records[0].trackingTruncated,true);assert.equal(JSON.stringify(snapshot).includes("private-prefix"),false);control.reset();assert.equal(control.snapshot().records.length,0);control.dispose();}});
test("invalid bounds are refused before changing methods",()=>{for(const options of [{maxRecords:0},{maxRecords:65},{maxRecords:NaN},{maxTrackedUnits:-1},{maxTrackedUnits:1048577}]){const f=fixture(),original=f.Context.prototype.measureText;assert.throws(()=>installCanvasLayoutProbe(options,f.surface),RangeError);assert.equal(f.Context.prototype.measureText,original);}});
test("duplicate installation is refused and dispose does not restore over a later independent method",()=>{const f=fixture(),first=installCanvasLayoutProbe({},f.surface),active=f.Context.prototype.measureText;assert.throws(()=>installCanvasLayoutProbe({},f.surface),RangeError);assert.equal(f.Context.prototype.measureText,active);const independent=()=>({width:9});f.Context.prototype.measureText=independent;first.dispose();assert.equal(f.Context.prototype.measureText,independent);assert.equal(f.surface.__jackpotCanvasLayoutProbe,undefined);});
test("invalid font width stays exactly invalid instead of observer normalization",()=>{for(const width of [NaN,-1,Infinity]){const f=fixture();f.metric.width=width;const control=installCanvasLayoutProbe({},f.surface),context=new f.Canvas().getContext("2d");const actual=context.measureText("AB");assert.equal(actual,f.metric);assert.ok(Object.is(actual.width,width));control.dispose();}});
test("fill exception preserves native failure and cleanup without a fabricated render",()=>{const f=fixture();f.Context.prototype.fillText=function(){throw f.failure};const control=installCanvasLayoutProbe({},f.surface),context=new f.Canvas().getContext("2d");assert.throws(()=>context.fillText("line",0,0),error=>error===f.failure);assert.equal(control.snapshot().records[0].fillFailures,1);control.dispose();assert.equal(control.snapshot().records.length,0);});
test("opt-in paint captures exact current native font and ink boxes without changing calls or return",()=>{
 const f=fixture(),control=installCanvasLayoutProbe({capturePaint:true},f.surface),canvas=new f.Canvas(),context=canvas.getContext("2d");
 context.measureText("layout");assert.equal(context.fillText("한글😀",10,20),"fill-return");context.font='700 35px "Jackpot Result"';context.fillText("제목",100,20);canvas.toBlob(()=>{});
 const record=control.snapshot().records[0];assert.equal(record.calls,1);assert.equal(record.fillCalls,2);assert.equal(f.calls(),3);assert.deepEqual(record.paints[0],{text:"한글😀",x:10,y:20,font:'400 31px "Jackpot Result"',baseline:"top",align:"start",color:"#000000",measuredWidth:3,left:10,right:13,top:21,bottom:29});assert.equal(record.paints[1].font,'700 35px "Jackpot Result"');
 assert.deepEqual(verifyCanvasPaintBounds(record),{textCalls:2,inkBoxes:2,width:1200,height:500,clipped:0,overlaps:0});record.paints[0].text="caller edit";assert.equal(control.snapshot().records[0].paints[0].text,"한글😀");control.reset();assert.equal(control.snapshot().records.length,0);control.dispose();
});
test("paint observer native metric failure preserves successful original fill and reports fault",()=>{const f=fixture({failureAt:1}),control=installCanvasLayoutProbe({capturePaint:true},f.surface),context=new f.Canvas().getContext("2d");assert.equal(context.fillText("value",0,0),"fill-return");assert.equal(control.snapshot().observerFaults,1);assert.equal(control.snapshot().records[0].fillFailures,0);assert.equal(control.snapshot().records[0].paints.length,0);control.dispose();});
test("paint text budget refuses truncation as a complete geometry result",()=>{const f=fixture(),control=installCanvasLayoutProbe({capturePaint:true,maxTrackedUnits:3},f.surface),canvas=new f.Canvas(),context=canvas.getContext("2d");context.fillText("abcd",0,0);canvas.toBlob(()=>{});const record=control.snapshot().records[0];assert.equal(record.paintTrackingTruncated,true);assert.throws(()=>verifyCanvasPaintBounds(record),/CanvasPaintIncomplete/);control.dispose();});
test("paint call count bound retains at most512 exact records and exposes incomplete observation",()=>{const f=fixture(),control=installCanvasLayoutProbe({capturePaint:true},f.surface),canvas=new f.Canvas(),context=canvas.getContext("2d");for(let i=0;i<513;i++)context.fillText("x",10,20);canvas.toBlob(()=>{});const record=control.snapshot().records[0];assert.equal(record.paints.length,512);assert.equal(record.paintTrackingTruncated,true);assert.throws(()=>verifyCanvasPaintBounds(record),/CanvasPaintIncomplete/);control.dispose();});
test("native paint bounds accepts touching edges and rejects one-axis clipping or two-axis overlap",()=>{
 const paint={text:"line",left:0,right:3,top:0,bottom:9,measuredWidth:3};const record={width:1200,height:500,fillCalls:2,paintTrackingTruncated:false,paints:[paint,{...paint,left:3,right:6}]};assert.equal(verifyCanvasPaintBounds(record).overlaps,0);
 for(const change of [{left:-1},{right:1201},{top:-1},{bottom:501}])assert.throws(()=>verifyCanvasPaintBounds({...record,fillCalls:1,paints:[{...paint,...change}]}),/CanvasPaintClipped/);
 assert.throws(()=>verifyCanvasPaintBounds({...record,paints:[paint,{...paint,left:2,right:5}]}),/CanvasPaintOverlap/);
 for(const change of [{left:NaN},{right:-1},{bottom:-1},{measuredWidth:-1}])assert.throws(()=>verifyCanvasPaintBounds({...record,fillCalls:1,paints:[{...paint,...change}]}),/CanvasPaintInvalidBounds/);
});
test("paint observation is explicitly boolean and unsupported maxWidth is an observer fault, never native mutation",()=>{const f=fixture(),original=f.Context.prototype.fillText;assert.throws(()=>installCanvasLayoutProbe({capturePaint:1},f.surface),RangeError);assert.equal(f.Context.prototype.fillText,original);const control=installCanvasLayoutProbe({capturePaint:true},f.surface),context=new f.Canvas().getContext("2d");assert.equal(context.fillText("x",1,1,5),"fill-return");assert.equal(control.snapshot().observerFaults,1);assert.deepEqual(context.lastFillArgs,["x",1,1,5]);control.dispose();});
test("native getter bold and omitted normal weight have identical semantic weight without relaxing size or family",()=>{
 for(const prefix of ["", "normal ", "400 "])assert.deepEqual(readResultCanvasFont(prefix+'31px "Jackpot Result", sans-serif'),{weight:400,size:31});
 for(const prefix of ["bold ", "700 "])assert.deepEqual(readResultCanvasFont(prefix+'35px "Jackpot Result", sans-serif'),{weight:700,size:35});
 assert.deepEqual(readResultCanvasFont('600 35px "Jackpot Result", sans-serif'),{weight:600,size:35});
 for(const font of [null,"",'700 31px "Jackpot Result"','600 31px "Jackpot Result"','35px "Jackpot Result"','700 34px "Jackpot Result"','800 35px "Jackpot Result"','bold 35px "Fallback"'])assert.throws(()=>readResultCanvasFont(font),/CanvasPaintFont/);
});
test("participant nickname prefix or exact body nickname never selects the count summary",()=>{
 const nickname={text:"참가자 00050 한글",font:'31px "Jackpot Result"'},sameNickname={text:"참가자 100명 · 당첨자 10명",font:'31px "Jackpot Result"'},summary={text:"참가자 100명 · 당첨자 10명",font:'600 35px "Jackpot Result"'};
 assert.equal(findResultSummaryPaint([nickname,sameNickname,summary],100,10),2);
 for(const paints of [[nickname,sameNickname],[summary,summary]])assert.throws(()=>findResultSummaryPaint(paints,100,10),/CanvasPaintSummary/);
 assert.throws(()=>findResultSummaryPaint([summary],99,10),/CanvasPaintSummary/);
});
