// Native stress uses production frontend/Go owners. OS selection, clipboard,
// browser and network delivery are explicit fixtures; physical DPI is unchanged.
import assert from "node:assert/strict";
import { spawn, execFile } from "node:child_process";
import { mkdtemp, readFile, writeFile, rm, access } from "node:fs/promises";
import { createServer } from "node:net";
import {createWriteStream} from "node:fs";
import { resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";
import { chromium, expect } from "@playwright/test";
import { percentile95 as p95,pngDimensions,watchRoundCommit,finalizePeak } from "./stress.metrics.mjs";
import {startMemoryTrace} from "./stress.trace.mjs";
import {installMediaFixture,verifyMediaPanel} from "./stress.media.mjs";
import {installDataPreview} from "./stress.preview.mjs";
import {installNoImagePreview} from "./stress.noimage.mjs";
import {localWorkload} from "./stress.workload.mjs";
const workload=localWorkload();
import {installBitmapProbe,readPreviewCanvas} from "./stress.bitmap.mjs";
const root=fileURLToPath(new URL("../../../",import.meta.url)),task=resolve(root,".task");
assert.ok(process.env.JACKPOT_STRESS_ASSETS,"fresh owned bitmap diagnostic assets required; historical assets are not a local-product checkpoint");
const exe=resolve(task,"product-stress.exe"),assets=resolve(process.env.JACKPOT_STRESS_ASSETS??resolve(task,"stress-assets-bitmap-local"));assert.ok(assets.startsWith(task+sep)&&assets.slice(task.length+1).startsWith("stress-assets-bitmap-local"),"owned stress assets required");
const bootstrapBindings=await readFile(resolve(task,"../frontend/bindings/github.com/porkyx/jackpot/internal/desktop/service.ts"),"utf8");const bootstrapMethod=Number(/export function Bootstrap[\s\S]*?return\s+\$Call\.ByID\((\d+)\)/.exec(bootstrapBindings)?.[1]);assert.ok(Number.isSafeInteger(bootstrapMethod)&&bootstrapMethod>0&&bootstrapMethod<=4294967295,"generated Bootstrap binding required");
const childGoMemoryLimit=process.env.JACKPOT_STRESS_GO_MEMORY_LIMIT;assert.ok(childGoMemoryLimit===undefined||childGoMemoryLimit===""||childGoMemoryLimit==="160MiB","only approved child Go memory diagnostic allowed");const goMemoryLimitDiagnostic=childGoMemoryLimit==="160MiB";assert.ok(!process.env.GOMEMLIMIT,"baseline inherited GOMEMLIMIT must be unset");const bindingsOnly=process.env.JACKPOT_STRESS_BINDINGS_ONLY==="1";const traceDiagnostic=process.env.JACKPOT_STRESS_MEMORY_TRACE==="1";const readbackDiagnostic=process.env.JACKPOT_STRESS_READBACK==="1";const dataDiagnostic=process.env.JACKPOT_STRESS_PREVIEW_DATA==="1";const noImageDiagnostic=process.env.JACKPOT_STRESS_PREVIEW_NOIMAGE==="1";assert.ok(Number(dataDiagnostic)+Number(readbackDiagnostic)+Number(noImageDiagnostic)<=1,"isolate preview transport from Canvas hint");if(dataDiagnostic)assert.ok(assets.startsWith(task+sep)&&assets.slice(task.length+1).startsWith("stress-assets-data-"),"data URI requires owned CSP asset fixture");assert.equal(readbackDiagnostic||dataDiagnostic||noImageDiagnostic||goMemoryLimitDiagnostic,false,"isolate bitmap display transfer");const reportPath=resolve(task,bindingsOnly?"product-bindings-report.json":"product-bitmap-report.json");
const work=await mkdtemp(resolve(task,"product-run-stress-"));
assert.ok(work.startsWith(task+sep)&&work.includes("product-run-stress-"));
const report={status:"running",phase:"boot",iterations:0,samples:[],PNG:[],workingSetPeakBytes:0,boundaries:{native:"actual Wails/WebView2/SQLite/collector/parser/crypto/Canvas",network:"two deterministic delivered pages",OSsave:"selection capture with real atomic writer",clipboard:"capture preserving user clipboard",DPI:"isolated CDP renderer DPR; Windows desktop DPI unchanged",HMR:"not exercised by production dist",privateQueue:"not inferred; authoritative pending operations checked"}};
const memoryLog=createWriteStream(resolve(task,bindingsOnly?"product-bindings-memory.jsonl":"product-bitmap-memory.jsonl"),{flags:"w"});
let child,browser,page,renderer,exit,sampler,samplerExit,goSampler,memoryTrace,traceSession,mediaFixture;let goSamplePending=Promise.resolve();let goSampleBusy=false;
async function resourceCheckpoint(){const metric=await renderer.send("Performance.getMetrics");const js=Object.fromEntries(metric.metrics.filter(value=>["JSHeapUsedSize","JSHeapTotalSize","Nodes","Documents","JSEventListeners"].includes(value.name)).map(value=>[value.name,value.value]));const go=await call("main.Probe.Memory");const dom=await renderer.send("Memory.getDOMCounters");const checkpoint={phase:report.phase,cycle:report.iterations,observedAt:Date.now(),js,dom,go,...(dataDiagnostic?{previewTransport:await page.evaluate(()=>window.__jackpotPreviewTransport.snapshot())}:{})};const tracePoint=report.phase+"-cycle-"+report.iterations;if(memoryTrace&&(bindingsOnly||report.phase==="scope-baseline"&&report.iterations===0||report.phase==="route-dialog-export-cycles"&&report.iterations===report.requestedIterations)&&!report.memoryDumpLabels?.includes(tracePoint)){checkpoint.memoryDump=await memoryTrace.dump(tracePoint);(report.memoryDumpLabels??=[]).push(tracePoint);}(report.resourceCheckpoints??=[]).push(checkpoint);return checkpoint}
const runPS=(command)=>new Promise((ok,fail)=>execFile("powershell.exe",["-NoProfile","-NonInteractive","-Command",command],{windowsHide:true,timeout:30000},(error,stdout)=>error?fail(error):ok(stdout)));
async function discoverOwned(){const command="$ErrorActionPreference='Stop'; $profileProof='"+work.replaceAll("'","''")+"' ; Get-CimInstance Win32_Process -Filter \"Name='msedgewebview2.exe'\" | Where-Object {$_.CommandLine -like ('*'+$profileProof+'*')} | ForEach-Object {$_.ProcessId}";const raw=await runPS(command);const discovered=raw.trim()===""?[]:raw.trim().split(/\s+/).map(Number);assert.ok(discovered.every(id=>Number.isSafeInteger(id)&&id>0));ownedIds=[...new Set([...ownedIds,...discovered])];}
let ownedIds=[];let latest,baseline;
const button=name=>page.getByRole("button",{name,exact:true});
const visible=name=>page.getByLabel(name,{exact:true}).and(page.locator(":visible"));
const call=(method,...args)=>page.evaluate(async({method,args})=>{const dispatch=window._wails.dispatchWailsEvent;const {Call}=await import("/wails/runtime.js");window._wails.dispatchWailsEvent=dispatch;return await (typeof method==="number"?Call.ByID(method,...args):Call.ByName(method,...args))},{method,args});
const snapshot=()=>call("main.Probe.Report");const exportState=()=>call("main.Probe.ExportState");
async function phase(name){report.phase=name;console.log("stress phase "+name);await writeFile(resolve(task,bindingsOnly?"product-bindings-live.json":"product-bitmap-live.json"),JSON.stringify({status:"running",phase:name,iterations:report.iterations,ownedPIDs:ownedIds,peakBytes:report.workingSetPeakBytes}));}
const current=async()=>{const state=await snapshot();return{state,collection:state.latest[0]}};
async function freePort(){const server=createServer();await new Promise((ok,fail)=>{server.once("error",fail);server.listen(0,"127.0.0.1",ok)});const port=server.address().port;await new Promise((ok,fail)=>server.close(e=>e?fail(e):ok()));return port;}
async function refreshOwned(){const session=await browser.newBrowserCDPSession();const processes=await session.send("SystemInfo.getProcessInfo");await session.detach();ownedIds=[...new Set([child.pid,...processes.processInfo.map(p=>p.id)])];assert.ok(ownedIds.every(id=>Number.isSafeInteger(id)&&id>0));await discoverOwned();await writeFile(resolve(task,"product-bitmap-owned.json"),JSON.stringify(ownedIds));}
function instrument({readback=false,clickTrace=false}={}){
 if(clickTrace){const records=[];window.__jackpotClickTrace=records;for(const type of ["pointerdown","pointerup","click","input","change","focusin","focusout"]){document.addEventListener(type,event=>{const target=event.target instanceof Element?event.target:null;const button=target?.closest("button");const root=document.querySelector(".create-product");const labels=[...document.querySelectorAll("label")].filter(label=>label.textContent==="상품명 (선택)");const rows=labels.filter(label=>document.getElementById(label.htmlFor)?.getClientRects().length>0).length;records.push({type,at:performance.now(),trusted:event.isTrusted,button:button?.textContent,disabled:button?.disabled,connected:target?.isConnected,rootBusy:root?.getAttribute("aria-busy"),rows,activeTag:document.activeElement?.tagName,activeId:document.activeElement?.id,targetTag:target?.tagName,targetId:target?.id,targetType:target instanceof HTMLInputElement?target.type:undefined,checked:target instanceof HTMLInputElement&&target.type==="checkbox"?target.checked:undefined,targetDisabled:target instanceof HTMLInputElement?target.disabled:undefined,feedback:[...document.querySelectorAll("[role=alert]")].map(value=>value.textContent).filter(value=>["입력값을 확인해 주세요.","상태가 변경되어 요청을 적용하지 않았습니다. 최신 상태를 확인해 주세요.","게시글이 변경되어 이전 요청을 적용하지 않았습니다.","앱 연결이 새로 시작되었습니다. 저장된 상태를 다시 확인해 주세요."].includes(value)),rect:button?.getBoundingClientRect().toJSON()});if(records.length>256)records.shift();},true);}}
 window.__jackpotReadbackHint=readback;const getContext=HTMLCanvasElement.prototype.getContext;const contextModes={default:0,readback:0};
 HTMLCanvasElement.prototype.getContext=function(type,...options){if(type==="2d"&&window.__jackpotReadbackHint===true)options[0]={...options[0],willReadFrequently:true};const result=Reflect.apply(getContext,this,[type,...options]);if(type==="2d"&&result!==null){const mode=result.getContextAttributes().willReadFrequently===true?"readback":"default";contextModes[mode]++;}return result;};window.__jackpotCanvasModes=contextModes;
 const targets=new WeakMap(),callbacks=new WeakMap();let serial=0;const keys=new Set(),details=new Map(),urls=new Set(),canvases=[];
 const identity=(map,value)=>{let id=map.get(value);if(id===undefined){id=++serial;map.set(value,id)}return id};
 const accepts=target=>target instanceof Node||target===window;
 const key=(target,type,listener,options)=>identity(targets,target)+":"+type+":"+identity(callbacks,listener)+":"+(typeof options==="boolean"?options:Boolean(options?.capture));
 const add=EventTarget.prototype.addEventListener,remove=EventTarget.prototype.removeEventListener;
 EventTarget.prototype.addEventListener=function(type,listener,options){const result=add.call(this,type,listener,options);if(listener!=null&&accepts(this)){const id=key(this,type,listener,options);keys.add(id);details.set(id,{target:new WeakRef(this),callback:new WeakRef(listener),type,capture:typeof options==="boolean"?options:Boolean(options?.capture)})}return result};
 EventTarget.prototype.removeEventListener=function(type,listener,options){const result=remove.call(this,type,listener,options);if(listener!=null&&accepts(this)){const id=key(this,type,listener,options);keys.delete(id);details.delete(id)}return result};
 const frames=new Set(),raf=window.requestAnimationFrame,caf=window.cancelAnimationFrame;
 window.requestAnimationFrame=function(callback){const id=raf.call(window,time=>{frames.delete(id);callback(time)});frames.add(id);return id};
 window.cancelAnimationFrame=function(id){caf.call(window,id);frames.delete(id)};
 const create=URL.createObjectURL,revoke=URL.revokeObjectURL;
 URL.createObjectURL=function(blob){const result=create.call(URL,blob);urls.add(result);return result};
 URL.revokeObjectURL=function(url){revoke.call(URL,url);urls.delete(url)};
 const element=Document.prototype.createElement;
 Document.prototype.createElement=function(name,options){const result=element.call(this,name,options);if(name.toLowerCase()==="canvas")canvases.push(new WeakRef(result));return result};
 window.__jackpotStress={nativeDetails:(read)=>[...details].map(([id,entry])=>{const target=entry.target.deref(),callback=entry.callback.deref();const native=target===undefined?[]:(read(target)[entry.type]??[]);return{id,type:entry.type,node:target?.nodeName??"window-or-collected",name:target?.getAttribute?.("name")??target?.id??"",connected:target===window||target?.isConnected===true,registered:native.some(value=>value.listener===callback&&value.useCapture===entry.capture)}}),details:()=>[...details].map(([id,entry])=>{const target=entry.target.deref();return{id,type:entry.type,node:target?.nodeName??"window-or-collected",name:target?.getAttribute?.("name")??target?.id??"",connected:target===window||target?.isConnected===true}}),snapshot:()=>({listeners:keys.size,frames:frames.size,objectUrls:urls.size,canvasPixels:canvases.reduce((sum,reference)=>{const c=reference.deref();return sum+(c===undefined?0:c.width*c.height)},0),domNodes:document.querySelectorAll("*").length})};
}
async function readyCreate(){await expect(page.getByRole("heading",{name:"추첨 만들기",exact:true})).toBeVisible({timeout:20000});await expect(visible("디시인사이드 게시글 주소")).toBeEnabled();}
async function goCreate(){await page.locator('nav a[href="#/create"]').click();await readyCreate();}
async function goResult(){assert.ok(typeof latest?.collectionId==="string"&&latest.collectionId.length>0,"Saved fixture collection ID is required");await page.evaluate(id=>{window.location.hash="#/results/"+encodeURIComponent(id)},latest.collectionId);await expect(page.getByRole("heading",{name:"추첨 결과",exact:true})).toBeVisible();await expect(page.locator('select[name=resultRound]')).toBeEnabled();}
async function metrics(){return page.evaluate(()=>window.__jackpotStress.snapshot());}
async function nativeListeners(){const result=await renderer.send("Runtime.evaluate",{expression:"window.__jackpotStress.nativeDetails(getEventListeners)",includeCommandLineAPI:true,returnByValue:true});assert.equal(result.exceptionDetails,undefined);return result.result.value}
async function idleMetrics(){await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));let idle;await expect.poll(async()=>{idle=await metrics();return idle.frames===0&&idle.objectUrls===0&&idle.canvasPixels===0},{timeout:20000}).toBe(true);return idle}
async function savedPNG(filename){const before=await exportState();await button("PNG 사진 저장").click();await expect.poll(async()=>{const state=await exportState();return state.saves},{timeout:15000}).toBeGreaterThan(before.saves);const state=await exportState();const bytes=await readFile(state.savePath);const {width,height}=pngDimensions(bytes);const out=resolve(task,filename);await writeFile(out,bytes);return{path:out,width,height,size:bytes.length,sha256:createHash("sha256").update(bytes).digest("hex")};}
try{
 await access(exe);await access(resolve(assets,"index.html"));const assetHTML=await readFile(resolve(assets,"index.html"));report.assets={htmlSHA256:createHash("sha256").update(assetHTML).digest("hex"),scripts:[...assetHTML.toString().matchAll(/src="([^"]+\.js)"/g)].map(match=>match[1]),CSP:assetHTML.toString().includes("Content-Security-Policy"),hostSHA256:createHash("sha256").update(await readFile(exe)).digest("hex")};report.goMemoryLimitDiagnostic=goMemoryLimitDiagnostic;report.childGoMemoryLimit=goMemoryLimitDiagnostic?childGoMemoryLimit:null;const port=await freePort();
 child=spawn(exe,["-assets",assets,"-work-dir",work,"-cdp-port",String(port),"-large-fixture","-fixture-comments",String(workload.fixtureComments)],{cwd:root,env:{...process.env,...(goMemoryLimitDiagnostic?{GOMEMLIMIT:childGoMemoryLimit}:{})},windowsHide:true,stdio:["ignore","pipe","pipe"]});
 exit=new Promise((ok,fail)=>{child.once("error",fail);child.once("exit",(code,signal)=>ok({code,signal}))});void exit.catch(()=>{});let logs="";child.stdout.on("data",chunk=>{logs=(logs+chunk.toString()).slice(-4000)});child.stderr.on("data",()=>{});
 await expect.poll(()=>logs.includes("JACKPOT_PRODUCT_E2E_READY"),{timeout:30000}).toBe(true);
 await expect.poll(async()=>{try{return(await(await fetch("http://127.0.0.1:"+port+"/json/list")).json()).some(p=>p.type==="page")}catch{return false}},{timeout:20000}).toBe(true);
 browser=await chromium.connectOverCDP("http://127.0.0.1:"+port,{timeout:20000,isWebView:true});page=browser.contexts()[0].pages()[0];page.setDefaultTimeout(20000);
 await expect(page.getByRole("heading",{name:"Jackpot",exact:true})).toBeVisible({timeout:20000});await page.addInitScript(instrument,{readback:false,clickTrace:process.env.JACKPOT_STRESS_CLICK_TRACE==="1"});if(dataDiagnostic)await page.addInitScript(installDataPreview);if(noImageDiagnostic)await page.addInitScript(installNoImagePreview);await page.addInitScript(installBitmapProbe);await page.reload();await readyCreate();renderer=await browser.contexts()[0].newCDPSession(page);await renderer.send("Emulation.setFocusEmulationEnabled",{enabled:true});await renderer.send("Performance.enable");await refreshOwned();await discoverOwned();report.processRoles=Object.fromEntries((await (async()=>{const session=await browser.newBrowserCDPSession();const result=await session.send("SystemInfo.getProcessInfo");await session.detach();return result.processInfo})()).map(item=>[item.id,item.type]));report.processRoles[child.pid]="go-main";
 report.bitmapPreviewDiagnostic=true;report.boundaries.previewTransport="copied CSc source ImageBitmap to visible bitmaprenderer Canvas; originalPNG/save/copy and productionCSP unchanged; concurrent CPU activity diagnostic";report.traceDiagnostic=traceDiagnostic;report.readbackDiagnostic=readbackDiagnostic;report.dataPreviewDiagnostic=dataDiagnostic;report.noImagePreviewDiagnostic=noImageDiagnostic;if(noImageDiagnostic)report.boundaries.previewTransport="test-only IMG decoder suppression; real Canvas/toBlob/save unchanged; preview correctness not exercised";if(dataDiagnostic){report.boundaries.previewTransport="test-only stable PNG data URI; separate CSP fixture permits data:; production CSP unchanged";report.previewAssets=JSON.parse(await readFile(resolve(task,"product-preview-assets-manifest.json"),"utf8"));assert.equal(resolve(report.previewAssets.target),assets);assert.equal(report.previewAssets.diagnosticHTMLSHA256,report.assets.htmlSHA256);}if(traceDiagnostic&&bindingsOnly){traceSession=await browser.newBrowserCDPSession();memoryTrace=await startMemoryTrace(traceSession);}
 const idsPath=resolve(task,"product-bitmap-owned.json");
 const script="$ErrorActionPreference='Stop'; $metricIdsPath='"+idsPath.replaceAll("'","''")+"'; $mainProcessId="+child.pid+"; $until=[DateTime]::UtcNow.AddMinutes(60); while([DateTime]::UtcNow -lt $until){ if(-not(Get-Process -Id $mainProcessId -ErrorAction SilentlyContinue)){break}; try{$ids=[IO.File]::ReadAllText($metricIdsPath)|ConvertFrom-Json}catch{continue}; $sum=0L;$parts=@(); foreach($id in $ids){$process=Get-Process -Id $id -ErrorAction SilentlyContinue;if($process){try{$process.Refresh();$ws=$process.WorkingSet64;$sum+=$ws;$parts+=@{id=$id;processName=$process.ProcessName;workingSet64=$ws;privateBytes64=$process.PrivateMemorySize64;handles=$process.HandleCount}}finally{$process.Dispose()}}}; [Console]::WriteLine((@{total=$sum;processes=$parts}|ConvertTo-Json -Depth 4 -Compress)); Start-Sleep -Milliseconds 250}";
 sampler=spawn("powershell.exe",["-NoProfile","-NonInteractive","-Command",script],{windowsHide:true,stdio:["ignore","pipe","pipe"]});samplerExit=new Promise(ok=>{sampler.once("error",()=>{report.metricSamplerFailure=true;ok()});sampler.once("close",ok)});let pending="";sampler.stdout.on("data",chunk=>{pending+=chunk;let at;while((at=pending.indexOf("\n"))>=0){const raw=pending.slice(0,at).trim();pending=pending.slice(at+1);try{const value=JSON.parse(raw);memoryLog.write(JSON.stringify({observedAt:Date.now(),phase:report.phase,cycle:report.iterations,...value})+"\n");if(Number.isFinite(value.total)&&value.total>report.workingSetPeakBytes){report.workingSetPeakBytes=value.total;report.peakWorkingSetParts=value.processes;report.peakWorkingSetPhase=report.phase}}catch{report.metricSamplerFailure=true}}});sampler.stderr.on("data",()=>{report.metricSamplerFailure=true});
 goSampler=setInterval(()=>{if(goSampleBusy)return;goSampleBusy=true;goSamplePending=call("main.Probe.Memory").then(go=>memoryLog.write(JSON.stringify({observedAt:Date.now(),phase:report.phase,cycle:report.iterations,go})+"\n")).catch(()=>{}).finally(()=>{goSampleBusy=false})},250);
 try{const oracle=JSON.parse(await readFile(resolve(task,"participant-preview-oracle.json"),"utf8"));assert.ok(Array.isArray(oracle.rows)&&oracle.rows.length<=100);const checked=await page.evaluate(rows=>{const segmenter=new Intl.Segmenter("ko",{granularity:"grapheme"});return rows.map(({input,preview},index)=>{const prefix=input===preview?preview:preview.endsWith("…")?preview.slice(0,-1):preview;const ends=new Set([0,...[...segmenter.segment(input)].map(part=>part.index+part.segment.length)]);return{index,utf16:preview.length,prefix:input.startsWith(prefix),boundary:ends.has(prefix.length)};});},oracle.rows);for(const row of checked){assert.ok(row.utf16<=256);assert.equal(row.prefix,true);assert.equal(row.boundary,true);}report.previewOracle={cases:checked.length,unicode16Extend:await page.evaluate(()=>[...new Intl.Segmenter("ko",{granularity:"grapheme"}).segment("a"+String.fromCodePoint(0x1e5ee))].length===1),unicode17Extend:await page.evaluate(()=>[...new Intl.Segmenter("ko",{granularity:"grapheme"}).segment("a"+String.fromCodePoint(0x1e6e3))].length===1),browser:browser.version(),passed:true};}catch(error){if(error?.code==="ENOENT")report.previewOracle={available:false};else throw error;}
 const initialMemory=await call("main.Probe.Memory");report.actualGoMemoryLimitBytes=initialMemory.memoryLimitBytes;assert.equal(initialMemory.memoryLimitBytes,goMemoryLimitDiagnostic?"167772160":"9223372036854775807","actual child Go runtime limit");const boot=await call(bootstrapMethod);assert.equal(boot.ok,true);assert.equal(boot.data.pendingOperations.length,0);assert.equal(boot.data.pendingCursor,null);report.bootstrapMethodId=bootstrapMethod;report.bootstrapPreflightPassed=true;
 if(bindingsOnly){if(memoryTrace)await resourceCheckpoint();report.authoritativePending=boot.data.pendingOperations.length;report.status="binding-smoke-passed";}else{
 mediaFixture=await installMediaFixture(page);
 await phase("large-collect");await visible("디시인사이드 게시글 주소").fill((await snapshot()).fixtureURL);await button("게시글 불러오기").click();await expect(button("추첨 생성")).toBeEnabled();await expect(page.locator(".create-participants>li")).toHaveCount(workload.initialRows);
 await resourceCheckpoint();const first=await snapshot();report.fixtureURL=first.fixtureURL;assert.equal(first.fixtureURL.length,119,"actual canonical119 URL required");assert.equal((await call("main.Probe.DraftState")).participants,workload.participants);assert.equal(first.FixtureCalls,3);assert.equal(first.FixtureBodiesClosed,3);
 await phase("native-create-comment-media");report.media=await verifyMediaPanel({page,renderer,fixture:mediaFixture,label:"create",open:async()=>{await page.locator(".create-participants>li").first().getByRole("button",{name:"댓글 보기",exact:true}).click();},close:async()=>{await button("닫기").click();}});
 const searchTimes=[];for(let index=0;index<20;index++){const text=index%2===0?"stress-user-00000":"";await visible("참가자 검색").fill(text);const start=await page.evaluate(()=>performance.now());await visible("참가자 검색").press("Enter");await expect(page.locator(".create-participants>li")).toHaveCount(text===""?workload.initialRows:1);searchTimes.push(await page.evaluate(()=>performance.now())-start);}
 report.searchP95Ms=p95(searchTimes);report.searchSamplesMs=searchTimes;
 let firstToggle;
 const configureSelection=async()=>{
 await visible("글쓴이 제외").uncheck();
 await expect.poll(async()=>(await call("main.Probe.DraftState")).filters.excludeAuthor).toBe(false);
 firstToggle=page.locator(".create-participants>li").first().getByRole("checkbox");
 await firstToggle.uncheck();
 await expect.poll(async()=>(await call("main.Probe.DraftState")).included).toBe(workload.included);
 };
 if(dataDiagnostic||noImageDiagnostic)await configureSelection();
 await visible("상품 구성").selectOption("multiple");await expect(visible("상품명 (선택)")).toHaveCount(1);for(let index=1;index<10;index++){await button("상품 추가").click();await expect(visible("상품명 (선택)")).toHaveCount(index+1);}
 const names=visible("상품명 (선택)");await expect(names).toHaveCount(10);for(let index=0;index<10;index++)await names.nth(index).fill("품목"+index+"한글😀");
 if(dataDiagnostic||noImageDiagnostic){await names.nth(9).blur();await expect.poll(async()=>(await call("main.Probe.DraftState")).prizes.multiple.map(prize=>prize.name)).toEqual(Array.from({length:10},(_,index)=>"품목"+index+"한글😀"));report.selectionOrderDiagnostic="author/manual before text; explicit last blur and authoritative10 prize names barrier";}else await configureSelection();
 const preserved=await call("main.Probe.DraftState");
 const sameSnapshot=(state)=>{assert.equal(state.summary.articleGeneration,preserved.summary.articleGeneration);assert.deepEqual(state.article,preserved.article);assert.deepEqual(state.filters,preserved.filters);assert.deepEqual(state.prizes,preserved.prizes);assert.equal(state.participants,workload.participants);assert.equal(state.included,workload.included)};
 await phase("page2-failure-preserves");
 const failedArmed=await call("main.Probe.ControlFixture","fail-page2");
 await button("게시글 불러오기").click();
 await expect(page.getByText("게시글 수집에 실패했습니다. 주소와 연결 상태를 확인해 주세요.",{exact:true})).toBeVisible();
 await expect(button("추첨 생성")).toBeEnabled();
 const failed=await call("main.Probe.DraftState");assert.equal(failed.load.state,"failed");sameSnapshot(failed);
 assert.equal((await snapshot()).fixtureNetwork.page2Entered,failedArmed.page2Entered+1);
 await expect(firstToggle).not.toBeChecked();
 await phase("page2-block-real-cancel-preserves");
 const cancelArmed=await call("main.Probe.ControlFixture","block-page2");
 await button("게시글 불러오기").click();
 await expect.poll(async()=>(await snapshot()).fixtureNetwork.blocked).toBe(true);
 assert.equal((await snapshot()).fixtureNetwork.page2Entered,cancelArmed.page2Entered+1);
 await button("수집 취소").click();
 await expect(page.getByText("수집을 취소했습니다.",{exact:true})).toBeVisible();
 await expect(button("추첨 생성")).toBeEnabled();
 const cancelled=await call("main.Probe.DraftState");assert.equal(cancelled.load.state,"cancelled");sameSnapshot(cancelled);
 const cancelledReport=await snapshot();assert.equal(cancelledReport.fixtureNetwork.page2Cancelled,cancelArmed.page2Cancelled+1);assert.equal(cancelledReport.fixtureNetwork.blocked,false);assert.equal(cancelledReport.FixtureCalls,cancelledReport.FixtureBodiesClosed);
 await expect(firstToggle).not.toBeChecked();
 report.collectorFaults={failedState:failed.load.state,cancelledState:cancelled.load.state,articleGeneration:preserved.summary.articleGeneration,participants:workload.participants,included:workload.included,page2Entered:cancelledReport.fixtureNetwork.page2Entered,page2Cancelled:cancelledReport.fixtureNetwork.page2Cancelled,bodiesBalanced:true};

 await phase("first-create");await resourceCheckpoint();const drawStart=await page.evaluate(()=>performance.now());await button("추첨 생성").click();await expect(page.getByRole("heading",{name:"추첨 결과",exact:true})).toBeVisible();await expect(page.locator('ol[aria-label="품목별 당첨자"] > li')).toHaveCount(10);report.firstCreateMs=await page.evaluate(()=>performance.now())-drawStart;latest=(await current()).collection;await resourceCheckpoint();assert.equal(latest.rounds[0].winners.length,10);
 await phase("local-rerun-draw-save-samples");const drawSamples=[];
 const drawSampleCount=workload.drawSampleCount;for(let sample=0;sample<drawSampleCount;sample++){
  await button("재추첨").click();const dialog=page.locator("dialog[open]");
  await dialog.locator("select[name=prizeMode]").selectOption("multiple");for(let index=1;index<10;index++){await button("품목 추가").click();await expect(dialog.locator('[name^="manyPrizeName"]')).toHaveCount(index+1);}
  for(let index=0;index<10;index++)await dialog.locator('[name="manyPrizeName'+(index+1)+'"]').fill("품목"+index+"한글😀");
  await page.evaluate(watchRoundCommit,{optionCount:sample+2,prizeCount:10});await button("새 회차 추첨").click();const timing=await page.evaluate(async()=>{const value=window.__jackpotRoundTimer;const result=await value.promise;delete window.__jackpotRoundTimer;return result});assert.equal(timing.ok,true);
  await expect(dialog).toHaveCount(0);await expect(page.locator('select[name=resultRound] option')).toHaveCount(sample+2);
  const collection=(await current()).collection;assert.equal(collection.rounds.at(-1).state,"completed");assert.equal(collection.rounds.at(-1).winners.length,10);
  drawSamples.push(timing.elapsedMs);
  const identities=collection.rounds.flatMap(round=>round.winners.map(winner=>winner.participant.id));assert.equal(new Set(identities).size,identities.length);
 }
 await resourceCheckpoint();report.workload=workload;report.drawObservationOnly=true;report.statisticalSampleSufficient=workload.statisticalSampleSufficient;report.drawSampleCount=drawSampleCount;report.drawSamplesMs=drawSamples;report.drawP95Ms=p95(drawSamples);await writeFile(resolve(task,"product-bitmap-draw.json"),JSON.stringify({drawSamplesMs:drawSamples,drawP95Ms:report.drawP95Ms,drawSampleCount,firstCreateMs:report.firstCreateMs,drawObservationOnly:true,statisticalSampleSufficient:workload.statisticalSampleSufficient,fixtureComments:workload.fixtureComments},null,2));

 await phase("native-frozen-comment-media");report.media.push(...await verifyMediaPanel({page,renderer,fixture:mediaFixture,label:"frozen",open:async()=>{await button("확정 참가자 보기").click();const dialog=page.locator("dialog[open]");await expect(dialog.getByRole("list",{name:"확정 참가자",exact:true}).locator(">li")).toHaveCount(workload.participants);await dialog.locator("button[data-participant-id]").first().click();await expect(dialog.getByRole("list",{name:"저장된 댓글",exact:true}).locator(">li")).toHaveCount(50);},close:async()=>{await button("명단 닫기").click();}}));mediaFixture.setMode("load");

 await phase("render-DPR-theme");for(const dpr of (process.env.JACKPOT_STRESS_SKIP_MATRIX==="1"?[]:[1,1.5,2]))for(const theme of ["light","dark"]){await page.locator('select[name=theme]').selectOption(theme);await renderer.send("Emulation.clearDeviceMetricsOverride");const viewportWidth=dpr===1?1024:dpr===1.5?1100:1280;await renderer.send("Emulation.setDeviceMetricsOverride",{width:viewportWidth,height:800,deviceScaleFactor:dpr,mobile:false});await expect.poll(()=>page.evaluate(()=>devicePixelRatio)).toBe(dpr);const actual=await page.evaluate(()=>devicePixelRatio);const image=await savedPNG("product-bitmap-"+dpr+"-"+theme+".png");report.PNG.push({...image,rendererDPR:actual,viewportWidth:await page.evaluate(()=>innerWidth),theme});await page.screenshot({path:resolve(task,"product-bitmap-ui-"+dpr+"-"+theme+".png")});}
 if(process.env.JACKPOT_STRESS_SKIP_MATRIX!=="1")assert.equal(new Set(report.PNG.map(p=>p.sha256)).size,1);else report.matrixSkippedDiagnostic=true;
 if(readbackDiagnostic){await phase("canvas-readback-comparison");await page.evaluate(()=>{window.__jackpotReadbackHint=false});const defaultPNG=await savedPNG("product-readback-default.png");await page.evaluate(()=>{window.__jackpotReadbackHint=true});const readbackPNG=await savedPNG("product-readback-software.png");report.readbackComparison={defaultPNG,readbackPNG,sameHash:defaultPNG.sha256===readbackPNG.sha256,modes:await page.evaluate(()=>window.__jackpotCanvasModes)};assert.ok(report.readbackComparison.modes.default>0&&report.readbackComparison.modes.readback>0,"both actual context modes required");report.readbackComparison.byteEqualityRequired=false;}
 await renderer.send("Emulation.clearDeviceMetricsOverride");await phase("scope-baseline");await goCreate();await page.locator("html").evaluate(element=>element.nodeName);baseline=await idleMetrics();if(traceDiagnostic){traceSession=await browser.newBrowserCDPSession();memoryTrace=await startMemoryTrace(traceSession);}await resourceCheckpoint();report.baseline=baseline;report.baselineListenerDetails=await nativeListeners();assert.ok(report.baselineListenerDetails.some(entry=>entry.registered));assert.equal(baseline.frames,0);assert.equal(baseline.objectUrls,0);assert.equal(baseline.canvasPixels,0);
 await phase("route-dialog-export-cycles");const iterations=workload.iterations;report.requestedIterations=iterations;for(let index=0;index<iterations;index++){
  await goResult();await button("확정 참가자 보기").click();const dialog=page.locator("dialog[open]");await expect(dialog.getByRole("list",{name:"확정 참가자",exact:true}).locator(">li")).toHaveCount(workload.participants);await dialog.locator("button[data-participant-id]").first().click();
  await expect(dialog.getByRole("list",{name:"저장된 댓글",exact:true}).locator(">li")).toHaveCount(50);await button("다음 댓글 페이지").click();await expect(dialog.getByRole("list",{name:"저장된 댓글",exact:true}).locator(">li")).toHaveCount(10);await button("명단 닫기").click();await expect(dialog).toHaveCount(0);
  await button("PNG 미리보기").click();const preview=page.getByRole("img",{name:"Jackpot 로컬 추첨 결과 미리보기"});await expect(preview).toBeVisible({timeout:20000});if(noImageDiagnostic){await expect.poll(()=>page.evaluate(()=>window.__jackpotNoImageTransport.snapshot().suppressed)).toBe(index+1);assert.deepEqual(await preview.evaluate(img=>({src:img.getAttribute("src"),width:img.naturalWidth})),{src:null,width:0});}else {assert.equal(await preview.evaluate(canvas=>canvas.tagName),"CANVAS");await expect.poll(()=>preview.evaluate(canvas=>canvas.width)).toBe(1200);const bitmap=await page.evaluate(()=>window.__jackpotBitmapProbe.snapshot());assert.equal(bitmap.created,index+1);assert.equal(bitmap.transferred,index+1);assert.equal(bitmap.closed,index+1);assert.equal(bitmap.decodedLive,0);assert.equal(bitmap.failures,0);assert.equal(bitmap.pending,0);assert.ok(bitmap.records.every(record=>record.closed&&record.transferred&&record.detachedAfterTransfer));report.bitmapProbe=bitmap;}if(dataDiagnostic){const uri=await preview.evaluate(async image=>{const src=image.getAttribute("src");if(src===null||!src.startsWith("data:image/png;base64,")||src.length>4*Math.ceil(25*1024*1024/3)+22)throw Error("Invalid actual data preview URI");const hash=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(src));return{chars:src.length,sha256:[...new Uint8Array(hash)].map(byte=>byte.toString(16).padStart(2,"0")).join("")};});(report.previewDataHashes??=[]).push(uri);}
  const saved=await savedPNG("product-bitmap-last.png");if(index===0||index===iterations-1){const displayed=await preview.evaluate(readPreviewCanvas);const oracle=JSON.parse(await new Promise((ok,fail)=>execFile(process.env.JACKPOT_PYTHON || "python",[resolve(root,"frontend/tests/native/preview-png-oracle.py"),saved.path],{windowsHide:true,timeout:15000},(error,stdout)=>error?fail(error):ok(stdout))));assert.deepEqual(displayed,oracle,"displayed decoded RGBA must equal actual saved PNG");(report.bitmapPixels??=[]).push({cycle:index+1,displayed,oracle,png:saved});await preview.screenshot({path:resolve(task,"product-bitmap-preview-"+(index+1)+".png")});}const beforeCopy=await exportState();await button("결과 텍스트 복사").click();await expect.poll(async()=>(await exportState()).copies).toBeGreaterThan(beforeCopy.copies);assert.ok((await exportState()).copiedText.includes("품목0한글😀"));await button("미리보기 닫기").click();await expect(preview).toBeHidden();await goCreate();
  const sample=await idleMetrics();if(noImageDiagnostic){assert.equal((await page.evaluate(()=>window.__jackpotNoImageTransport.snapshot())).activeBlobURLs,0);}if(dataDiagnostic){const state=await page.evaluate(()=>window.__jackpotPreviewTransport.snapshot());assert.equal(state.activeBlobURLs,0);assert.equal(state.pendingReads,0);assert.equal(state.failures,0);}assert.equal(sample.frames,0);assert.equal(page.frames().length,1);assert.equal(sample.objectUrls,0);assert.equal(sample.canvasPixels,0);report.lastListenerDetails=await nativeListeners();assert.equal(sample.listeners,baseline.listeners);assert.equal(report.lastListenerDetails.filter(entry=>entry.registered).length,report.baselineListenerDetails.filter(entry=>entry.registered).length);assert.equal(report.lastListenerDetails.filter(entry=>entry.registered&&!entry.connected).length,0);assert.equal(sample.domNodes,baseline.domNodes);report.samples.push(sample);report.iterations=index+1;
  if(index%10===9){await refreshOwned();await resourceCheckpoint();await phase("route-dialog-export-cycles");console.log("stress cycles "+report.iterations+"/"+iterations);}
 }
 if(dataDiagnostic){assert.equal(new Set(report.previewDataHashes.map(value=>value.sha256)).size,1);report.previewTransport=await page.evaluate(()=>window.__jackpotPreviewTransport.snapshot());assert.equal(report.previewTransport.converted,iterations);}if(noImageDiagnostic){report.noImageTransport=await page.evaluate(()=>window.__jackpotNoImageTransport.snapshot());assert.equal(report.noImageTransport.suppressed,iterations);}report.finalCanvasModes=await page.evaluate(()=>window.__jackpotCanvasModes);report.clickTrace=await page.evaluate(()=>window.__jackpotClickTrace??[]);const bootstrap=await call(bootstrapMethod);assert.equal(bootstrap.ok,true);assert.equal(bootstrap.data.pendingOperations.length,0);assert.equal(bootstrap.data.pendingCursor,null);report.authoritativePending=0;await resourceCheckpoint();
 report.final=await snapshot();assert.equal(report.final.counts.collections,1);assert.equal(report.final.counts.results,drawSampleCount+1);assert.equal(report.final.counts.winners,(drawSampleCount+1)*10);assert.equal(report.final.counts.participants,workload.participants);report.peakWorkingSetMiB=report.workingSetPeakBytes/1048576;report.ownedPIDs=ownedIds;
 report.targets={diagnosticMode:traceDiagnostic||readbackDiagnostic||dataDiagnostic||noImageDiagnostic||goMemoryLimitDiagnostic,searchP95Under200ms:report.searchP95Ms<=200,peakUnder500MiB:!traceDiagnostic&&!readbackDiagnostic&&!dataDiagnostic&&!noImageDiagnostic&&!goMemoryLimitDiagnostic&&report.workingSetPeakBytes<=500*1048576,drawP95Under1s:!traceDiagnostic&&!readbackDiagnostic&&!dataDiagnostic&&!noImageDiagnostic&&!goMemoryLimitDiagnostic&&workload.statisticalSampleSufficient&&report.drawP95Ms<=1000};
 assert.equal(Boolean(report.metricSamplerFailure),false);report.status="passed";}
}catch(error){report.status="failed";report.failure=error instanceof Error?error.message.slice(0,1500):"Unknown failure";process.exitCode=1;if(page){try{report.clickTrace=await page.evaluate(()=>window.__jackpotClickTrace??[]);report.lastDOM=await metrics();const failedDraft=await call("main.Probe.DraftState");report.failedDraftObservation={filters:failedDraft.filters,revision:failedDraft.summary?.revision,articleGeneration:failedDraft.summary?.articleGeneration};await page.screenshot({path:resolve(task,"product-bitmap-failure.png")})}catch{}}}
finally{
 if(mediaFixture){try{await mediaFixture.dispose();report.mediaRoutingRemoved=true;}catch(error){report.mediaCleanupFailure=String(error).slice(0,300);report.status="failed";process.exitCode=1;}}
 if(page){await page.evaluate(()=>{window.__jackpotBitmapProbe?.dispose();window.__jackpotPreviewTransport?.dispose();window.__jackpotNoImageTransport?.dispose();window.__jackpotRoundTimer?.dispose();delete window.__jackpotRoundTimer}).catch(()=>{})}
 await writeFile(reportPath,JSON.stringify(report,null,2)+"\n");
 clearInterval(goSampler);await goSamplePending;report.goSamplerStopped=true;
 if(memoryTrace){try{const trace=await memoryTrace.finish();const path=resolve(task,"product-memory-infra.json");await writeFile(path,trace.data);report.memoryTrace={path,dumps:trace.dumps,dataLossOccurred:trace.dataLossOccurred,bytes:trace.data.length,noForcedGC:true,levelOfDetail:"light",complete:!trace.dataLossOccurred&&trace.dumps.length===(bindingsOnly?1:2)};}catch(error){report.traceFailure=String(error).slice(0,500);report.status="failed";process.exitCode=1;}}await traceSession?.detach().catch(()=>{});
 if(child){await discoverOwned().catch(error=>{report.discoveryFailure=String(error).slice(0,300)});report.ownedPIDs=ownedIds;try{await call("main.Probe.Stop")}catch{child.kill()};const outcome=await exit.catch(()=>({code:-1}));report.exit=outcome;if(outcome.code!==0){report.status="failed";process.exitCode=1;}await browser?.close().catch(()=>{});sampler?.kill();await samplerExit;report.metricSamplerExited=true;
 if(ownedIds.length){const command="$ErrorActionPreference='Stop'; $ownedStressIds=@("+ownedIds.join(",")+"); foreach($ownedId in $ownedStressIds){$process=Get-Process -Id $ownedId -ErrorAction SilentlyContinue;if($process){try{if(-not $process.HasExited -and -not $process.WaitForExit(20000)){exit 1}}finally{$process.Dispose()}}};exit 0";
 try{await new Promise((ok,fail)=>execFile("powershell.exe",["-NoProfile","-NonInteractive","-Command",command],{windowsHide:true,timeout:25000},error=>error?fail(error):ok()));report.ownedProcessesExited=true}catch(error){report.cleanupFailure=true;report.ownedExitFailure=String(error).slice(0,500);report.status="failed";process.exitCode=1;}}}
 if(!report.cleanupFailure){assert.ok(work.startsWith(task+sep)&&work.includes("product-run-stress-"));
 const target=work.replaceAll("'","''"),prefix=(task+sep).replaceAll("'","''");
 const command="$ErrorActionPreference='Stop';$target='"+target+"';$prefix='"+prefix+"';$absolute=[IO.Path]::GetFullPath($target);if(-not $absolute.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)-or -not [IO.Path]::GetFileName($absolute).StartsWith('product-run-stress-',[StringComparison]::Ordinal)){throw 'Cleanup path rejected'};$until=[DateTime]::UtcNow.AddSeconds(20);$unlocked=$false;do{try{foreach($file in Get-ChildItem -LiteralPath $absolute -File -Recurse){$stream=[IO.File]::Open($file.FullName,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::None);$stream.Dispose()};$unlocked=$true}catch{Start-Sleep -Milliseconds 100}}while(-not $unlocked -and [DateTime]::UtcNow -lt $until);if(-not $unlocked){throw 'Owned profile lock remained'};Remove-Item -LiteralPath $absolute -Recurse -Force;if(Test-Path -LiteralPath $absolute){throw 'Owned directory still present'}";
 try{await runPS(command);report.cleanup="owned DB/profile removed after exclusive-open proof";report.ownedProcessesExited=true}catch(error){report.cleanupFailure=true;report.cleanupMessage=String(error).slice(0,300);process.exitCode=1;report.status="failed";}}

 await new Promise(ok=>memoryLog.end(ok));finalizePeak(report);if(report.targets){report.targets.diagnosticMode=true;report.targets.peakUnder500MiB=false;report.targets.drawP95Under1s=false;}await writeFile(reportPath,JSON.stringify(report,null,2)+"\n");await writeFile(resolve(task,bindingsOnly?"product-bindings-live.json":"product-bitmap-live.json"),JSON.stringify({status:report.status,phase:report.phase,iterations:report.iterations,ownedPIDs:ownedIds,peakBytes:report.workingSetPeakBytes}));console.log(JSON.stringify({status:report.status,iterations:report.iterations,phase:report.phase,peakMiB:report.peakWorkingSetMiB,report:reportPath}));
}
