// Real pinned Vite updates in a separate Wails debug host, copied source and
// exclusive WebView profile. Production assets and backend owners stay intact.
import assert from "node:assert/strict";
import {spawn,execFile} from "node:child_process";
import {mkdtemp,readFile,writeFile,copyFile,cp,symlink,rmdir,access} from "node:fs/promises";
import {createServer as createPortServer} from "node:net";
import {resolve,dirname} from "node:path";
import {fileURLToPath} from "node:url";
import {createHash} from "node:crypto";
import {createServer as createViteServer} from "vite";
import {chromium,expect} from "@playwright/test";
import {installHmrProbe} from "./hmr.probe.mjs";

const root=fileURLToPath(new URL("../../../",import.meta.url)),task=resolve(root,".task"),frontend=resolve(root,"frontend");
const cycles=Number(process.env.JACKPOT_HMR_CYCLES??100);assert.ok(cycles===1||cycles===100,"owned full100 or focused full-reload validation");
const reportStem=process.env.JACKPOT_HMR_REPORT_STEM??(cycles===100?"product-hmr":"product-hmr-fullreload");assert.match(reportStem,/^[a-z0-9][a-z0-9-]{0,80}$/);
const reportPath=resolve(task,reportStem+"-report.json"),work=await mkdtemp(resolve(task,"product-run-hmr-")),copy=await mkdtemp(resolve(task,"product-hmr-assets-"));
assert.equal(dirname(work),task);assert.equal(dirname(copy),task);
const exe=resolve(copy,"product-hmr.exe"),digest=async path=>createHash("sha256").update(await readFile(path)).digest("hex");
await access(resolve(task,"product-hmr-dev.exe"));await copyFile(resolve(task,"product-hmr-dev.exe"),exe);
for(const name of["src","bindings","index.html","package.json","tsconfig.json"])await cp(resolve(frontend,name),resolve(copy,name),{recursive:true});
await symlink(resolve(frontend,"node_modules"),resolve(copy,"node_modules"),"junction");
const originalMain=await readFile(resolve(copy,"src/main.ts"),"utf8");
const report={status:"running",startedAt:new Date().toISOString(),profileDirectory:work,copiedDirectory:copy,cycles:0,checks:[],level:"pinned-Vite-loopback-actual-Wails-WebView2",productionHTMLBefore:await digest(resolve(frontend,"dist/index.html")),hostSHA256:await digest(exe),sourceSHA256:{},events:[],boundary:{physicalInput:false,productionDistChanged:false,backendOwner:"actual copied debug host; unchanged Go services",instrumentation:"test-only copied modules; primitive Scope/workspace/coordinator probes; weak DOM refs",timing:"functional gate, not performance sample"}};
for(const path of["src/main.ts","src/app/runtime.ts","src/screens/create/productOwner.ts","src/operations/productCoordinator.ts","src/features/create/view.ts","src/features/results/view.ts","src/contracts/product.ts","src/platform/product.ts","src/platform/querySize.ts","src/app/routes.ts","bindings/github.com/porkyx/jackpot/internal/contracts/models.ts","index.html"])report.sourceSHA256[path]=await digest(resolve(copy,path));
const expectedCopiedSHA={...report.sourceSHA256};
const writeOwned=async(path,contents)=>{assert.equal(await digest(resolve(copy,path)),expectedCopiedSHA[path],"private copied source drift "+path);await writeFile(resolve(copy,path),contents);expectedCopiedSHA[path]=createHash("sha256").update(contents).digest("hex");};
const exact=(text,from,to)=>{assert.equal(text.split(from).length-1,1,"instrumentation anchor "+from);return text.replace(from,to);};
const plugin={name:"owned-hmr-lifetime-observer",enforce:"pre",transform(code,id){
 code=code.replaceAll("\r\n","\n");
 if(id===resolve(copy,"src/app/runtime.ts").replaceAll("\\","/")){
  code=exact(code,"const runtime = ManagedRuntime.make(layer);","const hmrToken = globalThis.__hmrProbe?.open(); const runtime = ManagedRuntime.make(layer);");
  code=exact(code,"const startup = runtime.runFork", "Effect.runSync(Scope.addFinalizer(appScope, Effect.promise(() => globalThis.__hmrProbe?.gate() ?? Promise.resolve()))); const startup = runtime.runFork");
  code=exact(code,').finally(() => { phase = "stopped"; });',').finally(() => { phase = "stopped"; globalThis.__hmrProbe?.closed(hmrToken, [runtime.scope.state._tag, appScope.state._tag, screens.state._tag], startup.pollUnsafe() !== undefined); });');
  code=exact(code,"return {\n    ready, phase:","const hmrOwner = {\n    ready, phase:");
  code=exact(code,"  };\n}\n\nexport interface RuntimeHotData", "  }; globalThis.__hmrProbe?.register(hmrOwner); return hmrOwner;\n}\n\nexport interface RuntimeHotData");
  code=exact(code,"void disposal.catch(onDisposeFailure);","void disposal.catch(error => { globalThis.__hmrProbe?.failure(); onDisposeFailure(error); });");
 }else if(id===resolve(copy,"src/screens/create/productOwner.ts").replaceAll("\\","/"))code=exact(code,"return workspace;","globalThis.__hmrProbe?.workspace(workspace); return workspace;");
 else if(id===resolve(copy,"src/operations/productCoordinator.ts").replaceAll("\\","/"))code=exact(code,"yield* SubscriptionRef.set(state,null);yield* PubSub.shutdown(state.pubsub);","yield* SubscriptionRef.set(state,null);yield* PubSub.shutdown(state.pubsub);globalThis.__hmrProbe?.coordinator({entries:entries.size,queue:queue.length,unknownDurable:unknownDurable.size,unknownDraft:unknownDraft.size,barriers:barriers.size,retired:retired.size,cache:collectionCache.size(),collectionFlights:collectionFlights.size});");
 return code;
}};
const runPS=command=>new Promise((ok,fail)=>execFile("powershell.exe",["-NoProfile","-NonInteractive","-Command",command],{windowsHide:true,timeout:30000},(error,stdout)=>error?fail(error):ok(stdout)));
const deadline=async(promise,ms)=>{let timer;try{return await Promise.race([promise,new Promise((_,fail)=>{timer=setTimeout(()=>fail(new Error("deadline")),ms);})]);}finally{clearTimeout(timer);}};
const freePort=async()=>{const server=createPortServer();await new Promise((ok,fail)=>{server.once("error",fail);server.listen(0,"127.0.0.1",ok);});const port=server.address().port;await new Promise((ok,fail)=>server.close(error=>error?fail(error):ok()));return port;};
let vite,child,browser,page,renderer,exit,owned=[],stopped=false,resultCollectionId;
async function discover(){const proof=work.replaceAll("'","''");const raw=await runPS("$ErrorActionPreference='Stop'; $hmrProfile='"+proof+"'; Get-CimInstance Win32_Process -Filter \"Name='msedgewebview2.exe'\" | Where-Object {$_.CommandLine -like ('*'+$hmrProfile+'*')} | ForEach-Object {$_.ProcessId}");const ids=raw.trim()===""?[]:raw.trim().split(/\s+/).map(Number);assert.ok(ids.every(id=>Number.isSafeInteger(id)&&id>0));owned=[...new Set([...owned,...ids])];}
const call=(method,...args)=>page.evaluate(async({method,args})=>{const dispatch=window._wails.dispatchWailsEvent;const{Call}=await import("/wails/runtime.js");window._wails.dispatchWailsEvent=dispatch;return Call.ByName("main.Probe."+method,...args);},{method,args});
const button=name=>page.getByRole("button",{name,exact:true}),visible=name=>page.getByLabel(name,{exact:true}).and(page.locator(":visible")),probe=()=>page.evaluate(()=>window.__hmrProbe.snapshot());
const check=async(name,run)=>{report.phase=name;await run();report.checks.push(name);console.log("HMR PASS "+name);};
async function nativeListeners(){const result=await renderer.send("Runtime.evaluate",{expression:"window.__hmrProbe.nativeDetails(getEventListeners)",includeCommandLineAPI:true,returnByValue:true});assert.equal(result.exceptionDetails,undefined);return result.result.value;}
async function readyResult(){await expect(page.getByRole("heading",{name:"추첨 결과",exact:true})).toBeVisible();await expect(button("PNG 미리보기")).toBeEnabled();await expect.poll(async()=>(await probe()).phase).toBe("running");}
async function idle(){await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await expect.poll(async()=>{const r=(await probe()).resources;return r.frames===0&&r.urls===0&&r.canvasPixels===0;}).toBe(true);return(await probe()).resources;}
async function stop(){if(stopped||!child)return;stopped=true;await discover();try{await call("Stop");}catch{if(child.exitCode===null)child.kill();}const finished=await deadline(exit,20000);report.hostExit=finished;await renderer?.detach().catch(()=>{});await browser?.close().catch(()=>{});await expect.poll(async()=>Number((await runPS("@(Get-Process -Id "+owned.join(",")+" -ErrorAction SilentlyContinue).Count")).trim()),{timeout:20000}).toBe(0);report.ownedPIDExit={count:owned.length,remaining:0,ids:owned};assert.equal(finished.code,0);assert.equal(finished.signal,null);}
try{
 vite=await createViteServer({configFile:resolve(frontend,"vite.config.mjs"),root:copy,cacheDir:resolve(copy,".vite"),plugins:[plugin],server:{host:"127.0.0.1",port:5173,strictPort:true,allowedHosts:["wails.localhost"],ws:{host:"127.0.0.1",port:5173}}});await vite.listen();
 for(const path of["/src/app/runtime.ts","/src/screens/create/productOwner.ts","/src/operations/productCoordinator.ts"])await vite.transformRequest(path);
 const cdp=await freePort();child=spawn(exe,["-assets",copy,"-work-dir",work,"-cdp-port",String(cdp)],{cwd:root,env:{...process.env,FRONTEND_DEVSERVER_URL:"http://127.0.0.1:5173"},windowsHide:true,shell:false,stdio:["ignore","pipe","pipe"]});exit=new Promise((ok,fail)=>{child.once("error",fail);child.once("exit",(code,signal)=>ok({code,signal}));});void exit.catch(()=>{});owned=[child.pid];let stdout="";child.stdout.on("data",chunk=>{stdout=(stdout+chunk.toString()).slice(-4096);});child.stderr.on("data",chunk=>{report.hostLastError=chunk.toString().slice(-800);});
 await expect.poll(()=>{if(child.exitCode!==null)throw new Error("native startup");return stdout.includes("JACKPOT_PRODUCT_E2E_READY");},{timeout:30000}).toBe(true);await expect.poll(async()=>{try{return(await(await fetch(`http://127.0.0.1:${cdp}/json/list`)).json()).some(target=>target.type==="page");}catch{return false;}},{timeout:20000}).toBe(true);
 browser=await chromium.connectOverCDP(`http://127.0.0.1:${cdp}`,{timeout:20000,isWebView:true});const pages=browser.contexts().flatMap(context=>context.pages());assert.equal(pages.length,1);page=pages[0];page.setDefaultTimeout(20000);await page.waitForURL(url=>url.protocol!=="about:",{timeout:20000});renderer=await page.context().newCDPSession(page);await renderer.send("Emulation.setFocusEmulationEnabled",{enabled:true});page.on("console",message=>{if(message.type()==="error")(report.consoleErrors??=[]).push(message.text().slice(0,500));});page.on("pageerror",error=>{(report.pageErrors??=[]).push(error.message.slice(0,500));});page.on("requestfailed",request=>{(report.requestFailures??=[]).push({url:request.url(),reason:request.failure()?.errorText});});page.on("response",response=>{if(response.status()>=400)(report.badResponses??=[]).push({url:response.url(),status:response.status()});});await page.exposeBinding("__hmrRecord",(_source,value)=>{report.events.push(value);});await page.addInitScript(installHmrProbe);await page.reload();await expect(visible("디시인사이드 게시글 주소")).toBeEnabled({timeout:30000});await discover();report.engine=browser.version();
 await check("actual-devserver-entry-is-self-accepted",async()=>{const compiled=await(await fetch("http://127.0.0.1:5173/src/main.ts")).text();assert.ok(compiled.includes("import.meta.hot.accept()"));assert.ok(compiled.includes("createHotContext"));report.devserver={host:"127.0.0.1",port:5173,vite:"8.3.3",externalAssetProxy:true};});
 await check("setup-real-collector",async()=>{await visible("디시인사이드 게시글 주소").fill("https://gall.dcinside.com/board/view/?id=producte2e&no=1");await button("게시글 불러오기").click();await expect(button("추첨 생성")).toBeEnabled();});
 await check("app-owned-unsent-raw-survives-route-and-is-discarded-on-real-HMR",async()=>{const name=visible("상품명 (선택)");await name.fill("저장 상품");await name.blur();await expect.poll(async()=>(await call("DraftState")).prizes.single.name).toBe("저장 상품");await name.evaluate(input=>{window.__hmrDetached=input;input.dispatchEvent(new CompositionEvent("compositionstart",{bubbles:true}));input.value="미전송😀";input.dispatchEvent(new InputEvent("input",{bubbles:true,isComposing:true}));});await page.evaluate(()=>{window.location.hash="#/unrecognized"});await expect(page.getByRole("heading",{name:"화면을 찾을 수 없습니다",exact:true})).toBeVisible();await page.locator('nav a[href="#/create"]').click();await expect(name).toHaveValue("미전송😀");assert.equal((await call("DraftState")).prizes.single.name,"저장 상품");const before=await probe();await writeOwned("src/main.ts",originalMain+"\n// owned raw HMR boundary\n");await expect.poll(async()=>(await probe()).opened).toBe(before.opened+1);await expect(name).toHaveValue("저장 상품");assert.equal((await call("DraftState")).prizes.single.name,"저장 상품");const after=await probe();assert.equal(after.maxActive,1);assert.equal(after.closures.at(-1).editorNull,true);assert.equal(after.closures.at(-1).workspaceClosed,true);assert.equal(await page.evaluate(()=>window.__hmrDetached.isConnected),false);await page.evaluate(()=>{delete window.__hmrDetached;});});
 await check("setup-one-real-durable-collection",async()=>{await button("추첨 생성").click();await readyResult();const saved=await call("Report");assert.equal(saved.counts.collections,1);resultCollectionId=saved.latest[0].collectionId;assert.ok(typeof resultCollectionId==="string"&&resultCollectionId.length>0);});
 await page.locator(".shell").evaluate(()=>true);const baseline=await idle(),nativeBaseline=await nativeListeners();report.baseline={resources:baseline,nativeRegistered:nativeBaseline.filter(value=>value.registered).length};assert.equal(nativeBaseline.filter(value=>value.registered&&!value.connected).length,0);
 await check(cycles+"-route-dialog-export-and-actual-module-disposal-handoffs",async()=>{
  for(let index=1;index<=cycles;index++){
   await page.locator('nav a[href="#/create"]').click();await expect(page.getByRole("heading",{name:"추첨 만들기",exact:true})).toBeVisible();await page.evaluate(id=>{window.location.hash="#/results/"+encodeURIComponent(id)},resultCollectionId);await readyResult();
   await button("PNG 미리보기").click();const image=page.getByAltText("Jackpot 로컬 추첨 결과 미리보기");await expect(image).toBeVisible();await expect.poll(()=>image.evaluate(value=>value.complete&&value.naturalWidth>0)).toBe(true);await button("확정 참가자 보기").click();await expect(page.locator("dialog[open]")).toHaveCount(1);const before=await probe();assert.equal(before.resources.urls,1);
   if(index===2)await page.evaluate(()=>window.__hmrProbe.hold());
   await writeOwned("src/main.ts",originalMain+`\n// owned actual HMR iteration ${index}\n`);
   if(index===2){await expect.poll(async()=>(await probe()).gateEntered).toBe(true);const waiting=await probe();assert.equal(waiting.opened,before.opened);assert.equal(waiting.active,1);assert.equal(waiting.phase,"stopping");await page.evaluate(()=>window.__hmrProbe.release());}
   await expect.poll(async()=>(await probe()).opened).toBe(before.opened+1);await readyResult();await expect(page.locator("dialog[open]")).toHaveCount(0);const after=await probe();assert.equal(after.active,1);assert.equal(after.maxActive,1);assert.equal(after.closed,after.opened-1);assert.equal(after.failures,0);const previous=after.closures.at(-1);assert.deepEqual(previous.scopes,["Closed","Closed","Closed"]);assert.equal(previous.startupDone,true);assert.equal(previous.workspaceClosed,true);assert.equal(previous.editorNull,true);assert.equal(previous.draftNull,true);assert.equal(previous.keywordEmpty,true);assert.equal(previous.resources.urls,0);assert.equal(previous.resources.canvasPixels,0);assert.equal(previous.resources.frames,0);assert.ok(Object.values(after.coordinators.at(-1)).every(value=>value===0));
   const resources=await idle();assert.deepEqual(resources,baseline);const registrations=await nativeListeners();assert.equal(registrations.filter(value=>value.registered).length,report.baseline.nativeRegistered);assert.equal(registrations.filter(value=>value.registered&&!value.connected).length,0);report.cycles=index;if(index%10===0)console.log("actual HMR cycles "+index);
  }
 });
 await check("two-Vite-full-reloads-await-cleanup-and-retain-fresh-document-baselines",async()=>{report.fullReloadBaselines=[];for(let index=0;index<2;index++){const before=report.events.length;let navigated=false;const navigation=page.waitForEvent("framenavigated",{predicate:frame=>frame===page.mainFrame()}).then(()=>{navigated=true;});if(index===0)await page.evaluate(()=>window.__hmrProbe.hold());await writeOwned("index.html",(await readFile(resolve(copy,"index.html"),"utf8"))+`\n<!-- owned full reload ${index} -->\n`);if(index===0){await expect.poll(async()=>(await probe()).gateEntered).toBe(true);assert.equal(navigated,false);assert.equal((await probe()).phase,"stopping");await page.evaluate(()=>window.__hmrProbe.release());}await navigation;await readyResult();await expect.poll(()=>report.events.length).toBe(before+1);const old=report.events.at(-1);assert.deepEqual(old.scopes,["Closed","Closed","Closed"]);assert.equal(old.workspaceClosed,true);assert.equal(old.resources.urls,0);assert.equal(old.resources.canvasPixels,0);assert.equal(old.resources.frames,0);assert.equal((await call("Report")).counts.collections,1);await page.locator(".shell").evaluate(()=>true);const resources=await idle(),registered=await nativeListeners();assert.equal(registered.filter(value=>value.registered&&!value.connected).length,0);const fresh={resources,nativeRegistered:registered.filter(value=>value.registered).length};report.fullReloadBaselines.push(fresh);if(index===1)assert.deepEqual(fresh,report.fullReloadBaselines[0]);}});
 await check("normal-exit-repeated-dispose-and-three-Scopes-at-baseline",async()=>{await page.evaluate(async()=>{const first=window.__hmrProbe.dispose();const second=window.__hmrProbe.dispose();if(first!==second)throw new Error("Dispose identity");await first;});const end=await probe();assert.equal(end.active,0);assert.equal(end.opened,end.closed);assert.equal(end.resources.urls,0);assert.equal(end.resources.canvasPixels,0);assert.equal(end.resources.frames,0);assert.ok(Object.values(end.coordinators.at(-1)).every(value=>value===0));report.final=end;});
 await stop();report.status="passed";
}catch(error){report.status="failed";report.failedStep=report.phase;report.errorClass=error?.name??"Unknown";report.error=String(error?.message??error).slice(0,1600);process.exitCode=1;if(page){try{report.failedPage={url:page.url(),html:await page.content()};await page.screenshot({path:resolve(task,reportStem+"-failure.png")});}catch{}try{report.failedProbe=await probe();}catch{}}}
finally{
 try{await stop();}catch(error){report.cleanupFailure=String(error?.message??error).slice(0,400);process.exitCode=1;if(child?.exitCode===null)child.kill();}await vite?.close();
 if(!report.cleanupFailure||report.ownedPIDExit?.remaining===0){const escaped=work.replaceAll("'","''"),ownedRoot=task.replaceAll("'","''");try{const files=await runPS("$ErrorActionPreference='Stop'; $hmrWork=[IO.Path]::GetFullPath('"+escaped+"'); if((Split-Path -Parent $hmrWork) -ne '"+ownedRoot+"' -or (Split-Path -Leaf $hmrWork) -notlike 'product-run-hmr-*'){throw 'scope'}; $hmrFiles=@(Get-ChildItem -LiteralPath $hmrWork -File -Recurse -Force); foreach($hmrFile in $hmrFiles){$hmrStream=[IO.File]::Open($hmrFile.FullName,[IO.FileMode]::Open,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None);$hmrStream.Dispose()}; Remove-Item -LiteralPath $hmrWork -Recurse -Force; Write-Output $hmrFiles.Count");report.profileCleanup={exclusiveFiles:Number(files.trim()),removed:true};}catch(error){report.cleanupFailure=String(error?.message??error).slice(0,400);process.exitCode=1;}}
 await rmdir(resolve(copy,"node_modules")).catch(error=>{report.junctionCleanupFailure=error.code;process.exitCode=1;});report.productionHTMLAfter=await digest(resolve(frontend,"dist/index.html"));report.sharedAssetsExternallyChanged=report.productionHTMLAfter!==report.productionHTMLBefore;report.wrapperAssetStatus=report.sharedAssetsExternallyChanged?"external-change-observed":"unchanged";report.copiedSourceAfterSHA={};try{for(const[path,expected]of Object.entries(expectedCopiedSHA)){const actual=await digest(resolve(copy,path));report.copiedSourceAfterSHA[path]=actual;assert.equal(actual,expected,"private copied source drift "+path);}report.copiedSourceVerified=true;}catch(error){report.copiedSourceVerified=false;report.copiedSourceFailure=String(error?.message??error);process.exitCode=1;}report.endedAt=new Date().toISOString();await writeFile(reportPath,JSON.stringify(report,null,2)+"\n");console.log(JSON.stringify({status:report.status,phase:report.phase,cycles:report.cycles,report:reportPath,cleanupFailure:report.cleanupFailure,sharedAssetsExternallyChanged:report.sharedAssetsExternallyChanged}));
}
