import {test} from "node:test";
import assert from "node:assert/strict";
import {installNoImagePreview} from "./stress.noimage.mjs";
function environment(){
 let count=0;const revoked=[];
 class Element{constructor(){this.attributes=new Map();}removeAttribute(name){this.attributes.delete(name);}}
 class Image extends Element{constructor(){super();this.alt="Jackpot 로컬 추첨 결과 미리보기";}set src(value){this.attributes.set("src",String(value));}get src(){return this.attributes.get("src");}}
 const host={URL:{createObjectURL:()=>"blob:owned-"+ ++count,revokeObjectURL:url=>revoked.push(url)},Element,HTMLImageElement:Image};
 return {host,Image,revoked,stats:()=>host.__jackpotNoImageTransport.snapshot()};
}
const png=(size=1)=>({type:"image/png",size});
test("invalid decoder isolation bounds do not modify native APIs",()=>{for(const maxBytes of [0,-1,1.5,NaN,Infinity,25*1024*1024+1]){const e=environment(),original=e.host.URL.createObjectURL;assert.throws(()=>installNoImagePreview({maxBytes},e.host));assert.equal(e.host.URL.createObjectURL,original);}});
test("minimum and exact maximum real PNG blobs suppress only the decoder",()=>{for(const size of [1,25*1024*1024]){const e=environment();installNoImagePreview({},e.host);const image=new e.Image();image.attributes.set("src","data:previous");const uri=e.host.URL.createObjectURL(png(size));assert.doesNotThrow(()=>{image.src=uri;});assert.equal(image.src,undefined);assert.equal(e.stats().suppressed,1);assert.equal(e.stats().activeBlobURLs,1);assert.deepEqual(e.revoked,[]);image.removeAttribute("src");e.host.URL.revokeObjectURL(uri);assert.equal(e.stats().activeBlobURLs,0);assert.deepEqual(e.revoked,[uri]);}});
test("foreign media and nonblob inputs retain native behavior",()=>{const e=environment();installNoImagePreview({},e.host);for(const [alt,src] of [["디시콘 이미지","blob:foreign"],["Jackpot 로컬 추첨 결과 미리보기","https://example.invalid/a.png"],["Jackpot 로컬 추첨 결과 미리보기",null]]){const image=new e.Image();image.alt=alt;assert.doesNotThrow(()=>{image.src=src;});assert.equal(image.src,String(src));}assert.equal(e.stats().suppressed,0);});
test("unknown, wrong MIME, empty, fractional and oversized owned blob fail visibly",()=>{const e=environment();installNoImagePreview({maxBytes:3},e.host);const image=new e.Image();assert.throws(()=>{image.src="blob:unknown";},/Invalid owned preview PNG/);for(const blob of [{type:"image/gif",size:1},png(0),png(NaN),png(1.5),png(4)]){const uri=e.host.URL.createObjectURL(blob);assert.throws(()=>{image.src=uri;},/Invalid owned preview PNG/);e.host.URL.revokeObjectURL(uri);}assert.equal(e.stats().suppressed,0);assert.equal(e.stats().activeBlobURLs,0);});
test("first, Nth, continuous native create failures leave no owned metadata",()=>{const e=environment();let calls=0;e.host.URL.createObjectURL=()=>{if(++calls!==2)throw Error("create failed");return "blob:actual"};installNoImagePreview({},e.host);for(let index=0;index<4;index++){if(index===1){const uri=e.host.URL.createObjectURL(png());const image=new e.Image();image.src=uri;e.host.URL.revokeObjectURL(uri);}else assert.throws(()=>e.host.URL.createObjectURL(png()),/create failed/);}assert.equal(e.stats().activeBlobURLs,0);assert.equal(e.stats().suppressed,1);});
test("native revoke failure remains observable and disposal can retry cleanup",()=>{const e=environment();let failing=true;e.host.URL.revokeObjectURL=()=>{if(failing)throw Error("revoke failed");};installNoImagePreview({},e.host);const uri=e.host.URL.createObjectURL(png());assert.throws(()=>e.host.URL.revokeObjectURL(uri),/revoke failed/);assert.equal(e.stats().activeBlobURLs,1);assert.throws(()=>e.host.__jackpotNoImageTransport.dispose(),/revoke failed/);failing=false;e.host.__jackpotNoImageTransport.dispose();assert.equal(e.stats().activeBlobURLs,0);});
test("dispose releases every owned URL once and later sources use native setter",()=>{const e=environment();installNoImagePreview({},e.host);const first=e.host.URL.createObjectURL(png()),second=e.host.URL.createObjectURL(png());e.host.__jackpotNoImageTransport.dispose();e.host.__jackpotNoImageTransport.dispose();assert.deepEqual(e.revoked,[first,second]);assert.equal(e.stats().disposed,true);assert.equal(e.stats().activeBlobURLs,0);const image=new e.Image();assert.doesNotThrow(()=>{image.src="blob:after-dispose";});assert.equal(image.src,"blob:after-dispose");});