import assert from "node:assert/strict";
import test from "node:test";
import {installFrozenReadTrace}from "./stress.frozen.mjs";
const methodID=249898922;
const query=(offset=0,extra={})=>({body:JSON.stringify({object:0,method:0,args:{methodID,args:[{offset,limit:50,expectedRevision:21,...extra}]}})});
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function host(fetch){let at=0;return{fetch,performance:{now:()=>++at}};}
const response=(value={ok:true,data:{revision:21,offset:50,total:60,rows:Array(10).fill({text:"private data"})}})=>({ok:true,clone:()=>({json:async()=>value})});
test("native fetch promise and response identity unchanged with only public projection",async()=>{const r=response(),promise=Promise.resolve(r);let receiver;const native=function(){receiver=this;return promise;};const h=host(native),o=installFrozenReadTrace({methodID},h);const actual=h.fetch("/wails/runtime",query(50,{password:"secret"}));assert.equal(actual,promise);assert.equal(await actual,r);await tick();assert.equal(receiver,h);const s=o.snapshot();assert.equal(s.pendingRequests,0);assert.equal(s.pendingProjections,0);assert.deepEqual(s.records,[{sequence:1,startedAt:1,offset:50,limit:50,expectedRevision:21,headersAt:2,httpOK:true,completedAt:3,ok:true,code:undefined,revision:21,responseOffset:50,total:60,rows:10}]);assert.ok(!JSON.stringify(s).includes("secret"));assert.ok(!JSON.stringify(s).includes("private"));o.dispose();assert.equal(h.fetch,native);assert.equal(h.__jackpotFrozenReads,undefined);o.dispose();});
test("native pending query barrier recorded without resolving or cancelling request",async()=>{let complete;const promise=new Promise(ok=>{complete=ok;});const h=host(()=>promise),o=installFrozenReadTrace({methodID},h);assert.equal(h.fetch("/wails/runtime",query()),promise);assert.equal(o.snapshot().pendingRequests,1);complete(response());await tick();assert.equal(o.snapshot().pendingRequests,0);assert.equal(o.snapshot().records[0].rows,10);o.dispose();});
test("bounded record eviction tracks loss while every request remains unchanged",async()=>{const promise=Promise.resolve(response());const h=host(()=>promise),o=installFrozenReadTrace({methodID,capacity:1},h);for(let i=0;i<4;i++)assert.equal(h.fetch("/wails/runtime",query(i*50)),promise);await tick();assert.equal(o.snapshot().records.length,1);assert.equal(o.snapshot().records[0].sequence,4);assert.equal(o.snapshot().dropped,3);assert.equal(o.snapshot().pendingRequests,0);o.dispose();});
test("foreign method malformed JSON oversized and noninteger query are ignored",async()=>{let calls=0;const h=host(()=>{calls++;return Promise.resolve(response());}),o=installFrozenReadTrace({methodID},h);const foreign=query();foreign.body=foreign.body.replace(String(methodID),"1");for(const init of [foreign,{body:"{"},{body:"x".repeat(4097)},query(1.5),{body:"{}"},{body:new Uint8Array([0])},undefined])await h.fetch("/wails/runtime",init);await tick();assert.equal(calls,7);assert.equal(o.snapshot().records.length,0);o.dispose();});
for(const failed of [1,2,"all"])test("first Nth continuous native rejection propagates without retry "+failed,async()=>{let calls=0;const reason=Object.assign(new Error("secret detail"),{name:"AbortError"});const h=host(()=>{calls++;return failed==="all"||calls===failed?Promise.reject(reason):Promise.resolve(response());}),o=installFrozenReadTrace({methodID},h);for(let i=0;i<3;i++){if(failed==="all"||i+1===failed)await assert.rejects(h.fetch("/wails/runtime",query()),error=>error===reason);else await h.fetch("/wails/runtime",query());}await tick();assert.equal(calls,3);assert.equal(o.snapshot().pendingRequests,0);assert.equal(o.snapshot().records.filter(r=>r.cancelled).length,failed==="all"?3:1);assert.ok(!JSON.stringify(o.snapshot()).includes("secret"));o.dispose();});
test("synchronous native failure remains same thrown error and balances pending",()=>{const reason=new Error("private failure");const h=host(()=>{throw reason;}),o=installFrozenReadTrace({methodID},h);assert.throws(()=>h.fetch("/wails/runtime",query()),error=>error===reason);assert.equal(o.snapshot().pendingRequests,0);assert.equal(o.snapshot().records[0].synchronousFailure,true);o.dispose();});
for(const stage of ["clone","json-throw","json-reject"])test("projection failure never changes caller response "+stage,async()=>{const r={ok:false,clone:()=>{if(stage==="clone")throw Error("private clone");return{json:()=>{if(stage==="json-throw")throw Error("private JSON");return Promise.reject(Error("private JSON"));}};}};const h=host(()=>Promise.resolve(r)),o=installFrozenReadTrace({methodID},h);assert.equal(await h.fetch("/wails/runtime",query()),r);await tick();assert.equal(o.snapshot().records[0].projectionFailure,true);assert.equal(o.snapshot().pendingProjections,0);o.dispose();});
test("Scope disposal before late response drops observation and restores fetch",async()=>{let complete;const native=()=>new Promise(ok=>{complete=ok;});const h=host(native),o=installFrozenReadTrace({methodID},h);const actual=h.fetch("/wails/runtime",query());o.dispose();assert.equal(h.fetch,native);const r=response();complete(r);assert.equal(await actual,r);await tick();assert.equal(o.snapshot().records.length,0);assert.equal(o.snapshot().pendingRequests,0);assert.equal(o.snapshot().pendingProjections,0);});
test("header protocol failure projected without secret strings",async()=>{const h=host(()=>Promise.resolve(response({ok:false,code:"StorageUnavailable",message:"secret",data:{revision:NaN,offset:1.5,total:undefined,rows:null}}))),o=installFrozenReadTrace({methodID},h);await h.fetch("/wails/runtime",query());await tick();const r=o.snapshot().records[0];assert.equal(r.ok,false);assert.equal(r.code,"StorageUnavailable");assert.equal(r.rows,undefined);assert.equal(r.revision,undefined);assert.ok(!JSON.stringify(o.snapshot()).includes("secret"));o.dispose();});
test("ownership conflicts and option boundaries fail loudly",()=>{for(const input of [{methodID:0},{methodID:4294967296},{methodID:1.5},{methodID,capacity:0},{methodID,capacity:257},{methodID,capacity:1.5}])assert.throws(()=>installFrozenReadTrace(input,host(()=>{})));const h=host(()=>{}),o=installFrozenReadTrace({methodID,capacity:256},h);assert.throws(()=>installFrozenReadTrace({methodID},h));const foreign=()=>{};h.fetch=foreign;assert.throws(()=>o.dispose(),/ownership lost/);assert.equal(h.fetch,foreign);});
test("request and response offsets remain distinct when backend answers wrong page",async()=>{const h=host(()=>Promise.resolve(response())),o=installFrozenReadTrace({methodID},h);await h.fetch("/wails/runtime",query(0));await tick();assert.equal(o.snapshot().records[0].offset,0);assert.equal(o.snapshot().records[0].responseOffset,50);o.dispose();});