import assert from "node:assert/strict";
import test from "node:test";
import {webcrypto}from "node:crypto";
import {installBitmapProbe,readPreviewCanvas}from "./stress.bitmap.mjs";
const tick=()=>new Promise(ok=>setImmediate(ok));
function host(mode="success"){
 class Bitmap{constructor(){this.width=1200;this.height=1;}close(){this.width=0;this.height=0;}}
 class Context{transferFromImageBitmap(bitmap){if(mode==="transfer-fail")throw Error("native transfer");bitmap.width=0;bitmap.height=0;}}
 let calls=0;const native=()=>{calls++;if(mode==="create-fail")return Promise.reject(Error("native decode"));return Promise.resolve(new Bitmap());};
 return{ImageBitmap:Bitmap,ImageBitmapRenderingContext:Context,Blob,createImageBitmap:native,calls:()=>calls};
}
test("native bitmap promise transfer close ownership is observed without replacing pixels",async()=>{const h=host(),native=h.createImageBitmap,close=h.ImageBitmap.prototype.close,transfer=h.ImageBitmapRenderingContext.prototype.transferFromImageBitmap,o=installBitmapProbe(h);const promise=h.createImageBitmap(new Blob(["png"],{type:"image/png"})),b=await promise;await tick();assert.equal(o.snapshot().decodedLive,1);new h.ImageBitmapRenderingContext().transferFromImageBitmap(b);b.close();b.close();const s=o.snapshot();assert.equal(s.created,1);assert.equal(s.transferred,1);assert.equal(s.closed,1);assert.equal(s.decodedLive,0);assert.deepEqual(s.records,[{width:1200,height:1,closed:true,transferred:true,detachedAfterTransfer:true}]);o.dispose();o.dispose();assert.equal(h.createImageBitmap,native);assert.equal(h.ImageBitmap.prototype.close,close);assert.equal(h.ImageBitmapRenderingContext.prototype.transferFromImageBitmap,transfer);assert.equal(h.__jackpotBitmapProbe,undefined);});
test("foreign nonPNG decode and foreign bitmap close remain unobserved",async()=>{const h=host(),o=installBitmapProbe(h);const b=await h.createImageBitmap(new Blob(["text"],{type:"text/plain"}));b.close();new h.ImageBitmap().close();await tick();assert.equal(o.snapshot().created,0);assert.equal(o.snapshot().closed,0);o.dispose();});
test("native decode rejection propagates unchanged without retry",async()=>{const h=host("create-fail"),o=installBitmapProbe(h);await assert.rejects(h.createImageBitmap(new Blob(["png"],{type:"image/png"})),/native decode/);await tick();assert.equal(h.calls(),1);assert.equal(o.snapshot().failures,1);assert.equal(o.snapshot().pending,0);o.dispose();});
test("native transfer failure stays failure and not transferred metric",async()=>{const h=host("transfer-fail"),o=installBitmapProbe(h);const b=await h.createImageBitmap(new Blob(["png"],{type:"image/png"}));assert.throws(()=>new h.ImageBitmapRenderingContext().transferFromImageBitmap(b),/native transfer/);assert.equal(o.snapshot().transferred,0);assert.equal(o.snapshot().decodedLive,1);b.close();assert.equal(o.snapshot().decodedLive,0);o.dispose();});
test("Scope dispose before late decode restores native surfaces and drops late records",async()=>{const h=host();let complete;h.createImageBitmap=()=>new Promise(ok=>{complete=ok;});const native=h.createImageBitmap,o=installBitmapProbe(h);const actual=h.createImageBitmap(new Blob(["png"],{type:"image/png"}));o.dispose();const b=new h.ImageBitmap();complete(b);assert.equal(await actual,b);await tick();assert.equal(o.snapshot().records.length,0);assert.equal(o.snapshot().created,0);assert.equal(o.snapshot().pending,0);assert.equal(h.createImageBitmap,native);b.close();});
test("weak primitive bitmap records remain bounded",async()=>{const h=host(),o=installBitmapProbe(h);for(let i=0;i<130;i++){const b=await h.createImageBitmap(new Blob(["png"],{type:"image/png"}));new h.ImageBitmapRenderingContext().transferFromImageBitmap(b);b.close();}await tick();assert.equal(o.snapshot().records.length,128);assert.equal(o.snapshot().created,130);assert.equal(o.snapshot().closed,130);o.dispose();});
function pixelHost(fail=""){let copy;return{crypto:webcrypto,OffscreenCanvas:class{constructor(width,height){this.width=width;this.height=height;copy=this;}getContext(){if(fail==="null")return null;return{drawImage:()=>{if(fail==="draw")throw Error("draw error");},getImageData:()=>({data:new Uint8ClampedArray(fail==="size"?4:4800).fill(255)})};}},copy:()=>copy};}
const canvas={tagName:"CANVAS",width:1200,height:1,hidden:false,isConnected:true};
test("actual displayed RGBA digest readback resets temporary software canvas",async()=>{const h=pixelHost(),pixels=await readPreviewCanvas(canvas,h);assert.equal(pixels.width,1200);assert.equal(pixels.height,1);assert.equal(pixels.rgbaBytes,4800);assert.equal(pixels.rgbaSHA256.length,64);assert.equal(h.copy().width,0);assert.equal(h.copy().height,0);});
for(const failure of ["null","draw","size"])test("pixel read failure remains failure with software surface reset "+failure,async()=>{const h=pixelHost(failure);await assert.rejects(readPreviewCanvas(canvas,h));assert.equal(h.copy().width,0);assert.equal(h.copy().height,0);});
test("hidden detached wrong tag and invalid bounds never count as displayed preview",async()=>{for(const change of [{hidden:true},{isConnected:false},{tagName:"IMG"},{width:1199},{height:0},{height:8193},{height:NaN}])await assert.rejects(readPreviewCanvas({...canvas,...change},pixelHost()),/visible bounded/);});
test("bitmap probe ownership conflicts fail loudly",()=>{const h=host(),o=installBitmapProbe(h);assert.throws(()=>installBitmapProbe(h));const foreign=()=>{};h.createImageBitmap=foreign;assert.throws(()=>o.dispose(),/ownership lost/);assert.equal(h.createImageBitmap,foreign);});