import { expect,it } from "@effect/vitest";
import { vi } from "vitest";
import { Deferred,Effect,Exit,Fiber,Scope } from "effect";
import { TestClock } from "effect/testing";
import { makeCollectionCache } from "../../src/operations/collectionCache";
import { makeProductCoordinator } from "../../src/operations/productCoordinator";
import { TransportError } from "../../src/contracts/backend";
import { backendHarness,bootstrap,collection,reply } from "../helpers/productBackend";
import { draft } from "../helpers/productCommands";
import type { Collection,ProductReply } from "../../src/contracts/product";

const data=(id:string,revision=2):Collection=>({...collection(),collectionId:id,revision});
function setup(){return Effect.gen(function*(){const port=backendHarness();const scope=yield*Scope.make();const owner=yield*makeProductCoordinator(port).pipe(Scope.provide(scope));yield*owner.acceptBootstrap(bootstrap());owner.setWritesBlocked(false);return{port,scope,owner};});}
it("empty cache and missed touch retain no entry or fabricated result",()=>{const cache=makeCollectionCache();expect(cache.size()).toBe(0);expect(cache.get("missing")).toBeUndefined();expect(cache.size()).toBe(0);cache.clear();expect(cache.size()).toBe(0);});
it("sixteen entries remain and seventeenth evicts exactly least recently used",()=>{const cache=makeCollectionCache();for(let i=1;i<=16;i++)expect(cache.remember(data("c"+i))).toBe(true);expect(cache.size()).toBe(16);expect(cache.get("c1")?.revision).toBe(2);cache.remember(data("c17"));expect(cache.size()).toBe(16);expect(cache.get("c2")).toBeUndefined();expect(cache.get("c1")?.revision).toBe(2);expect(cache.get("c17")?.revision).toBe(2);});
it("older revision cannot replace confirmed metadata or become LRU touch",()=>{const cache=makeCollectionCache();cache.remember(data("c1",3));for(let i=2;i<=16;i++)cache.remember(data("c"+i));expect(cache.remember(data("c1",2))).toBe(false);cache.remember(data("c17"));expect(cache.get("c1")).toBeUndefined();expect(cache.get("c2")?.revision).toBe(2);});
it("result reference seed raises revision floor and equal or old notice preserves known summary",()=>{const cache=makeCollectionCache();cache.remember(data("c",2));cache.seed({collectionId:"c",roundId:"r3",revision:3});expect(cache.get("c")).toEqual({collectionId:"c",revision:3,title:collection().article.title,galleryName:collection().article.galleryName,result:{collectionId:"c",roundId:"r3",revision:3}});cache.seed({collectionId:"c",roundId:"older",revision:2});cache.seed({collectionId:"c",roundId:"equal",revision:3});expect(cache.get("c")?.result?.roundId).toBe("r3");cache.seed({collectionId:"new",roundId:"r",revision:1});expect(cache.get("new")?.title).toBeNull();});
it("cache owns only readonly primitive summary and result reference without secret or entity arrays",()=>{const cache=makeCollectionCache();const raw={...data("c"),password:"SECRET",participants:[{body:"raw comments"}],comments:["PRIVATE"]};cache.remember(raw);const entry=cache.get("c")!;expect(Object.keys(entry).sort()).toEqual(["collectionId","galleryName","result","revision","title"]);expect(Object.isFrozen(entry)).toBe(true);expect(JSON.stringify(entry)).not.toMatch(/SECRET|PRIVATE|raw comments|unlocked|participants|comments/);raw.article={...raw.article,title:"mutated"};expect(entry.title).toBe(collection().article.title);cache.clear();expect(cache.size()).toBe(0);expect(cache.get("c")).toBeUndefined();});
it.effect("cache hit revalidates actual Go collection and confirms newer revision",()=>Effect.gen(function*(){const h=yield*setup();try{h.port.override("getCollection",Effect.succeed(reply(data("c"))),Effect.succeed(reply({...data("c"),revision:3})));expect((yield*h.owner.getCollection("c")).data.revision).toBe(2);expect((yield*h.owner.getCollection("c")).data.revision).toBe(3);expect(h.port.count("getCollection")).toBe(2);}finally{yield*Scope.close(h.scope,Exit.void);}}));
it.effect("concurrent older collection reply cannot overwrite higher confirmed revision",()=>Effect.gen(function*(){const h=yield*setup();const held=yield*Deferred.make<ProductReply<Collection>>();try{h.port.override("getCollection",Deferred.await(held),Effect.succeed(reply(data("c",3))));const old=yield*h.owner.getCollection("c").pipe(Effect.forkScoped);yield*h.port.wait("getCollection");expect((yield*h.owner.getCollection("c")).data.revision).toBe(3);yield*Deferred.succeed(held,reply(data("c",2)));const result=yield*Effect.result(Fiber.join(old));expect(result._tag).toBe("Failure");if(result._tag==="Failure")expect(result.failure._tag==="ProductUnavailable"&&result.failure.reason).toBe("stale");}finally{yield*Scope.close(h.scope,Exit.void);}}));
it.effect("LRU eviction makes removed revision query authoritative again while retained floor rejects stale",()=>Effect.gen(function*(){const h=yield*setup();try{for(let i=1;i<=16;i++){h.port.override("getCollection",Effect.succeed(reply(data("c"+i,3))));yield*h.owner.getCollection("c"+i);}h.port.override("getCollection",Effect.succeed(reply(data("c1",3))));yield*h.owner.getCollection("c1");h.port.override("getCollection",Effect.succeed(reply(data("c17",3))));yield*h.owner.getCollection("c17");h.port.override("getCollection",Effect.succeed(reply(data("c1",2))));expect((yield*Effect.result(h.owner.getCollection("c1")))._tag).toBe("Failure");h.port.override("getCollection",Effect.succeed(reply(data("c2",2))));expect((yield*h.owner.getCollection("c2")).data.revision).toBe(2);expect(h.port.count("getCollection")).toBe(20);}finally{yield*Scope.close(h.scope,Exit.void);}}));
it.effect("Bootstrap recent result raises existing floor and session replacement clears previous cache",()=>Effect.gen(function*(){const h=yield*setup();try{h.port.override("getCollection",Effect.succeed(reply(data("c",2))));yield*h.owner.getCollection("c");yield*h.owner.acceptBootstrap({...bootstrap(),data:{...bootstrap().data,recentResults:[{collectionId:"c",roundId:"r",revision:3}]}});h.port.override("getCollection",Effect.succeed(reply(data("c",2))));expect((yield*Effect.result(h.owner.getCollection("c")))._tag).toBe("Failure");const next=draft({summary:{...draft().summary,backendSessionId:"next",draftId:"next-draft"}});h.port.set(next);yield*h.owner.acceptBootstrap(bootstrap(next,"next"));h.port.override("getCollection",Effect.succeed(reply(data("c",1),"next")));expect((yield*h.owner.getCollection("c")).data.revision).toBe(1);}finally{yield*Scope.close(h.scope,Exit.void);}}));
it.effect("closing cache owner rejects further reads with zero additional IO",()=>Effect.gen(function*(){const h=yield*setup();yield*h.owner.getCollection("c");yield*Scope.close(h.scope,Exit.void);yield*Scope.close(h.scope,Exit.void);expect((yield*Effect.result(h.owner.getCollection("c")))._tag).toBe("Failure");expect(h.port.count("getCollection")).toBe(1);}));
it.effect("sixteen result cache eviction cannot evict unknown durable operation or permit duplicate mutation",()=>Effect.gen(function*(){const h=yield*setup();const request={collectionId:"collection",roundId:"r",expectedRevision:1,expectedVersion:1,prizes:[],message:"",mode:"immediate" as const,scheduledAt:null};try{h.port.override("rerun",Effect.fail(new TransportError()));const pending=yield*h.owner.collectionCommand("rerun",request).pipe(Effect.forkScoped);yield*h.port.wait("lookup",1);yield*TestClock.adjust(1000);yield*h.port.wait("lookup",2);yield*TestClock.adjust(2000);yield*h.port.wait("lookup",3);yield*TestClock.adjust(4000);expect((yield*Fiber.await(pending))._tag).toBe("Failure");for(let i=1;i<=17;i++)yield*h.owner.getCollection("c"+i);expect((yield*Effect.result(h.owner.collectionCommand("rerun",request)))._tag).toBe("Failure");expect(h.port.count("rerun")).toBe(1);yield*h.owner.recheck;expect(h.port.count("lookup")).toBe(5);}finally{yield*Scope.close(h.scope,Exit.void);}}));
it("cached latest result is an owned immutable reference without winner or round payload",()=>{const cache=makeCollectionCache();const latest={collectionId:"c",roundId:"r",number:1,attempt:1,state:"completed" as const,revision:2,roundVersion:2,mode:"immediate" as const,message:"SECRET MESSAGE",prizes:[],scheduledAt:null,executedAt:null,failureCode:null,winners:[],algorithmVersion:"v1",appVersion:"0.1"};cache.remember({...data("c",2),rounds:[latest],latestRound:latest});const entry=cache.get("c")!;expect(entry.result).toEqual({collectionId:"c",roundId:"r",revision:2});expect(Object.isFrozen(entry.result)).toBe(true);latest.roundId="changed";expect(entry.result?.roundId).toBe("r");expect(JSON.stringify(entry)).not.toMatch(/SECRET MESSAGE|winners|roundVersion/);});
it.effect("invalid null Bootstrap result references preserve current draft and cache without partial session change",()=>Effect.gen(function*(){const h=yield*setup();try{h.port.override("getCollection",Effect.succeed(reply(data("c",3))));yield*h.owner.getCollection("c");const invalid={...bootstrap(null,"foreign"),data:{...bootstrap().data,recentResults:null}};expect((yield*Effect.result(h.owner.acceptBootstrap(invalid)))._tag).toBe("Failure");expect((yield*h.owner.draft)?.summary.backendSessionId).toBe("session");h.port.override("getCollection",Effect.succeed(reply(data("c",2))));expect((yield*Effect.result(h.owner.getCollection("c")))._tag).toBe("Failure");}finally{yield*Scope.close(h.scope,Exit.void);}}));
it("nonempty LRU with a broken Map iterator raises a production invariant instead of silently exceeding capacity",()=>{const cache=makeCollectionCache();for(let i=0;i<16;i++)cache.remember(data("c"+i));const original=Map.prototype.keys;const broken=vi.spyOn(Map.prototype,"keys").mockImplementationOnce(()=>original.call(new Map()));try{expect(()=>cache.remember(data("c16"))).toThrow("Non-empty confirmed LRU has no oldest key");}finally{broken.mockRestore();}expect(cache.size()).toBe(16);expect(cache.get("c16")).toBeUndefined();expect(cache.get("c0")?.revision).toBe(2);cache.clear();expect(cache.size()).toBe(0);});