import { expect,it } from "@effect/vitest";
import { Deferred, Effect, Exit, Fiber, Scope, Stream } from "effect";
import { makeCreateWorkspace } from "../../src/screens/create/productOwner";
import { ClientIdError, ClientIds,clientIdsFrom } from "../../src/platform/ids";
import { ProtocolError } from "../../src/contracts/backend";
import { commandHarness,draft } from "../helpers/productCommands";

const ids=clientIdsFrom(()=> "new-prize");
function setup(value=draft()){return Effect.gen(function*(){const port=yield* commandHarness(value);const scope=yield* Scope.make();const workspace=yield* makeCreateWorkspace(port.commands,()=>{}).pipe(Scope.provide(scope),Effect.provideService(ClientIds,ids));return {port,scope,workspace};});}
it.effect("dirty raw persists until exact receipt confirmation; clean repeat sends no edit",()=>Effect.gen(function*(){const {workspace,port,scope}=yield* setup();try{workspace.input({_tag:"SingleCountChanged",raw:"2"});expect(workspace.read().editor?.single.count.dirty).toBe(true);yield* workspace.commitField({_tag:"singleCount"});expect(workspace.read().editor?.single.count.raw).toBe("2");expect(workspace.read().editor?.single.count.dirty).toBe(false);yield* workspace.commitField({_tag:"singleCount"});expect(port.state.edits).toHaveLength(1);}finally{yield* Scope.close(scope,Exit.void);yield* port.close;}}));
for(const raw of ["","0","11","1.5","-1","x"])it.effect("invalid active count "+JSON.stringify(raw)+" preserves raw and sends no mutation",()=>Effect.gen(function*(){const {workspace,port,scope}=yield* setup();try{workspace.input({_tag:"SingleCountChanged",raw});expect((yield* Effect.result(workspace.flush))._tag).toBe("Failure");expect(workspace.read().editor?.single.count.raw).toBe(raw);expect(workspace.read().editor?.single.count.dirty).toBe(true);expect(port.state.edits).toHaveLength(0);}finally{yield* Scope.close(scope,Exit.void);yield* port.close;}}));
it.effect("inactive invalid inputs survive mode switch without blocking active configuration",()=>Effect.gen(function*(){const {workspace,port,scope}=yield* setup();try{workspace.input({_tag:"SingleCountChanged",raw:"bad"});workspace.input({_tag:"PrizeModeChanged",raw:"multiple"});yield* workspace.commitField({_tag:"prizeMode"});expect(workspace.read().editor?.single.count.raw).toBe("bad");expect(workspace.read().editor?.single.count.dirty).toBe(true);expect(port.state.edits[0]?.prizes?.single.count).toBe(1);expect((yield* workspace.flush).afterSequence).toBe(1);}finally{yield* Scope.close(scope,Exit.void);yield* port.close;}}));
it.effect("manual include works at zero included while final creation remains invalid",()=>Effect.gen(function*(){const {workspace,port,scope}=yield* setup(draft({included:0,excluded:3}));try{yield* workspace.setUnclassified(true);expect(port.state.edits[0]?.kind).toBe("SetAllUnclassified");expect((yield* Effect.result(workspace.prepareCreation))._tag).toBe("Failure");expect(port.state.creates).toHaveLength(0);}finally{yield* Scope.close(scope,Exit.void);yield* port.close;}}));
it.effect("unregistered keyword buffer blocks finalization; literal registered keywords commit once",()=>Effect.gen(function*(){const {workspace,port,scope}=yield* setup();try{workspace.setKeywordRaw("include","  <script>  ");expect((yield* Effect.result(workspace.flush))._tag).toBe("Failure");yield* workspace.addKeyword("include");expect(workspace.read().keywordRaw.include).toBe("");expect(workspace.read().editor?.filters.includeKeywords.raw).toBe("<script>");expect(port.state.edits[0]?.filters?.includeKeywords).toEqual(["<script>"]);yield* workspace.addKeyword("include");expect(port.state.edits).toHaveLength(1);yield* workspace.removeKeyword("include","<script>");expect(workspace.read().editor?.filters.includeKeywords.raw).toBe("");}finally{yield* Scope.close(scope,Exit.void);yield* port.close;}}));
it.effect("stale field fence cannot admit newer raw",()=>Effect.gen(function*(){const {workspace,port,scope}=yield* setup();try{const editor=workspace.read().editor;if(editor===null)throw Error("editor absent");const fence={identity:editor.identity,editorEpoch:editor.editorEpoch,inputVersion:editor.single.count.inputVersion};workspace.input({_tag:"SingleCountChanged",raw:"2"});yield* workspace.commitField({_tag:"singleCount"},fence);expect(port.state.edits).toHaveLength(0);}finally{yield* Scope.close(scope,Exit.void);yield* port.close;}}));
it.effect("first transport failure keeps dirty raw and explicit retry succeeds",()=>Effect.gen(function*(){const {workspace,port,scope}=yield* setup();try{port.state.failEdit=1;workspace.input({_tag:"SingleCountChanged",raw:"2"});expect((yield* Effect.result(workspace.commitField({_tag:"singleCount"})))._tag).toBe("Failure");expect(workspace.read().editor?.single.count.dirty).toBe(true);yield* workspace.commitField({_tag:"singleCount"});expect(workspace.read().editor?.single.count.dirty).toBe(false);}finally{yield* Scope.close(scope,Exit.void);yield* port.close;}}));
it.effect("failed confirmation retains receipt without duplicate admission",()=>Effect.gen(function*(){const {workspace,port,scope}=yield* setup();try{port.state.failCommit=1;workspace.input({_tag:"SingleCountChanged",raw:"2"});expect((yield* Effect.result(workspace.commitField({_tag:"singleCount"})))._tag).toBe("Failure");expect((yield* Effect.result(workspace.commitField({_tag:"singleCount"})))._tag).toBe("Failure");expect(port.state.edits).toHaveLength(1);expect(workspace.read().editor?.single.count.submitted?.receipt.sequence).toBe(1);}finally{yield* Scope.close(scope,Exit.void);yield* port.close;}}));
it.effect("unknown finalization remains locked without automatic resend",()=>Effect.gen(function*(){const {workspace,port,scope}=yield* setup();try{port.state.unknown=true;const prepared=yield* workspace.prepareCreation;expect((yield* Effect.result(workspace.finalize(prepared)))._tag).toBe("Failure");expect(workspace.read().editor?.lock?.kind).toBe("finalization");expect(port.state.creates).toHaveLength(1);}finally{yield* Scope.close(scope,Exit.void);yield* port.close;}}));
it.effect("session replacement discards old raw",()=>Effect.gen(function*(){const {workspace,port,scope}=yield* setup();try{workspace.input({_tag:"SingleNameChanged",raw:"old"});port.emit(draft({summary:{...draft().summary,backendSessionId:"new-session"}}));yield* Stream.runHead(workspace.changes.pipe(Stream.filter((state)=>state.editor?.identity.backendSessionId==="new-session")));expect(workspace.read().editor?.single.name.raw).toBe("");}finally{yield* Scope.close(scope,Exit.void);yield* port.close;}}));
it.effect("app close ends retained stream and rejects future commands",()=>Effect.gen(function*(){const {workspace,port,scope}=yield* setup();const watcher=yield* Stream.runDrain(workspace.changes).pipe(Effect.forkScoped);yield* Scope.close(scope,Exit.void);yield* Fiber.join(watcher);expect(workspace.read().closed).toBe(true);expect(workspace.read().editor).toBeNull();expect((yield* Effect.result(workspace.load))._tag).toBe("Failure");expect(port.state.loads).toHaveLength(0);yield* port.close;}));
it.effect("native name count and immediate mode order survives final flush with exact prize name",()=>Effect.gen(function*(){const {workspace,port,scope}=yield* setup();try{workspace.input({_tag:"SingleNameChanged",raw:"E2E 상품"});workspace.input({_tag:"SingleCountChanged",raw:"1"});workspace.input({_tag:"DrawModeChanged",raw:"immediate"});yield* workspace.commitField({_tag:"drawMode"});const prepared=yield* workspace.prepareCreation;expect(port.state.edits[0]?.prizes?.single.name).toBe("E2E 상품");expect(workspace.read().editor?.single.name.raw).toBe("E2E 상품");expect(port.state.edits).toHaveLength(1);yield* workspace.finalize(prepared);expect(port.state.creates[0]?.afterSequence).toBe(1);}finally{yield* Scope.close(scope,Exit.void);yield* port.close;}}));

it.effect("public availability projection is idempotent preserves editor versions and is ignored after close",()=>Effect.gen(function*(){
 const{workspace,port,scope}=yield*setup();workspace.input({_tag:"SingleNameChanged",raw:"보존"});const before=workspace.read();workspace.setWritesBlocked(true);const blocked=workspace.read();
 expect(blocked.writesBlocked).toBe(true);expect(blocked.editor).toBe(before.editor);expect(blocked.version).toBe(before.version);workspace.setWritesBlocked(true);expect(workspace.read()).toBe(blocked);
 workspace.setWritesBlocked(false);expect(workspace.read().writesBlocked).toBe(false);expect(workspace.read().editor?.single.name.raw).toBe("보존");expect(port.state.edits).toHaveLength(0);
 yield*Scope.close(scope,Exit.void);const closed=workspace.read();workspace.setWritesBlocked(true);expect(workspace.read()).toBe(closed);expect(closed.closed).toBe(true);yield*port.close;
}));
it.effect("rapid prize additions with delayed IDs preserve input order and every accepted row",()=>Effect.gen(function*(){const port=yield*commandHarness(draft({participants:10,included:10,prizes:{...draft().prizes,mode:"multiple"}}));const scope=yield*Scope.make();const started=yield*Deferred.make<void>();const release=yield*Deferred.make<string>();let requested=0;const next=Effect.suspend(()=>++requested===1?Deferred.succeed(started,undefined).pipe(Effect.andThen(Deferred.await(release))):Effect.succeed("prize-"+requested));const workspace=yield*makeCreateWorkspace(port.commands,()=>{}).pipe(Scope.provide(scope),Effect.provideService(ClientIds,{operationId:next,intentId:next}));try{const first=yield*workspace.addPrize.pipe(Effect.forkScoped);yield*Deferred.await(started);const second=yield*workspace.addPrize.pipe(Effect.forkScoped);for(let turn=0;turn<20;turn++)yield*Effect.yieldNow;yield*Deferred.succeed(release,"prize-1");yield*Fiber.join(first);yield*Fiber.join(second);expect(workspace.read().editor?.multiple.map(item=>item.id)).toEqual(["many","prize-1","prize-2"]);expect(port.state.edits.at(-1)?.prizes?.multiple.map(item=>item.id)).toEqual(["many","prize-1","prize-2"]);}finally{yield*Scope.close(scope,Exit.void);yield*port.close;}}));
it.effect("delayed prize ID cannot append under a replacement session",()=>Effect.gen(function*(){const port=yield*commandHarness(draft({prizes:{...draft().prizes,mode:"multiple"}}));const scope=yield*Scope.make();const started=yield*Deferred.make<void>();const release=yield*Deferred.make<string>();const next=Deferred.succeed(started,undefined).pipe(Effect.andThen(Deferred.await(release)));const workspace=yield*makeCreateWorkspace(port.commands,()=>{}).pipe(Scope.provide(scope),Effect.provideService(ClientIds,{operationId:next,intentId:next}));try{const work=yield*workspace.addPrize.pipe(Effect.forkScoped);yield*Deferred.await(started);port.emit(draft({summary:{...draft().summary,backendSessionId:"new",draftId:"replacement"}}));yield*Stream.runHead(workspace.changes.pipe(Stream.filter(state=>state.editor?.identity.backendSessionId==="new")));yield*Deferred.succeed(release,"stale-prize");expect((yield*Fiber.await(work))._tag).toBe("Failure");expect(workspace.read().editor?.multiple.map(item=>item.id)).toEqual(["many"]);expect(port.state.edits).toHaveLength(0);}finally{yield*Scope.close(scope,Exit.void);yield*port.close;}}));
it.effect("ten accepted prize rows reject the eleventh without partial mutation",()=>Effect.gen(function*(){const port=yield*commandHarness(draft({participants:10,included:10,prizes:{...draft().prizes,mode:"multiple"}}));const scope=yield*Scope.make();let serial=0;const ids=clientIdsFrom(()=>"prize-"+(++serial));const workspace=yield*makeCreateWorkspace(port.commands,()=>{}).pipe(Scope.provide(scope),Effect.provideService(ClientIds,ids));try{for(let row=1;row<10;row++)yield*workspace.addPrize;expect(workspace.read().editor?.multiple).toHaveLength(10);expect(port.state.edits).toHaveLength(9);const names=workspace.read().editor?.multiple.map(item=>item.id);expect((yield*Effect.result(workspace.addPrize))._tag).toBe("Failure");expect(workspace.read().editor?.multiple.map(item=>item.id)).toEqual(names);expect(port.state.edits).toHaveLength(9);}finally{yield*Scope.close(scope,Exit.void);yield*port.close;}}));
for(const nth of [1,2,-1])it.effect("prize ID first Nth continuous failure "+nth+" releases ordering lock and never appends a failed row",()=>Effect.gen(function*(){const port=yield*commandHarness(draft({participants:10,included:10,prizes:{...draft().prizes,mode:"multiple"}}));const scope=yield*Scope.make();let calls=0;const next=Effect.suspend(()=>{calls++;return nth===-1||calls===nth?Effect.fail(new ClientIdError()):Effect.succeed("prize-"+calls);});const workspace=yield*makeCreateWorkspace(port.commands,()=>{}).pipe(Scope.provide(scope),Effect.provideService(ClientIds,{operationId:next,intentId:next}));try{const expected=["many"];for(let call=1;call<=3;call++){const result=yield*Effect.result(workspace.addPrize);if(nth===-1||call===nth)expect(result._tag).toBe("Failure");else{expect(result._tag).toBe("Success");expected.push("prize-"+call);}expect(workspace.read().editor?.multiple.map(item=>item.id)).toEqual(expected);expect(port.state.edits).toHaveLength(expected.length-1);expect(workspace.read().structuralPending).toBe(false);}}finally{yield*Scope.close(scope,Exit.void);yield*port.close;}}));
it.effect("app close cancels a pending prize ID and queued addition without restoring editor",()=>Effect.gen(function*(){const port=yield*commandHarness(draft());const scope=yield*Scope.make();const started=yield*Deferred.make<void>();const release=yield*Deferred.make<string>();let calls=0;const next=Effect.sync(()=>{calls++;}).pipe(Effect.andThen(Deferred.succeed(started,undefined)),Effect.andThen(Deferred.await(release)));const workspace=yield*makeCreateWorkspace(port.commands,()=>{}).pipe(Scope.provide(scope),Effect.provideService(ClientIds,{operationId:next,intentId:next}));const first=yield*workspace.addPrize.pipe(Effect.forkScoped);yield*Deferred.await(started);const second=yield*workspace.addPrize.pipe(Effect.forkScoped);yield*Scope.close(scope,Exit.void);expect((yield*Fiber.await(first))._tag).toBe("Failure");expect((yield*Fiber.await(second))._tag).toBe("Failure");yield*Deferred.succeed(release,"late");expect(workspace.read().closed).toBe(true);expect(workspace.read().structuralPending).toBe(false);expect(workspace.read().editor).toBeNull();expect(calls).toBe(1);expect(port.state.edits).toHaveLength(0);yield*port.close;}));
it.effect("structural pending owns both queued additions until each confirmation without an enabled gap",()=>Effect.gen(function*(){const port=yield*commandHarness(draft({participants:10,included:10,prizes:{...draft().prizes,mode:"multiple"}}));Object.assign(port.commands,{changes:Stream.empty});const scope=yield*Scope.make();let id=0;const workspace=yield*makeCreateWorkspace(port.commands,()=>{}).pipe(Scope.provide(scope),Effect.provideService(ClientIds,clientIdsFrom(()=>"extra-"+(++id))));const firstStarted=yield*Deferred.make<void>();const secondStarted=yield*Deferred.make<void>();const firstRelease=yield*Deferred.make<void>();const secondRelease=yield*Deferred.make<void>();const original=port.commands.commitThrough;let commit=0;Object.assign(port.commands,{commitThrough:(receipt:Parameters<typeof original>[0])=>Effect.suspend(()=>{const nth=++commit;return Deferred.succeed(nth===1?firstStarted:secondStarted,undefined).pipe(Effect.andThen(Deferred.await(nth===1?firstRelease:secondRelease)),Effect.andThen(original(receipt)));})});try{const first=yield*workspace.addPrize.pipe(Effect.forkScoped);yield*Deferred.await(firstStarted);expect(workspace.read().structuralPending).toBe(true);const observed=yield*Deferred.make<void>();const barrier=yield*Deferred.make<void>();const queued=yield*Deferred.make<void>();let watched=0;const flags:boolean[]=[];const watcher=yield*Stream.runForEach(workspace.changes,snapshot=>Effect.sync(()=>{flags.push(snapshot.structuralPending);if(++watched===2)Deferred.doneUnsafe(queued,Effect.void);if(snapshot.editor?.multiple.length===2)Deferred.doneUnsafe(observed,Effect.void);if(snapshot.editor?.single.name.raw==="pending-barrier")Deferred.doneUnsafe(barrier,Effect.void);})).pipe(Effect.forkScoped);yield*Deferred.await(observed);flags.length=0;const second=yield*workspace.addPrize.pipe(Effect.forkScoped);yield*Deferred.await(queued);yield*Deferred.succeed(firstRelease,undefined);yield*Deferred.await(secondStarted);yield*Fiber.join(first);workspace.input({_tag:"SingleNameChanged",raw:"pending-barrier"});yield*Deferred.await(barrier);expect(flags.every(flag=>flag)).toBe(true);expect(workspace.read().structuralPending).toBe(true);expect(workspace.read().editor?.multiple).toHaveLength(3);yield*Deferred.succeed(secondRelease,undefined);yield*Fiber.join(second);expect(workspace.read().structuralPending).toBe(false);expect(port.state.edits).toHaveLength(2);yield*Fiber.interrupt(watcher);}finally{yield*Scope.close(scope,Exit.void);yield*port.close;}}));
for(const action of["remove","mode"]as const)it.effect("structural "+action+" stays pending through confirmation and clears on typed failure",()=>Effect.gen(function*(){const initial=draft({prizes:{...draft().prizes,mode:"multiple",multiple:[{id:"many",name:"",count:1},{id:"remove",name:"",count:1}]}});const{workspace,port,scope}=yield*setup(initial);const started=yield*Deferred.make<void>();const failed=yield*Deferred.make<void>();const original=port.commands.commitThrough;Object.assign(port.commands,{commitThrough:(_receipt:Parameters<typeof original>[0])=>Deferred.succeed(started,undefined).pipe(Effect.andThen(Deferred.await(failed)),Effect.andThen(Effect.fail(new ProtocolError())))});try{if(action==="mode")workspace.input({_tag:"PrizeModeChanged",raw:"single"});const work=yield*(action==="remove"?workspace.removePrize("remove"):workspace.commitField({_tag:"prizeMode"})).pipe(Effect.forkScoped);yield*Deferred.await(started);expect(workspace.read().structuralPending).toBe(true);yield*Deferred.succeed(failed,undefined);expect((yield*Fiber.await(work))._tag).toBe("Failure");expect(workspace.read().structuralPending).toBe(false);expect(port.state.edits).toHaveLength(1);}finally{yield*Scope.close(scope,Exit.void);yield*port.close;}}));
it.effect("app close interrupts pending structural commit and publishes closed baseline without late acknowledgement",()=>Effect.gen(function*(){const{workspace,port,scope}=yield*setup(draft({prizes:{...draft().prizes,mode:"multiple"}}));const started=yield*Deferred.make<void>();const release=yield*Deferred.make<void>();const original=port.commands.commitThrough;Object.assign(port.commands,{commitThrough:(receipt:Parameters<typeof original>[0])=>Deferred.succeed(started,undefined).pipe(Effect.andThen(Deferred.await(release)),Effect.andThen(original(receipt)))});const work=yield*workspace.addPrize.pipe(Effect.forkScoped);yield*Deferred.await(started);expect(workspace.read().structuralPending).toBe(true);yield*Scope.close(scope,Exit.void);expect((yield*Fiber.await(work))._tag).toBe("Failure");expect(workspace.read().structuralPending).toBe(false);expect(workspace.read().closed).toBe(true);expect(workspace.read().editor).toBeNull();const closed=workspace.read();yield*Deferred.succeed(release,undefined);expect(workspace.read()).toBe(closed);expect(port.state.edits).toHaveLength(1);yield*port.close;}));for(const[flavor,text]of[["Korean",(length:number)=>"한".repeat(length)],["emoji",(length:number)=>"😀".repeat(Math.floor(length/2))+(length%2===0?"":"한")]]as const)for(const length of[19,20,21])it.effect("active prize "+flavor+" UTF16 boundary "+length+" preserves raw and admits only at most20",()=>Effect.gen(function*(){const{workspace,port,scope}=yield*setup();try{const name=text(length);expect(name.length).toBe(length);workspace.input({_tag:"SingleNameChanged",raw:name});const result=yield*Effect.result(workspace.commitField({_tag:"singleName"}));expect(result._tag).toBe(length<=20?"Success":"Failure");expect(workspace.read().editor?.single.name.raw).toBe(name);expect(port.state.edits).toHaveLength(length<=20?1:0);if(length<=20)expect(port.state.edits[0]?.prizes?.single.name).toBe(name);else expect(workspace.read().editor?.single.name.dirty).toBe(true);}finally{yield*Scope.close(scope,Exit.void);yield*port.close;}}));
it.effect("same prize name with distinct stable IDs survives actual configuration admission",()=>Effect.gen(function*(){const initial=draft({prizes:{...draft().prizes,mode:"multiple",multiple:[{id:"a",name:"동일😀",count:1},{id:"b",name:"동일😀",count:1}]}});const{workspace,port,scope}=yield*setup(initial);try{workspace.input({_tag:"MultipleNameChanged",prizeId:"a",raw:"동일😀"});yield*workspace.commitField({_tag:"multipleName",prizeId:"a"});expect(port.state.edits[0]?.prizes?.multiple).toEqual([{id:"a",name:"동일😀",count:1},{id:"b",name:"동일😀",count:1}]);expect(workspace.read().editor?.multiple.map(item=>item.id)).toEqual(["a","b"]);}finally{yield*Scope.close(scope,Exit.void);yield*port.close;}}));

for(const mode of ["immediate","reservation"] as const)it.effect("local creation "+mode+" flushes dirty prizes and finalizes exact fence without credentials",()=>Effect.gen(function*(){
 const {workspace,port,scope}=yield*setup();try{
  workspace.input({_tag:"SingleNameChanged",raw:"로컬 상품"});workspace.input({_tag:"SingleCountChanged",raw:"2"});workspace.input({_tag:"DrawModeChanged",raw:mode});
  const prepared=yield*workspace.prepareCreation;expect(workspace.read().editor?.lock?.kind).toBe("finalization");
  expect((yield*workspace.finalize(prepared)).collectionId).toBe("collection");
  expect(port.state.creates).toEqual([{afterSequence:1,mode}]);expect(port.state.edits.at(-1)?.prizes?.single.name).toBe("로컬 상품");expect(workspace.read().editor).toBeNull();
  expect((yield*Effect.result(workspace.finalize(prepared)))._tag).toBe("Failure");expect(port.state.creates).toHaveLength(1);
 }finally{yield*Scope.close(scope,Exit.void);yield*port.close;}
}));