import { expect,it } from "@effect/vitest";
import { Deferred,Effect,Fiber } from "effect";
import { TestClock } from "effect/testing";
import { readProductQuery } from "../../src/operations/productQueries";
import { BackendRejected,ProtocolError,TransportError } from "../../src/contracts/backend";

it.effect("success is returned without retry",()=>Effect.gen(function*(){let calls=0;expect(yield* readProductQuery(()=>Effect.sync(()=>++calls))).toBe(1);expect(calls).toBe(1);}));
for(const failure of [new ProtocolError(),new BackendRejected({code:"InvalidInput",messageKey:"InvalidInput"})])it.effect(failure._tag+" never retries",()=>Effect.gen(function*(){let calls=0;const task=yield* readProductQuery(()=>{calls++;return Effect.fail(failure);}).pipe(Effect.forkScoped);for(let i=0;i<10;i++)yield* Effect.yieldNow;expect(task.pollUnsafe()?._tag).toBe("Failure");expect(calls).toBe(1);}));
for(const at of [1,2,3])it.effect("transport first/Nth failure then success at attempt "+at,()=>Effect.gen(function*(){let calls=0;const started=Deferred.makeUnsafe<void>();const work=yield* readProductQuery(()=>{calls++;Deferred.doneUnsafe(started,Effect.void);return calls<at?Effect.fail(new TransportError()):Effect.succeed(calls);}).pipe(Effect.forkScoped);yield* Deferred.await(started);if(at>1)yield* TestClock.adjust(250);if(at>2)yield* TestClock.adjust(1000);for(let i=0;i<10;i++)yield* Effect.yieldNow;expect(calls).toBe(at);expect(work.pollUnsafe()).not.toBeUndefined();expect(yield* Fiber.join(work)).toBe(at);}));
it.effect("continuous transport failure stops at exactly three attempts",()=>Effect.gen(function*(){let calls=0;const started=Deferred.makeUnsafe<void>();const work=yield* readProductQuery(()=>{calls++;Deferred.doneUnsafe(started,Effect.void);return Effect.fail(new TransportError());}).pipe(Effect.forkScoped);yield* Deferred.await(started);yield* TestClock.adjust(250);yield* TestClock.adjust(1000);for(let i=0;i<10;i++)yield* Effect.yieldNow;expect(calls).toBe(3);expect(work.pollUnsafe()?._tag).toBe("Failure");expect((yield* Fiber.await(work))._tag).toBe("Failure");}));
it.effect("each fifteen-second timeout cancels dependency and bounded policy stops at three",()=>Effect.gen(function*(){let calls=0;let active=0;let cancelled=0;const started=Deferred.makeUnsafe<void>();const work=yield* readProductQuery(()=>Effect.callback((_resume)=>{calls++;active++;Deferred.doneUnsafe(started,Effect.void);return Effect.sync(()=>{active--;cancelled++;});})).pipe(Effect.forkScoped);yield* Deferred.await(started);expect(active).toBe(1);yield* TestClock.adjust(14999);expect(calls).toBe(1);expect([active,cancelled]).toEqual([1,0]);yield* TestClock.adjust(1);expect(active).toBe(0);yield* TestClock.adjust(250);expect(active).toBe(1);yield* TestClock.adjust(15000);yield* TestClock.adjust(1000);yield* TestClock.adjust(15000);expect((yield* Fiber.await(work))._tag).toBe("Failure");expect([calls,active,cancelled]).toEqual([3,0,3]);}));
it.effect("consumer cancellation cancels active request with no retry",()=>Effect.gen(function*(){let calls=0;let active=0;const started=Deferred.makeUnsafe<void>();const work=yield* readProductQuery(()=>Effect.callback((_resume)=>{calls++;active++;Deferred.doneUnsafe(started,Effect.void);return Effect.sync(()=>{active--;});})).pipe(Effect.forkScoped);yield* Deferred.await(started);yield* Fiber.interrupt(work);yield* TestClock.adjust(20000);expect([calls,active]).toEqual([1,0]);}));