import { expect,it } from "@effect/vitest";
import { Deferred, Effect, Exit, Fiber, Scope, Stream } from "effect";
import { TestClock } from "effect/testing";
import { BackendRejected,ProtocolError,TransportError } from "../../src/contracts/backend";
import type { Draft, DraftEditRequest, ProductReply } from "../../src/contracts/product";
import { makeProductCoordinator,ProductUnavailable,type DraftIntent } from "../../src/operations/productCoordinator";
import { ClientIdError } from "../../src/platform/ids";
import { backendHarness,bootstrap,collection,reply } from "../helpers/productBackend";
import { draft } from "../helpers/productCommands";

const intent=(kind:DraftIntent["kind"]="UpdateFilters"):DraftIntent=>({kind,filters:kind==="UpdateFilters"?draft().filters:null,prizes:kind==="SetPrizes"?draft().prizes:null,participantId:"p",included:true});
function setup(initial=draft()){return Effect.gen(function*(){const port=backendHarness(initial);const scope=yield* Scope.make();const owner=yield* makeProductCoordinator(port).pipe(Scope.provide(scope));yield* owner.acceptBootstrap(bootstrap(initial));owner.setWritesBlocked(false);return {port,scope,owner};});}
const reject=new BackendRejected({code:"InvalidInput",messageKey:"InvalidInput"});
const waitFailure=<A,E>(fiber:Fiber.Fiber<A,E>)=>Effect.gen(function*(){const exit=yield* Fiber.await(fiber);expect(exit._tag).toBe("Failure");return exit;});
it.effect("higher revision bootstrap refreshes same session to collection completion",()=>Effect.gen(function*(){const h=yield* setup(draft({summary:{...draft().summary,state:"loading"},load:{operationId:"load",sequence:1,pages:1,comments:1,state:"loading",failureCode:null}}));try{h.port.set(draft({summary:{...draft().summary,revision:2},load:{operationId:"load",sequence:2,pages:2,comments:3,state:"completed",failureCode:null}}));yield* h.owner.acceptBootstrap(bootstrap(h.port.current()));expect(h.port.count("getDraft")).toBe(2);expect((yield* h.owner.draft)?.load?.state).toBe("completed");yield* h.owner.acceptBootstrap(bootstrap(h.port.current()));expect(h.port.count("getDraft")).toBe(2);}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("session replacement fences older bootstrap and clears prior receipts",()=>Effect.gen(function*(){const h=yield* setup();try{const receipt=yield* h.owner.edit(intent());yield* h.owner.commitThrough(receipt);const fresh=draft({summary:{...draft().summary,backendSessionId:"new",draftId:"new-draft"}});h.port.set(fresh);yield* h.owner.acceptBootstrap(bootstrap(fresh,"new"));expect((yield* Effect.result(h.owner.commitThrough(receipt)))._tag).toBe("Failure");expect((yield* Effect.result(h.owner.acceptBootstrap(bootstrap())))._tag).toBe("Failure");const next=yield* h.owner.edit(intent());expect(next.sequence).toBe(1);expect(next.draftId).toBe("new-draft");yield* h.owner.commitThrough(next);}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("new article generation rejects queued old edits and starts a fresh fence",()=>Effect.gen(function*(){const h=yield* setup();try{const receipt=yield* h.owner.edit(intent());yield* h.owner.commitThrough(receipt);const changed=draft({summary:{...draft().summary,revision:2,articleGeneration:2}});h.port.set(changed);yield* h.owner.acceptBootstrap(bootstrap(changed));expect((yield* Effect.result(h.owner.commitThrough(receipt)))._tag).toBe("Failure");const next=yield* h.owner.edit(intent());expect(next.sequence).toBe(1);expect(next.articleGeneration).toBe(2);yield* h.owner.commitThrough(next);}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("load API does not hold admission lock; cancellation bypasses global write block",()=>Effect.gen(function*(){const h=yield* setup();const pending=yield* Deferred.make<ProductReply<Draft>>();try{h.port.override("loadArticle",Deferred.await(pending));const load=yield* h.owner.loadArticle("url").pipe(Effect.forkScoped);yield* h.port.wait("loadArticle");h.owner.setWritesBlocked(true);yield* h.owner.cancelLoad;expect(h.port.count("editDraft")).toBe(1);expect((h.port.calls.get("editDraft")?.[0] as DraftEditRequest).kind).toBe("CancelLoad");yield* Deferred.succeed(pending,reply(h.port.current()));yield* Fiber.join(load);}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("create API seal rejects second finalization immediately without waiting first API",()=>Effect.gen(function*(){const h=yield* setup();const pending=yield* Deferred.make<ProductReply<ReturnType<typeof collection>>>();try{h.port.override("createCollection",Deferred.await(pending));const first=yield* h.owner.createCollection(0,"immediate").pipe(Effect.forkScoped);yield* h.port.wait("createCollection");const second=yield* Effect.result(h.owner.createCollection(0,"immediate"));expect(second._tag).toBe("Failure");expect(h.port.count("createCollection")).toBe(1);yield* Deferred.succeed(pending,reply(collection()));expect((yield* Fiber.join(first)).collectionId).toBe("collection");}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("known finalization rejection unseals only after actual draft read confirms not finalized",()=>Effect.gen(function*(){const h=yield* setup();try{h.port.override("createCollection",Effect.fail(reject));expect((yield* Effect.result(h.owner.createCollection(0,"immediate")))._tag).toBe("Failure");const receipt=yield* h.owner.edit(intent());yield* h.owner.commitThrough(receipt);expect(h.port.count("getDraft")).toBe(2);}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("finalization id failure restores admission without dispatching creation",()=>Effect.gen(function*(){const port=backendHarness();const scope=yield* Scope.make();const owner=yield* makeProductCoordinator({...port,newId:Effect.fail(new ClientIdError())}).pipe(Scope.provide(scope));try{yield* owner.acceptBootstrap(bootstrap());owner.setWritesBlocked(false);expect((yield* Effect.result(owner.createCollection(0,"immediate")))._tag).toBe("Failure");expect(port.count("createCollection")).toBe(0);expect((yield* Effect.result(owner.loadArticle("url")))._tag).toBe("Failure");}finally{yield* Scope.close(scope,Exit.void);}}));
it.effect("collection reservation before delayed newId rejects concurrent duplicate execution",()=>Effect.gen(function*(){const port=backendHarness();const next=yield* Deferred.make<string>();const scope=yield* Scope.make();const owner=yield* makeProductCoordinator({...port,newId:Deferred.await(next)}).pipe(Scope.provide(scope));const request={collectionId:"collection",roundId:"round",expectedRevision:1,expectedVersion:1,prizes:[],message:"",mode:"immediate" as const,scheduledAt:null};try{yield* owner.acceptBootstrap(bootstrap());owner.setWritesBlocked(false);const first=yield* owner.collectionCommand("rerun",request).pipe(Effect.forkScoped);for(let i=0;i<10;i++)yield* Effect.yieldNow;expect((yield* Effect.result(owner.collectionCommand("rerun",request)))._tag).toBe("Failure");yield* Deferred.succeed(next,"id");yield* Fiber.join(first);expect(port.count("rerun")).toBe(1);}finally{yield* Scope.close(scope,Exit.void);}}));
it.effect("bounded load outcome polling leaves unknown and manual recheck reads operation exactly once",()=>Effect.gen(function*(){const h=yield* setup();try{h.port.override("loadArticle",Effect.fail(new TransportError()));const pending=yield* h.owner.loadArticle("url").pipe(Effect.forkScoped);yield* h.port.wait("getDraftOperation",1);yield* TestClock.adjust(1000);yield* h.port.wait("getDraftOperation",2);yield* TestClock.adjust(2000);yield* h.port.wait("getDraftOperation",3);yield* TestClock.adjust(4000);yield* h.port.wait("getDraftOperation",4);yield* waitFailure(pending);expect((yield* Effect.result(h.owner.edit(intent())))._tag).toBe("Failure");yield* h.owner.recheck;expect(h.port.count("getDraftOperation")).toBe(5);expect(h.port.count("loadArticle")).toBe(1);expect((yield* Effect.result(h.owner.createCollection(0,"immediate")))._tag).toBe("Failure");}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("lost CreateDraft response recovers same operation without new id",()=>Effect.gen(function*(){const port=backendHarness();const scope=yield* Scope.make();const owner=yield* makeProductCoordinator(port).pipe(Scope.provide(scope));try{yield* owner.acceptBootstrap(bootstrap(null));owner.setWritesBlocked(false);port.override("createDraft",Effect.fail(new TransportError()));port.override("getDraftOperation",Effect.succeed(reply({operationId:"operation-1",state:"succeeded",summary:draft().summary,failureCode:null})));expect((yield* owner.ensureDraft).summary.draftId).toBe("draft");expect(port.count("createDraft")).toBe(1);expect(port.count("getDraftOperation")).toBe(1);expect((yield* owner.ensureDraft).summary.draftId).toBe("draft");expect(port.count("createDraft")).toBe(1);}finally{yield* Scope.close(scope,Exit.void);}}));
it.effect("edit unknown completes barrier with failure then single manual confirmation repairs exact receipt",()=>Effect.gen(function*(){const h=yield* setup();try{h.port.override("editDraft",Effect.fail(new ProtocolError()));const receipt=yield* h.owner.edit(intent());const barrier=yield* h.owner.commitThrough(receipt).pipe(Effect.forkScoped);yield* h.port.wait("getDraftOperation",1);yield* TestClock.adjust(1000);yield* h.port.wait("getDraftOperation",2);yield* TestClock.adjust(2000);yield* h.port.wait("getDraftOperation",3);yield* TestClock.adjust(4000);yield* h.port.wait("getDraftOperation",4);yield* waitFailure(barrier);h.port.override("getDraftOperation",Effect.succeed(reply({operationId:receipt.intentId,state:"succeeded",summary:draft().summary,failureCode:null})));yield* h.owner.recheck;yield* h.owner.commitThrough(receipt);expect(h.port.count("editDraft")).toBe(1);expect(h.port.count("getDraftOperation")).toBe(5);}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("closed coordinator terminates retained draft stream and rejects read/mutation without IO",()=>Effect.gen(function*(){const h=yield* setup();const watcher=yield* Stream.runDrain(h.owner.changes).pipe(Effect.forkScoped);yield* Scope.close(h.scope,Exit.void);for(let i=0;i<10;i++)yield* Effect.yieldNow;expect(watcher.pollUnsafe()).not.toBeUndefined();yield* Fiber.join(watcher);expect(yield* h.owner.draft).toBeNull();expect((yield* Effect.result(h.owner.getCollection("collection")))._tag).toBe("Failure");expect((yield* Effect.result(h.owner.edit(intent())))._tag).toBe("Failure");expect(h.port.count("getCollection")).toBe(0);}));
it.effect("empty draft accepts configuration before article collection",()=>Effect.gen(function*(){const h=yield* setup(draft({summary:{...draft().summary,state:"empty"},article:null,participants:0,included:0}));try{const receipt=yield* h.owner.edit(intent("SetPrizes"));yield* h.owner.commitThrough(receipt);expect(h.port.count("editDraft")).toBe(1);expect((yield* Effect.result(h.owner.createCollection(receipt.sequence,"immediate")))._tag).toBe("Failure");}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("confirmed finalized draft starts new real draft with fresh receipt sequence",()=>Effect.gen(function*(){const finalized=draft({summary:{...draft().summary,state:"finalized",collectionId:"collection"}});const h=yield* setup(finalized);try{const fresh=draft({summary:{...draft().summary,draftId:"fresh",state:"empty"},article:null});h.port.override("createDraft",Effect.succeed(reply(fresh)));expect((yield* h.owner.ensureDraft).summary.draftId).toBe("fresh");expect(h.port.count("createDraft")).toBe(1);expect((yield* h.owner.edit(intent())).sequence).toBe(1);}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("same-session new draft rejects previously waiting barrier instead of aliasing reused sequence",()=>Effect.gen(function*(){const h=yield* setup();const held=yield* Deferred.make<ProductReply<Draft>>();try{h.port.override("editDraft",Deferred.await(held));const receipt=yield* h.owner.edit(intent());yield* h.port.wait("editDraft");const barrier=yield* h.owner.commitThrough(receipt).pipe(Effect.forkScoped);const fresh=draft({summary:{...draft().summary,draftId:"fresh"}});h.port.set(fresh);yield* h.owner.acceptBootstrap(bootstrap(fresh));yield* waitFailure(barrier);const next=yield* h.owner.edit(intent());expect(next.sequence).toBe(1);yield* h.owner.commitThrough(next);yield* Deferred.succeed(held,reply(draft()));for(let i=0;i<20;i++)yield* Effect.yieldNow;expect((yield* h.owner.draft)?.summary.draftId).toBe("fresh");}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("queue 31 and 32 are admitted while 33 is rejected without losing any receipt",()=>Effect.gen(function*(){const h=yield* setup();const held=yield* Deferred.make<ProductReply<Draft>>();try{h.port.override("editDraft",Deferred.await(held));const receipts=[];receipts.push(yield* h.owner.edit(intent("ToggleParticipant")));yield* h.port.wait("editDraft");for(let i=1;i<32;i++)receipts.push(yield* h.owner.edit(intent("ToggleParticipant")));expect(receipts).toHaveLength(32);expect((yield* Effect.result(h.owner.edit(intent("ToggleParticipant"))))._tag).toBe("Failure");expect(h.port.count("editDraft")).toBe(1);yield* Deferred.succeed(held,reply(draft()));yield* h.owner.commitThrough(receipts[31] as typeof receipts[number]);expect(h.port.count("editDraft")).toBe(32);}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("same-field queued tail coalesces but another field and active barrier preserve ordering",()=>Effect.gen(function*(){const h=yield* setup();const held=yield* Deferred.make<ProductReply<Draft>>();try{h.port.override("editDraft",Deferred.await(held));const first=yield* h.owner.edit(intent(),"first");yield* h.port.wait("editDraft");const tail=yield* h.owner.edit(intent(),"same");const replacement=yield* h.owner.edit(intent(),"same");const other=yield* h.owner.edit(intent(),"other");const barrier=yield* h.owner.commitThrough(other).pipe(Effect.forkScoped);for(let i=0;i<5;i++)yield* Effect.yieldNow;const last=yield* h.owner.edit(intent(),"other");yield* Deferred.succeed(held,reply(draft()));yield* Fiber.join(barrier);yield* h.owner.commitThrough(tail);yield* h.owner.commitThrough(last);expect(h.port.count("editDraft")).toBe(4);expect(replacement.sequence).toBe(3);}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("barrier registrations 64 are bounded and identical receipt callers count separately",()=>Effect.gen(function*(){const h=yield* setup();const held=yield* Deferred.make<ProductReply<Draft>>();try{h.port.override("editDraft",Deferred.await(held));const receipt=yield* h.owner.edit(intent());yield* h.port.wait("editDraft");const waiting=[];for(let i=0;i<64;i++){waiting.push(yield* h.owner.commitThrough(receipt).pipe(Effect.forkScoped));yield* Effect.yieldNow;}const overflow=yield* h.owner.commitThrough(receipt).pipe(Effect.forkScoped);for(let i=0;i<10;i++)yield* Effect.yieldNow;expect(overflow.pollUnsafe()?._tag).toBe("Failure");yield* Deferred.succeed(held,reply(draft()));for(const fiber of waiting)yield* Fiber.join(fiber);}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("participant reply context uses field equality rather than JSON property order",()=>Effect.gen(function*(){const h=yield* setup();try{const request={backendSessionId:"session",draftId:"draft",revision:1,articleGeneration:1,query:"",group:"included",offset:0,limit:100};h.port.override("queryParticipants",Effect.succeed(reply({context:{articleGeneration:1,revision:1,draftId:"draft",backendSessionId:"session"},total:0,matched:0,offset:0,rows:[]})));expect((yield* h.owner.queryParticipants(request)).data.rows).toEqual([]);}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("read reply cannot overwrite a changed draft revision",()=>Effect.gen(function*(){const h=yield* setup();const held=yield* Deferred.make<unknown>();try{const request={backendSessionId:"session",draftId:"draft",revision:1,articleGeneration:1,query:"",group:"included",offset:0,limit:100};h.port.override("queryParticipants",Deferred.await(held));const query=yield* h.owner.queryParticipants(request).pipe(Effect.forkScoped);yield* h.port.wait("queryParticipants");const newer=draft({summary:{...draft().summary,revision:2}});h.port.set(newer);yield* h.owner.acceptBootstrap(bootstrap(newer));yield* Deferred.succeed(held,reply({context:request,total:0,matched:0,offset:0,rows:[]}));yield* waitFailure(query);expect((yield* h.owner.draft)?.summary.revision).toBe(2);}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("route read cancellation and app close both cancel actual query resource",()=>Effect.gen(function*(){const h=yield* setup();let active=0;const acquired=yield* Deferred.make<void>();const secondAcquired=yield* Deferred.make<void>();const request={backendSessionId:"session",draftId:"draft",revision:1,articleGeneration:1,query:"",group:"included",offset:0,limit:100};h.port.override("queryParticipants",Effect.callback(()=>{active++;Deferred.doneUnsafe(acquired,Effect.void);return Effect.sync(()=>{active--;});}));const query=yield* h.owner.queryParticipants(request).pipe(Effect.forkScoped);yield* h.port.wait("queryParticipants");yield* Deferred.await(acquired);expect(active).toBe(1);yield* Fiber.interrupt(query);expect(active).toBe(0);h.port.override("queryParticipants",Effect.callback(()=>{active++;Deferred.doneUnsafe(secondAcquired,Effect.void);return Effect.sync(()=>{active--;});}));const second=yield* h.owner.queryParticipants(request).pipe(Effect.forkScoped);yield* h.port.wait("queryParticipants",2);yield* Deferred.await(secondAcquired);yield* Scope.close(h.scope,Exit.void);expect(active).toBe(0);yield* waitFailure(second);}));
it.effect("route mutation consumer cancellation preserves admitted app work",()=>Effect.gen(function*(){const h=yield* setup();const held=yield* Deferred.make<ProductReply<Draft>>();try{h.port.override("loadArticle",Deferred.await(held));const consumer=yield* h.owner.loadArticle("url").pipe(Effect.forkScoped);yield* h.port.wait("loadArticle");yield* Fiber.interrupt(consumer);const newer=draft({summary:{...draft().summary,revision:2}});yield* Deferred.succeed(held,reply(newer));yield* Stream.runHead(h.owner.changes.pipe(Stream.filter((value)=>value?.summary.revision===2)));expect(h.port.count("loadArticle")).toBe(1);}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("global 63 and 64 slots permit actual distinct collection flights; 65 is rejected",()=>Effect.gen(function*(){const h=yield* setup();const held=yield* Deferred.make<unknown>();try{h.port.override("rerun",...Array.from({length:64},()=>Deferred.await(held)));const flights=[];for(let i=0;i<64;i++){flights.push(yield* h.owner.collectionCommand("rerun",{collectionId:"collection-"+i,roundId:"round",expectedRevision:1,expectedVersion:1,prizes:[],message:"",mode:"immediate",scheduledAt:null}).pipe(Effect.forkScoped));yield* h.port.wait("rerun",i+1);}expect(h.port.count("rerun")).toBe(64);expect((yield* Effect.result(h.owner.collectionCommand("rerun",{collectionId:"collection-65",roundId:"round",expectedRevision:1,expectedVersion:1,prizes:[],message:"",mode:"immediate",scheduledAt:null})))._tag).toBe("Failure");expect((yield* Effect.result(h.owner.createCollection(0,"immediate")))._tag).toBe("Failure");expect(h.port.count("createCollection")).toBe(0);}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("explicit fresh edit after known rejection creates a new fence; rejected receipt never becomes successful",()=>Effect.gen(function*(){const h=yield* setup();try{h.port.override("editDraft",Effect.fail(reject));const rejected=yield* h.owner.edit(intent());expect((yield* Effect.result(h.owner.commitThrough(rejected)))._tag).toBe("Failure");const fresh=yield* h.owner.edit(intent());expect(fresh.sequence).toBe(1);yield* h.owner.commitThrough(fresh);expect((yield* Effect.result(h.owner.commitThrough(rejected)))._tag).toBe("Failure");expect(h.port.count("editDraft")).toBe(2);}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("terminal 127 128 129 eviction expires old receipt while latest barrier and finalization stay valid",()=>Effect.gen(function*(){const h=yield* setup();try{let oldest;let newest;for(let i=0;i<129;i++){const receipt=yield* h.owner.edit(intent());if(i===0)oldest=receipt;newest=receipt;yield* h.owner.commitThrough(receipt);}if(oldest===undefined||newest===undefined)throw Error("loop invariant");expect((yield* Effect.result(h.owner.commitThrough(oldest)))._tag).toBe("Failure");yield* h.owner.commitThrough(newest);expect((yield* h.owner.createCollection(newest.sequence,"immediate")).collectionId).toBe("collection");}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("long superseded chain remains bounded and complete prefix permits the latest finalization",()=>Effect.gen(function*(){const h=yield* setup();const held=yield* Deferred.make<ProductReply<Draft>>();try{h.port.override("editDraft",Deferred.await(held));yield* h.owner.edit(intent(),"head");yield* h.port.wait("editDraft");let last;for(let i=1;i<160;i++)last=yield* h.owner.edit(intent(),"tail");expect((yield* Effect.result(h.owner.edit(intent(),"tail")))._tag).toBe("Failure");if(last===undefined)throw Error("loop invariant");const barrier=yield* h.owner.commitThrough(last).pipe(Effect.forkScoped);yield* Deferred.succeed(held,reply(draft()));yield* Fiber.join(barrier);expect(h.port.count("editDraft")).toBe(2);expect((yield* h.owner.createCollection(last.sequence,"immediate")).collectionId).toBe("collection");}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("durable lost response confirms actual operation once and never resends initial draw",()=>Effect.gen(function*(){const h=yield* setup();try{h.port.override("createCollection",Effect.fail(new ProtocolError()));h.port.override("lookup",Effect.succeed(reply({operationId:"operation-1",state:"succeeded",kind:"CreateCollection",collectionId:"collection",roundId:"round",revision:1,failureCode:null})));expect((yield* h.owner.createCollection(0,"immediate")).collectionId).toBe("collection");expect(h.port.count("createCollection")).toBe(1);expect(h.port.count("lookup")).toBe(1);expect(h.port.count("getCollection")).toBe(1);}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("durable unknown retains seal and manual recheck uses one lookup",()=>Effect.gen(function*(){const h=yield* setup();try{h.port.override("createCollection",Effect.fail(new TransportError()));const pending=yield* h.owner.createCollection(0,"immediate").pipe(Effect.forkScoped);yield* h.port.wait("lookup",1);yield* TestClock.adjust(1000);yield* h.port.wait("lookup",2);yield* TestClock.adjust(2000);yield* h.port.wait("lookup",3);yield* TestClock.adjust(4000);yield* h.port.wait("lookup",4);yield* waitFailure(pending);expect((yield* Effect.result(h.owner.edit(intent())))._tag).toBe("Failure");yield* h.owner.recheck;expect(h.port.count("lookup")).toBe(5);expect(h.port.count("createCollection")).toBe(1);}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("manual recheck is single flight when overlapping callbacks wait on actual observation",()=>Effect.gen(function*(){const h=yield* setup();try{h.port.override("loadArticle",Effect.fail(new TransportError()));const load=yield* h.owner.loadArticle("url").pipe(Effect.forkScoped);yield* h.port.wait("getDraftOperation",1);yield* TestClock.adjust(1000);yield* h.port.wait("getDraftOperation",2);yield* TestClock.adjust(2000);yield* h.port.wait("getDraftOperation",3);yield* TestClock.adjust(4000);yield* h.port.wait("getDraftOperation",4);yield* waitFailure(load);const held=yield* Deferred.make<unknown>();h.port.override("getDraftOperation",Deferred.await(held));const first=yield* h.owner.recheck.pipe(Effect.forkScoped);yield* h.port.wait("getDraftOperation",5);const second=yield* h.owner.recheck.pipe(Effect.forkScoped);for(let i=0;i<10;i++)yield* Effect.yieldNow;expect(h.port.count("getDraftOperation")).toBe(5);yield* Deferred.succeed(held,reply({operationId:"operation-1",state:"unknown",summary:null,failureCode:null}));yield* Fiber.join(first);yield* Fiber.join(second);expect(h.port.count("getDraftOperation")).toBe(5);}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("mutation thirty-second timeout cancels transport and same operation alone is recovered",()=>Effect.gen(function*(){const h=yield* setup();let active=0;let cancelled=0;const acquired=yield* Deferred.make<void>();try{h.port.override("loadArticle",Effect.callback(()=>{active++;Deferred.doneUnsafe(acquired,Effect.void);return Effect.sync(()=>{active--;cancelled++;});}));h.port.override("getDraftOperation",Effect.succeed(reply({operationId:"operation-1",state:"succeeded",summary:draft().summary,failureCode:null})));const load=yield* h.owner.loadArticle("url").pipe(Effect.forkScoped);yield* Deferred.await(acquired);yield* TestClock.adjust(29999);expect(h.port.count("getDraftOperation")).toBe(0);expect(active).toBe(1);yield* TestClock.adjust(1);yield* Fiber.join(load);expect([active,cancelled,h.port.count("loadArticle"),h.port.count("getDraftOperation")]).toEqual([0,1,1,1]);}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("write gate allows real reads and cancel but rejects every new mutation",()=>Effect.gen(function*(){const h=yield* setup();try{h.owner.setWritesBlocked(true);expect((yield* h.owner.getCollection("collection")).data.collectionId).toBe("collection");expect((yield* Effect.result(h.owner.loadArticle("url")))._tag).toBe("Failure");expect((yield* Effect.result(h.owner.edit(intent())))._tag).toBe("Failure");expect((yield* Effect.result(h.owner.createCollection(0,"immediate")))._tag).toBe("Failure");yield* h.owner.cancelLoad;expect(h.port.count("editDraft")).toBe(1);}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("admitted configuration owns keyword/prize arrays independently from caller mutation",()=>Effect.gen(function*(){const h=yield* setup();const held=yield* Deferred.make<ProductReply<Draft>>();try{h.port.override("editDraft",Deferred.await(held));yield* h.owner.edit(intent("ToggleParticipant"));yield* h.port.wait("editDraft");const include=["original"];const items=[{id:"item",name:"원본",count:1}];const receipt=yield* h.owner.edit({kind:"UpdateFilters",filters:{...draft().filters,includeKeywords:include},prizes:null,participantId:"",included:null});include[0]="changed";const prize=yield* h.owner.edit({kind:"SetPrizes",filters:null,prizes:{...draft().prizes,multiple:items},participantId:"",included:null});items[0]!.name="변경";yield* Deferred.succeed(held,reply(draft()));yield* h.owner.commitThrough(prize);const requests=h.port.calls.get("editDraft") as DraftEditRequest[];expect(requests[1]?.filters?.includeKeywords).toEqual(["original"]);expect(requests[2]?.prizes?.multiple[0]?.name).toBe("원본");}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("wrong operation id and failed observation never pretend a lost mutation succeeded",()=>Effect.gen(function*(){const h=yield* setup();try{h.port.override("loadArticle",Effect.fail(new TransportError()));h.port.override("getDraftOperation",Effect.succeed(reply({operationId:"wrong",state:"succeeded",summary:draft().summary,failureCode:null})),Effect.succeed(reply({operationId:"operation-1",state:"failed",summary:draft().summary,failureCode:"InvalidInput"})));const load=yield* h.owner.loadArticle("url").pipe(Effect.forkScoped);yield* h.port.wait("getDraftOperation",1);yield* TestClock.adjust(1000);yield* waitFailure(load);expect(h.port.count("getDraftOperation")).toBe(2);expect(h.port.count("loadArticle")).toBe(1);expect((yield* h.owner.edit(intent())).sequence).toBe(1);}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("wrong durable operation identity is ignored and typed terminal failure is preserved",()=>Effect.gen(function*(){const h=yield* setup();try{h.port.override("createCollection",Effect.fail(new TransportError()));h.port.override("lookup",Effect.succeed(reply({operationId:"wrong",state:"succeeded",kind:"CreateCollection",collectionId:"collection",roundId:"round",revision:1,failureCode:null})),Effect.succeed(reply({operationId:"operation-1",state:"failed",kind:"CreateCollection",collectionId:"collection",roundId:"round",revision:1,failureCode:"StorageUnavailable"})));const create=yield* h.owner.createCollection(0,"immediate").pipe(Effect.forkScoped);yield* h.port.wait("lookup",1);yield* TestClock.adjust(1000);yield* waitFailure(create);expect(h.port.count("getCollection")).toBe(0);expect(h.port.count("lookup")).toBe(2);}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("latest sequence is mandatory for finalization and success keeps sealed admission",()=>Effect.gen(function*(){const h=yield* setup();try{const receipt=yield* h.owner.edit(intent());yield* h.owner.commitThrough(receipt);expect((yield* Effect.result(h.owner.createCollection(0,"immediate")))._tag).toBe("Failure");expect(h.port.count("createCollection")).toBe(0);yield* h.owner.createCollection(receipt.sequence,"immediate");expect((yield* Effect.result(h.owner.edit(intent())))._tag).toBe("Failure");}finally{yield* Scope.close(h.scope,Exit.void);}}));
for(const expectedRevision of [undefined,null,1])it.effect("frozen pages accept optional revision "+expectedRevision+" and preserve actual limit/offset",()=>Effect.gen(function*(){const h=yield* setup();try{const request={collectionId:"collection",query:"",group:"included",offset:100,limit:100,...(expectedRevision===undefined?{}:{expectedRevision})};const page=yield* h.owner.queryFrozenParticipants(request);expect(page.data.offset).toBe(100);const comments=yield* h.owner.queryFrozenComments({collectionId:"collection",participantId:"participant",offset:50,limit:50,...(expectedRevision===undefined?{}:{expectedRevision})});expect(comments.data.participantId).toBe("participant");}finally{yield* Scope.close(h.scope,Exit.void);}}));
for(const invalid of ["collection","participant","revision"])it.effect("frozen "+invalid+" fence rejects mismatched actual response",()=>Effect.gen(function*(){const h=yield* setup();try{h.port.override("queryFrozenComments",Effect.succeed(reply({collectionId:invalid==="collection"?"wrong":"collection",participantId:invalid==="participant"?"wrong":"participant",revision:invalid==="revision"?2:1,total:0,offset:0,rows:[]})));expect((yield* Effect.result(h.owner.queryFrozenComments({collectionId:"collection",participantId:"participant",expectedRevision:1,offset:0,limit:50})))._tag).toBe("Failure");expect(h.port.count("queryFrozenComments")).toBe(1);}finally{yield* Scope.close(h.scope,Exit.void);}}));

for(const [name,run] of [
 ["ensure",(owner:import("../../src/operations/productCoordinator").ProductCoordinator)=>owner.ensureDraft],
 ["refresh",(owner:import("../../src/operations/productCoordinator").ProductCoordinator)=>owner.refreshDraft],
 ["load",(owner:import("../../src/operations/productCoordinator").ProductCoordinator)=>owner.loadArticle("url")],
 ["cancel",(owner:import("../../src/operations/productCoordinator").ProductCoordinator)=>owner.cancelLoad],
 ["reset",(owner:import("../../src/operations/productCoordinator").ProductCoordinator)=>owner.resetArticle],
 ["read collection",(owner:import("../../src/operations/productCoordinator").ProductCoordinator)=>owner.getCollection("collection")],
] as const)it.effect(name+" before bootstrap fails with no backend IO",()=>Effect.gen(function*(){const port=backendHarness();const scope=yield* Scope.make();const owner=yield* makeProductCoordinator(port).pipe(Scope.provide(scope));try{const result=yield* Effect.result(run(owner) as Effect.Effect<unknown,import("../../src/operations/productCoordinator").ProductError>);expect(result._tag).toBe("Failure");if(result._tag==="Failure")expect(result.failure._tag).toBe("ProductUnavailable");expect(port.calls.size).toBe(0);}finally{yield* Scope.close(scope,Exit.void);}}));

it.effect("simultaneous refresh callers share one actual read without duplicate ownership",()=>Effect.gen(function*(){const h=yield* setup();const held=yield* Deferred.make<unknown>();try{h.port.override("getDraft",Deferred.await(held));const first=yield* h.owner.refreshDraft.pipe(Effect.forkScoped);for(let i=0;i<10;i++)yield* Effect.yieldNow;expect(h.port.count("getDraft")).toBe(2);yield* h.port.wait("getDraft",2);const second=yield* h.owner.refreshDraft.pipe(Effect.forkScoped);for(let i=0;i<10;i++)yield* Effect.yieldNow;expect(h.port.count("getDraft")).toBe(2);yield* Deferred.succeed(held,reply(draft()));expect((yield* Fiber.join(first)).summary.revision).toBe(1);expect((yield* Fiber.join(second)).summary.revision).toBe(1);}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("refresh rejects foreign summary session without altering confirmed draft",()=>Effect.gen(function*(){const h=yield* setup();try{const wrong=draft({summary:{...draft().summary,backendSessionId:"foreign",revision:99}});h.port.override("getDraft",Effect.succeed(reply(wrong)));expect((yield* Effect.result(h.owner.refreshDraft))._tag).toBe("Failure");expect((yield* h.owner.draft)?.summary.backendSessionId).toBe("session");expect((yield* h.owner.draft)?.summary.revision).toBe(1);}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("refresh ignores older revision and generation independently",()=>Effect.gen(function*(){const current=draft({summary:{...draft().summary,revision:3,articleGeneration:3}});const h=yield* setup(current);try{for(const summary of [{...current.summary,revision:2},{...current.summary,revision:4,articleGeneration:2}]){h.port.override("getDraft",Effect.succeed(reply(draft({summary}))));expect((yield* h.owner.refreshDraft).summary).toEqual(current.summary);}expect((yield* h.owner.draft)?.summary).toEqual(current.summary);}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("duplicate cancel is rejected while first actual cancel remains active",()=>Effect.gen(function*(){const h=yield* setup();const held=yield* Deferred.make<unknown>();try{h.port.override("editDraft",Deferred.await(held));const first=yield* h.owner.cancelLoad.pipe(Effect.forkScoped);yield* h.port.wait("editDraft");expect((yield* Effect.result(h.owner.cancelLoad))._tag).toBe("Failure");expect(h.port.count("editDraft")).toBe(1);yield* Deferred.succeed(held,reply(draft()));yield* Fiber.join(first);}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("known reset rejection releases admission without querying unknown operation",()=>Effect.gen(function*(){const h=yield* setup();try{h.port.override("editDraft",Effect.fail(reject));const failed=yield* Effect.result(h.owner.resetArticle);expect(failed._tag).toBe("Failure");expect(h.port.count("getDraftOperation")).toBe(0);yield* h.owner.resetArticle;expect(h.port.count("editDraft")).toBe(2);expect((yield* h.owner.draft)?.summary.state).toBe("empty");}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("pending edit worker prevents article replacement but permits real cancellation",()=>Effect.gen(function*(){const h=yield* setup();const held=yield* Deferred.make<unknown>();try{h.port.override("editDraft",Deferred.await(held));const receipt=yield* h.owner.edit(intent());yield* h.port.wait("editDraft");expect((yield* Effect.result(h.owner.loadArticle("url")))._tag).toBe("Failure");expect(h.port.count("loadArticle")).toBe(0);yield* h.owner.cancelLoad;expect(h.port.count("editDraft")).toBe(2);yield* Deferred.succeed(held,reply(h.port.current()));yield* h.owner.commitThrough(receipt);}finally{yield* Scope.close(h.scope,Exit.void);}}));


it.effect("foreign read envelope session is stale even when payload ID matches",()=>Effect.gen(function*(){const h=yield* setup();try{h.port.override("getCollection",Effect.succeed(reply(collection(),"foreign")));const result=yield* Effect.result(h.owner.getCollection("collection"));expect(result._tag).toBe("Failure");if(result._tag==="Failure")expect(result.failure._tag==="ProductUnavailable"&&result.failure.reason).toBe("stale");expect((yield* h.owner.draft)?.summary.revision).toBe(1);}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("participant comment page must match ID and every request context field",()=>Effect.gen(function*(){const h=yield* setup();const context={backendSessionId:"session",draftId:"draft",revision:1,articleGeneration:1};const request={...context,participantId:"p",offset:0,limit:50};try{expect((yield* h.owner.queryParticipantComments(request)).data.participantId).toBe("p");for(const bad of [{context,participantId:"other"},{context:{...context,backendSessionId:"foreign"},participantId:"p"},{context:{...context,draftId:"other"},participantId:"p"},{context:{...context,revision:2},participantId:"p"},{context:{...context,articleGeneration:2},participantId:"p"}]){h.port.override("queryParticipantComments",Effect.succeed(reply({...bad,total:0,offset:0,rows:[]})));expect((yield* Effect.result(h.owner.queryParticipantComments(request)))._tag).toBe("Failure");}}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("comment reply using old request is rejected after real draft revision changes",()=>Effect.gen(function*(){const h=yield* setup();const context={backendSessionId:"session",draftId:"draft",revision:1,articleGeneration:1};const request={...context,participantId:"p",offset:0,limit:50};try{const next=draft({summary:{...draft().summary,revision:2}});h.port.set(next);yield* h.owner.acceptBootstrap(bootstrap(next));expect((yield* Effect.result(h.owner.queryParticipantComments(request)))._tag).toBe("Failure");expect((yield* h.owner.draft)?.summary.revision).toBe(2);}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("loading draft blocks configuration and finalization without backend mutation",()=>Effect.gen(function*(){const h=yield* setup(draft({summary:{...draft().summary,state:"loading"}}));try{expect((yield* Effect.result(h.owner.edit(intent())))._tag).toBe("Failure");expect((yield* Effect.result(h.owner.createCollection(0,"immediate")))._tag).toBe("Failure");expect([h.port.count("editDraft"),h.port.count("createCollection")]).toEqual([0,0]);}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("known finalization rejection keeps seal if actual confirmation read fails",()=>Effect.gen(function*(){const h=yield* setup();try{h.port.override("createCollection",Effect.fail(reject));h.port.override("getDraft",Effect.fail(new ProtocolError()));expect((yield* Effect.result(h.owner.createCollection(0,"immediate")))._tag).toBe("Failure");expect((yield* Effect.result(h.owner.edit(intent())))._tag).toBe("Failure");expect(h.port.count("editDraft")).toBe(0);}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("lost finalization response recovers one actual committed collection without resend",()=>Effect.gen(function*(){const h=yield* setup();try{h.port.override("createCollection",Effect.fail(new ProtocolError()));h.port.override("lookup",Effect.succeed(reply({operationId:"operation-1",state:"succeeded",kind:"CreateCollection",collectionId:"collection",roundId:"round",revision:1,failureCode:null})));const actual=yield* h.owner.createCollection(0,"immediate");expect(actual.collectionId).toBe("collection");expect([h.port.count("createCollection"),h.port.count("lookup"),h.port.count("getCollection")]).toEqual([1,1,1]);expect((yield* Effect.result(h.owner.edit(intent())))._tag).toBe("Failure");}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("collection known rejection releases exact target reservation for explicit retry",()=>Effect.gen(function*(){const h=yield* setup();const request={collectionId:"collection",roundId:"round",expectedRevision:1,expectedVersion:1,prizes:[],message:"",mode:"immediate" as const,scheduledAt:null};try{h.port.override("rerun",Effect.fail(reject));expect((yield* Effect.result(h.owner.collectionCommand("rerun",request)))._tag).toBe("Failure");expect(h.port.count("lookup")).toBe(0);expect((yield* h.owner.collectionCommand("rerun",request)).collectionId).toBe("collection");expect(h.port.count("rerun")).toBe(2);}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("retired session history remains bounded after 65 real session changes",()=>Effect.gen(function*(){const h=yield* setup();try{for(let index=1;index<=65;index++){const session="session-"+index;const current=draft({summary:{...draft().summary,backendSessionId:session,draftId:"draft-"+index}});h.port.set(current);yield* h.owner.acceptBootstrap(bootstrap(current,session));}expect((yield* Effect.result(h.owner.acceptBootstrap(bootstrap(draft({summary:{...draft().summary,backendSessionId:"session-64"}}),"session-64"))))._tag).toBe("Failure");h.port.set(draft());yield* h.owner.acceptBootstrap(bootstrap());expect((yield* h.owner.draft)?.summary.backendSessionId).toBe("session");}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("edit without bootstrap has explicit session error and no backend mutation",()=>Effect.gen(function*(){const port=backendHarness();const scope=yield* Scope.make();const owner=yield* makeProductCoordinator(port).pipe(Scope.provide(scope));try{const result=yield* Effect.result(owner.edit(intent()));expect(result._tag).toBe("Failure");if(result._tag==="Failure")expect(result.failure._tag==="ProductUnavailable"&&result.failure.reason).toBe("session_required");expect(port.calls.size).toBe(0);}finally{yield* Scope.close(scope,Exit.void);}}));

for(const operation of ["load","cancel","reset","edit","finalize"] as const)it.effect(operation+" cannot use null draft after valid bootstrap with no active draft",()=>Effect.gen(function*(){const port=backendHarness();const scope=yield* Scope.make();const owner=yield* makeProductCoordinator(port).pipe(Scope.provide(scope));try{yield* owner.acceptBootstrap(bootstrap(null));owner.setWritesBlocked(false);const command:Effect.Effect<unknown,import("../../src/operations/productCoordinator").ProductError>=operation==="load"?owner.loadArticle("url"):operation==="cancel"?owner.cancelLoad:operation==="reset"?owner.resetArticle:operation==="edit"?owner.edit(intent()):owner.createCollection(0,"immediate");expect((yield* Effect.result(command))._tag).toBe("Failure");expect(port.calls.size).toBe(0);}finally{yield* Scope.close(scope,Exit.void);}}));

it.effect("initial refresh failure leaves active ID for explicit ensure to retry actual read",()=>Effect.gen(function*(){const port=backendHarness();const scope=yield* Scope.make();const owner=yield* makeProductCoordinator(port).pipe(Scope.provide(scope));try{port.override("getDraft",Effect.fail(new ProtocolError()));expect((yield* Effect.result(owner.acceptBootstrap(bootstrap())))._tag).toBe("Failure");expect(yield* owner.draft).toBeNull();owner.setWritesBlocked(false);expect((yield* owner.ensureDraft).summary.draftId).toBe("draft");expect([port.count("getDraft"),port.count("createDraft")]).toEqual([2,0]);}finally{yield* Scope.close(scope,Exit.void);}}));

it.effect("sealed confirmed creation ensure rechecks actual draft rather than reusing stale projection",()=>Effect.gen(function*(){const h=yield* setup();try{yield* h.owner.createCollection(0,"immediate");const reads=h.port.count("getDraft");expect((yield* h.owner.ensureDraft).summary.draftId).toBe("draft");expect(h.port.count("getDraft")).toBe(reads+1);expect(h.port.count("createDraft")).toBe(0);}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("finalized draft cannot be replaced while app write gate is blocked",()=>Effect.gen(function*(){const h=yield* setup(draft({summary:{...draft().summary,state:"finalized",collectionId:"collection"}}));try{h.owner.setWritesBlocked(true);expect((yield* Effect.result(h.owner.ensureDraft))._tag).toBe("Failure");expect((yield* h.owner.draft)?.summary.state).toBe("finalized");expect(h.port.count("createDraft")).toBe(0);}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("same-field prize tail coalesces while preserving latest owned prize configuration",()=>Effect.gen(function*(){const h=yield* setup();const held=yield* Deferred.make<unknown>();try{h.port.override("editDraft",Deferred.await(held));yield* h.owner.edit(intent("ToggleParticipant"));yield* h.port.wait("editDraft");const first=yield* h.owner.edit(intent("SetPrizes"),"prizes");const latest=yield* h.owner.edit({...intent("SetPrizes"),prizes:{...draft().prizes,single:{id:"single",name:"최신",count:1}}},"prizes");const waiting=yield* h.owner.commitThrough(first).pipe(Effect.forkScoped);yield* Deferred.succeed(held,reply(draft()));yield* Fiber.join(waiting);yield* h.owner.commitThrough(latest);expect(h.port.count("editDraft")).toBe(2);expect((yield* h.owner.draft)?.prizes.single.name).toBe("최신");}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("published draft copies nested snapshot and load metadata instead of aliasing source",()=>Effect.gen(function*(){const original=draft({summary:{...draft().summary,snapshot:{snapshotId:"snapshot",collectedAt:"2026-10-06T00:00:00Z",complete:true,pages:1,acceptedComments:3,deletedComments:0,unsupportedComments:0}},load:{operationId:"load",sequence:1,pages:1,comments:3,state:"completed",failureCode:null}});const h=yield* setup(original);try{const value=yield* h.owner.draft;expect(value).not.toBe(original);expect(value?.summary.snapshot).not.toBe(original.summary.snapshot);expect(value?.load).not.toBe(original.load);expect(Object.isFrozen(value?.summary.snapshot)).toBe(true);expect(Object.isFrozen(value?.load)).toBe(true);}finally{yield* Scope.close(h.scope,Exit.void);}}));

for(const operation of ["load","cancel","finalize","collection"] as const)it.effect(operation+" reservation waiting on ID cannot dispatch under replacement session",()=>Effect.gen(function*(){const port=backendHarness();const next=yield* Deferred.make<string>();const scope=yield* Scope.make();const owner=yield* makeProductCoordinator({...port,newId:Deferred.await(next)}).pipe(Scope.provide(scope));try{yield* owner.acceptBootstrap(bootstrap());owner.setWritesBlocked(false);const command:Effect.Effect<unknown,import("../../src/operations/productCoordinator").ProductError>=operation==="load"?owner.loadArticle("url"):operation==="cancel"?owner.cancelLoad:operation==="finalize"?owner.createCollection(0,"immediate"):owner.collectionCommand("rerun",{collectionId:"collection",roundId:"round",expectedRevision:1,expectedVersion:1,prizes:[],message:"",mode:"immediate",scheduledAt:null});const work=yield* command.pipe(Effect.forkScoped);for(let i=0;i<10;i++)yield* Effect.yieldNow;const fresh=draft({summary:{...draft().summary,backendSessionId:"new",draftId:"new-draft"}});port.set(fresh);yield* owner.acceptBootstrap(bootstrap(fresh,"new"));yield* Deferred.succeed(next,"operation");yield* waitFailure(work);expect([port.count("loadArticle"),port.count("editDraft"),port.count("createCollection"),port.count("rerun")]).toEqual([0,0,0,0]);expect((yield* owner.draft)?.summary.draftId).toBe("new-draft");}finally{yield* Scope.close(scope,Exit.void);}}));

it.effect("unexpected mutation defect preserves unknown receipt and closes worker without hanging barrier",()=>Effect.gen(function*(){const h=yield* setup();try{h.port.override("editDraft",Effect.die(new Error("injected adapter defect")));const receipt=yield* h.owner.edit(intent());const wait=yield* h.owner.commitThrough(receipt).pipe(Effect.forkScoped);for(let i=0;i<20;i++)yield* Effect.yieldNow;expect(wait.pollUnsafe()?._tag).toBe("Failure");expect((yield* Effect.result(h.owner.edit(intent())))._tag).toBe("Failure");expect(h.port.count("editDraft")).toBe(1);h.port.override("getDraftOperation",Effect.succeed(reply({operationId:receipt.intentId,state:"succeeded",summary:draft().summary,failureCode:null})));yield* h.owner.recheck;yield* h.owner.commitThrough(receipt);expect(h.port.count("editDraft")).toBe(1);}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("durable manual confirmation frees target only after terminal actual collection read",()=>Effect.gen(function*(){const h=yield* setup();const request={collectionId:"collection",roundId:"round",expectedRevision:1,expectedVersion:1,prizes:[],message:"",mode:"immediate" as const,scheduledAt:null};try{h.port.override("rerun",Effect.fail(new TransportError()));const work=yield* h.owner.collectionCommand("rerun",request).pipe(Effect.forkScoped);yield* h.port.wait("lookup",1);yield* TestClock.adjust(1000);yield* h.port.wait("lookup",2);yield* TestClock.adjust(2000);yield* h.port.wait("lookup",3);yield* TestClock.adjust(4000);yield* h.port.wait("lookup",4);yield* waitFailure(work);expect((yield* Effect.result(h.owner.collectionCommand("rerun",request)))._tag).toBe("Failure");h.port.override("lookup",Effect.succeed(reply({operationId:"operation-1",state:"succeeded",kind:"Rerun",collectionId:"collection",roundId:"round",revision:2,failureCode:null})));yield* h.owner.recheck;expect(h.port.count("lookup")).toBe(5);expect(h.port.count("getCollection")).toBe(1);expect((yield* h.owner.collectionCommand("rerun",request)).collectionId).toBe("collection");expect(h.port.count("rerun")).toBe(2);}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("manual confirmation defect is surfaced and singleflight is cleared for later explicit retry",()=>Effect.gen(function*(){const h=yield* setup();try{h.port.override("createCollection",Effect.fail(new TransportError()));const work=yield* h.owner.createCollection(0,"immediate").pipe(Effect.forkScoped);yield* h.port.wait("lookup",1);yield* TestClock.adjust(1000);yield* h.port.wait("lookup",2);yield* TestClock.adjust(2000);yield* h.port.wait("lookup",3);yield* TestClock.adjust(4000);yield* h.port.wait("lookup",4);yield* waitFailure(work);h.port.override("lookup",Effect.die(new Error("injected lookup defect")));const manual=yield* Effect.exit(h.owner.recheck);expect(manual._tag).toBe("Failure");yield* h.owner.recheck;expect(h.port.count("lookup")).toBe(6);expect((yield* Effect.result(h.owner.edit(intent())))._tag).toBe("Failure");}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("setWritesBlocked after owner close cannot reopen mutation or retained reads",()=>Effect.gen(function*(){const h=yield* setup();yield* Scope.close(h.scope,Exit.void);h.owner.setWritesBlocked(false);expect((yield* Effect.result(h.owner.edit(intent())))._tag).toBe("Failure");expect((yield* Effect.result(h.owner.getCollection("collection")))._tag).toBe("Failure");expect(h.port.count("editDraft")).toBe(0);}));
for(const corrupt of ["header session","missing summary","summary session","summary draft"] as const)it.effect("lost draft response does not trust "+corrupt+" and observes same operation again",()=>Effect.gen(function*(){const h=yield* setup();try{h.port.override("loadArticle",Effect.fail(new TransportError()));const summary=corrupt==="missing summary"?null:{...draft().summary,...(corrupt==="summary session"?{backendSessionId:"foreign"}:{}),...(corrupt==="summary draft"?{draftId:"foreign"}:{})};h.port.override("getDraftOperation",Effect.succeed(reply({operationId:"operation-1",state:"succeeded",summary,failureCode:null},corrupt==="header session"?"foreign":"session")),Effect.succeed(reply({operationId:"operation-1",state:"succeeded",summary:draft().summary,failureCode:null})));const load=yield* h.owner.loadArticle("url").pipe(Effect.forkScoped);yield* h.port.wait("getDraftOperation",1);for(let i=0;i<10;i++)yield* Effect.yieldNow;if(corrupt==="summary draft")expect(load.pollUnsafe()?._tag).toBe("Failure");else expect(load.pollUnsafe()).toBeUndefined();yield* TestClock.adjust(1000);if(corrupt==="summary draft")yield* waitFailure(load);else expect((yield* Fiber.join(load)).summary.draftId).toBe("draft");expect(h.port.count("loadArticle")).toBe(1);expect(h.port.count("getDraftOperation")).toBe(corrupt==="summary draft"?1:2);}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("lost draft polling stops as stale before another IO after backend session replacement",()=>Effect.gen(function*(){const h=yield* setup();try{h.port.override("loadArticle",Effect.fail(new TransportError()));const load=yield* h.owner.loadArticle("url").pipe(Effect.forkScoped);yield* h.port.wait("getDraftOperation",1);const fresh=draft({summary:{...draft().summary,backendSessionId:"new",draftId:"new-draft"}});h.port.set(fresh);yield* h.owner.acceptBootstrap(bootstrap(fresh,"new"));yield* TestClock.adjust(1000);yield* waitFailure(load);expect(h.port.count("getDraftOperation")).toBe(1);expect((yield* h.owner.draft)?.summary.draftId).toBe("new-draft");}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("failed draft observation with absent failure code yields explicit protocol rejection",()=>Effect.gen(function*(){const h=yield* setup();try{h.port.override("loadArticle",Effect.fail(new TransportError()));h.port.override("getDraftOperation",Effect.succeed(reply({operationId:"operation-1",state:"failed",summary:null,failureCode:null})));const result=yield* Effect.result(h.owner.loadArticle("url"));expect(result._tag).toBe("Failure");if(result._tag==="Failure")expect(result.failure._tag==="BackendRejected"&&result.failure.code).toBe("ProtocolError");expect(h.port.count("getDraftOperation")).toBe(1);}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("failed durable observation with absent failure code yields explicit protocol rejection",()=>Effect.gen(function*(){const h=yield* setup();try{h.port.override("createCollection",Effect.fail(new TransportError()));h.port.override("lookup",Effect.succeed(reply({operationId:"operation-1",state:"failed",kind:null,collectionId:null,roundId:null,revision:null,failureCode:null})));const result=yield* Effect.result(h.owner.createCollection(0,"immediate"));expect(result._tag).toBe("Failure");if(result._tag==="Failure")expect(result.failure._tag==="BackendRejected"&&result.failure.code).toBe("ProtocolError");expect(h.port.count("getCollection")).toBe(0);}finally{yield* Scope.close(h.scope,Exit.void);}}));

for(const corrupt of ["envelope session","payload ID"] as const)it.effect("durable success rejects collection "+corrupt+" before a valid later observation",()=>Effect.gen(function*(){const h=yield* setup();try{h.port.override("createCollection",Effect.fail(new TransportError()));const observation=reply({operationId:"operation-1",state:"succeeded",kind:"CreateCollection",collectionId:"collection",roundId:"round",revision:1,failureCode:null});h.port.override("lookup",Effect.succeed(observation),Effect.succeed(observation));h.port.override("getCollection",Effect.succeed(reply({...collection(),collectionId:corrupt==="payload ID"?"wrong":"collection"},corrupt==="envelope session"?"foreign":"session")));const create=yield* h.owner.createCollection(0,"immediate").pipe(Effect.forkScoped);yield* h.port.wait("getCollection",1);for(let i=0;i<10;i++)yield* Effect.yieldNow;expect(create.pollUnsafe()).toBeUndefined();yield* TestClock.adjust(1000);expect((yield* Fiber.join(create)).collectionId).toBe("collection");expect([h.port.count("createCollection"),h.port.count("lookup"),h.port.count("getCollection")]).toEqual([1,2,2]);}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("durable collection command never accepts a terminal observation for another target",()=>Effect.gen(function*(){const h=yield* setup();const request={collectionId:"collection",roundId:"round",expectedRevision:1,expectedVersion:1,prizes:[],message:"",mode:"immediate" as const,scheduledAt:null};try{h.port.override("rerun",Effect.fail(new TransportError()));h.port.override("lookup",Effect.succeed(reply({operationId:"operation-1",state:"succeeded",kind:"Rerun",collectionId:"wrong",roundId:"round",revision:1,failureCode:null})),Effect.succeed(reply({operationId:"operation-1",state:"succeeded",kind:"Rerun",collectionId:"collection",roundId:"round",revision:1,failureCode:null})));const work=yield* h.owner.collectionCommand("rerun",request).pipe(Effect.forkScoped);yield* h.port.wait("lookup",1);expect(h.port.count("getCollection")).toBe(0);yield* TestClock.adjust(1000);expect((yield* Fiber.join(work)).collectionId).toBe("collection");expect(h.port.count("rerun")).toBe(1);}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("finalization success arriving after session replacement cannot publish old collection",()=>Effect.gen(function*(){const h=yield* setup();const held=yield* Deferred.make<unknown>();try{h.port.override("createCollection",Deferred.await(held));const work=yield* h.owner.createCollection(0,"immediate").pipe(Effect.forkScoped);yield* h.port.wait("createCollection");const fresh=draft({summary:{...draft().summary,backendSessionId:"new",draftId:"new-draft"}});h.port.set(fresh);yield* h.owner.acceptBootstrap(bootstrap(fresh,"new"));yield* Deferred.succeed(held,reply(collection()));yield* waitFailure(work);expect((yield* h.owner.draft)?.summary.draftId).toBe("new-draft");expect(h.port.count("getDraft")).toBe(2);}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("old refresh finishing after replacement leaves newer singleflight owner intact",()=>Effect.gen(function*(){const h=yield* setup();const held=yield* Deferred.make<unknown>();try{h.port.override("getDraft",Deferred.await(held));const old=yield* h.owner.refreshDraft.pipe(Effect.forkScoped);for(let i=0;i<10;i++)yield* Effect.yieldNow;expect(h.port.count("getDraft")).toBe(2);yield* h.port.wait("getDraft",2);const fresh=draft({summary:{...draft().summary,backendSessionId:"new",draftId:"new-draft"}});h.port.set(fresh);yield* h.owner.acceptBootstrap(bootstrap(fresh,"new"));yield* Deferred.succeed(held,reply(draft()));yield* waitFailure(old);expect((yield* h.owner.draft)?.summary.draftId).toBe("new-draft");expect((yield* h.owner.refreshDraft).summary.draftId).toBe("new-draft");}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("global reservations without IDs count toward64 cap and never admit65th IO",()=>Effect.gen(function*(){const port=backendHarness();const next=yield* Deferred.make<string>();const scope=yield* Scope.make();const owner=yield* makeProductCoordinator({...port,newId:Deferred.await(next)}).pipe(Scope.provide(scope));try{yield* owner.acceptBootstrap(bootstrap());owner.setWritesBlocked(false);const request={roundId:"round",expectedRevision:1,expectedVersion:1,prizes:[],message:"",mode:"immediate" as const,scheduledAt:null};for(let index=0;index<64;index++){yield* owner.collectionCommand("rerun",{...request,collectionId:"collection-"+index}).pipe(Effect.forkScoped);for(let pause=0;pause<5;pause++)yield* Effect.yieldNow;}const overflow=yield* owner.collectionCommand("rerun",{...request,collectionId:"collection-64"}).pipe(Effect.forkScoped);for(let i=0;i<10;i++)yield* Effect.yieldNow;expect(overflow.pollUnsafe()?._tag).toBe("Failure");expect((yield* Effect.result(owner.cancelLoad))._tag).toBe("Failure");expect(port.count("rerun")).toBe(0);expect(port.count("editDraft")).toBe(0);}finally{yield* Scope.close(scope,Exit.void);}}));

it.effect("unknown direct command remains blocked on manual unknown and releases only terminal failure",()=>Effect.gen(function*(){const h=yield* setup();try{h.port.override("loadArticle",Effect.fail(new TransportError()));const load=yield* h.owner.loadArticle("url").pipe(Effect.forkScoped);yield* h.port.wait("getDraftOperation",1);yield* TestClock.adjust(1000);yield* h.port.wait("getDraftOperation",2);yield* TestClock.adjust(2000);yield* h.port.wait("getDraftOperation",3);yield* TestClock.adjust(4000);yield* h.port.wait("getDraftOperation",4);yield* waitFailure(load);yield* h.owner.recheck;expect((yield* Effect.result(h.owner.loadArticle("new")))._tag).toBe("Failure");h.port.override("getDraftOperation",Effect.succeed(reply({operationId:"operation-1",state:"failed",summary:null,failureCode:"InvalidInput"})));yield* h.owner.recheck;yield* h.owner.loadArticle("new");expect(h.port.count("loadArticle")).toBe(2);expect(h.port.count("getDraftOperation")).toBe(6);}finally{yield* Scope.close(h.scope,Exit.void);}}));
it.effect("manual check skips already confirmed receipts without operation IO",()=>Effect.gen(function*(){const h=yield* setup();try{const receipt=yield* h.owner.edit(intent());yield* h.owner.commitThrough(receipt);yield* h.owner.recheck;expect(h.port.count("getDraftOperation")).toBe(0);expect((yield* h.owner.draft)?.summary.revision).toBe(2);}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("unknown receipt manual check stays unknown and retains next mutation block",()=>Effect.gen(function*(){const h=yield* setup();try{h.port.override("editDraft",Effect.fail(new TransportError()));const receipt=yield* h.owner.edit(intent());const barrier=yield* h.owner.commitThrough(receipt).pipe(Effect.forkScoped);yield* h.port.wait("getDraftOperation",1);yield* TestClock.adjust(1000);yield* h.port.wait("getDraftOperation",2);yield* TestClock.adjust(2000);yield* h.port.wait("getDraftOperation",3);yield* TestClock.adjust(4000);yield* h.port.wait("getDraftOperation",4);yield* waitFailure(barrier);yield* h.owner.recheck;expect(h.port.count("getDraftOperation")).toBe(5);expect((yield* Effect.result(h.owner.commitThrough(receipt)))._tag).toBe("Failure");expect((yield* Effect.result(h.owner.edit(intent())))._tag).toBe("Failure");expect(h.port.count("editDraft")).toBe(1);}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("known collection success from previous session cannot publish target result",()=>Effect.gen(function*(){const h=yield* setup();const held=yield* Deferred.make<unknown>();const request={collectionId:"collection",roundId:"round",expectedRevision:1,expectedVersion:1,prizes:[],message:"",mode:"immediate" as const,scheduledAt:null};try{h.port.override("rerun",Deferred.await(held));const work=yield* h.owner.collectionCommand("rerun",request).pipe(Effect.forkScoped);yield* h.port.wait("rerun");const fresh=draft({summary:{...draft().summary,backendSessionId:"new",draftId:"new-draft"}});h.port.set(fresh);yield* h.owner.acceptBootstrap(bootstrap(fresh,"new"));yield* Deferred.succeed(held,reply(collection()));yield* waitFailure(work);expect((yield* h.owner.draft)?.summary.draftId).toBe("new-draft");}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("finalization ID failure after new session does not alter its actual draft projection",()=>Effect.gen(function*(){const port=backendHarness();const next=yield* Deferred.make<string,ClientIdError>();const scope=yield* Scope.make();const owner=yield* makeProductCoordinator({...port,newId:Deferred.await(next)}).pipe(Scope.provide(scope));try{yield* owner.acceptBootstrap(bootstrap());owner.setWritesBlocked(false);const work=yield* owner.createCollection(0,"immediate").pipe(Effect.forkScoped);for(let i=0;i<10;i++)yield* Effect.yieldNow;const fresh=draft({summary:{...draft().summary,backendSessionId:"new",draftId:"new-draft"}});port.set(fresh);yield* owner.acceptBootstrap(bootstrap(fresh,"new"));yield* Deferred.fail(next,new ClientIdError());yield* waitFailure(work);expect((yield* owner.draft)?.summary.draftId).toBe("new-draft");expect(port.count("createCollection")).toBe(0);}finally{yield* Scope.close(scope,Exit.void);}}));

it.effect("known finalization rejection after session replacement never refreshes old draft",()=>Effect.gen(function*(){const h=yield* setup();const held=yield* Deferred.make<unknown,typeof reject>();try{h.port.override("createCollection",Deferred.await(held));const work=yield* h.owner.createCollection(0,"immediate").pipe(Effect.forkScoped);yield* h.port.wait("createCollection");const fresh=draft({summary:{...draft().summary,backendSessionId:"new",draftId:"new-draft"}});h.port.set(fresh);yield* h.owner.acceptBootstrap(bootstrap(fresh,"new"));yield* Deferred.fail(held,reject);yield* waitFailure(work);expect(h.port.count("getDraft")).toBe(2);expect((yield* h.owner.draft)?.summary.draftId).toBe("new-draft");}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("retired edit worker defect cannot block the replacement session worker",()=>Effect.gen(function*(){const h=yield* setup();const held=yield* Deferred.make<void>();try{h.port.override("editDraft",Deferred.await(held).pipe(Effect.andThen(Effect.die(new Error("retired worker defect")))));const old=yield* h.owner.edit(intent());yield* h.port.wait("editDraft");const fresh=draft({summary:{...draft().summary,backendSessionId:"new",draftId:"new-draft"}});h.port.set(fresh);yield* h.owner.acceptBootstrap(bootstrap(fresh,"new"));const latest=yield* h.owner.edit(intent());yield* h.owner.commitThrough(latest);yield* Deferred.succeed(held,undefined);for(let i=0;i<20;i++)yield* Effect.yieldNow;expect((yield* Effect.result(h.owner.commitThrough(old)))._tag).toBe("Failure");const after=yield* h.owner.edit(intent());yield* h.owner.commitThrough(after);expect(h.port.count("editDraft")).toBe(3);expect((yield* h.owner.draft)?.summary.draftId).toBe("new-draft");}finally{yield* Scope.close(h.scope,Exit.void);}}));

it.effect("worker defect preserves queued successor until unknown head is actually confirmed",()=>Effect.gen(function*(){const h=yield* setup();const held=yield* Deferred.make<void>();try{h.port.override("editDraft",Deferred.await(held).pipe(Effect.andThen(Effect.die(new Error("worker defect")))));const first=yield* h.owner.edit(intent("ToggleParticipant"));yield* h.port.wait("editDraft");const second=yield* h.owner.edit(intent("ToggleParticipant"));yield* Deferred.succeed(held,undefined);for(let i=0;i<20;i++)yield* Effect.yieldNow;expect((yield* Effect.result(h.owner.commitThrough(second)))._tag).toBe("Failure");expect(h.port.count("editDraft")).toBe(1);h.port.override("getDraftOperation",Effect.succeed(reply({operationId:first.intentId,state:"succeeded",summary:draft().summary,failureCode:null})));yield* h.owner.recheck;yield* h.owner.commitThrough(second);expect(h.port.count("editDraft")).toBe(2);}finally{yield* Scope.close(h.scope,Exit.void);}}));