// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DraftService exposes concrete draft commands and bounded read projections.
 * Snapshot promotion and cancellation belong to the Go application owner.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contracts$0 from "../contracts/models.js";

export function CreateDraft(request: contracts$0.CreateDraftRequest): $CancellablePromise<contracts$0.DraftResponse> {
    return $Call.ByID(2868141020, request);
}

export function EditDraft(request: contracts$0.DraftEditRequest): $CancellablePromise<contracts$0.DraftResponse> {
    return $Call.ByID(2416021424, request);
}

export function GetDraft(request: contracts$0.DraftQuery): $CancellablePromise<contracts$0.DraftResponse> {
    return $Call.ByID(3617670506, request);
}

export function GetDraftOperation(request: contracts$0.OperationLookupRequest): $CancellablePromise<contracts$0.DraftOperationResponse> {
    return $Call.ByID(2794807679, request);
}

export function LoadArticle(request: contracts$0.LoadArticleRequest): $CancellablePromise<contracts$0.DraftResponse> {
    return $Call.ByID(1616219941, request);
}

export function QueryParticipantComments(request: contracts$0.ParticipantCommentsQuery): $CancellablePromise<contracts$0.CommentsResponse> {
    return $Call.ByID(2685427950, request);
}

export function QueryParticipants(request: contracts$0.ParticipantQuery): $CancellablePromise<contracts$0.ParticipantsResponse> {
    return $Call.ByID(1442270765, request);
}
