// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contracts$0 from "../contracts/models.js";

export function CopyText(request: contracts$0.TextExportRequest): $CancellablePromise<contracts$0.ExportResponse> {
    return $Call.ByID(611818236, request);
}

export function OpenArticle(request: contracts$0.ArticleExportRequest): $CancellablePromise<contracts$0.ExportResponse> {
    return $Call.ByID(3143704348, request);
}

export function SavePNG(request: contracts$0.PNGRequest): $CancellablePromise<contracts$0.ExportResponse> {
    return $Call.ByID(272480182, request);
}
