// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contracts$0 from "../contracts/models.js";

export function CancelSchedule(request: contracts$0.CollectionCommandRequest): $CancellablePromise<contracts$0.CollectionResponse> {
    return $Call.ByID(3827868161, request);
}

export function CreateCollection(request: contracts$0.CreateCollectionRequest): $CancellablePromise<contracts$0.CollectionResponse> {
    return $Call.ByID(2633550642, request);
}

export function GetCollection(request: contracts$0.CollectionQuery): $CancellablePromise<contracts$0.CollectionResponse> {
    return $Call.ByID(1947843826, request);
}

export function QueryFrozenComments(query: contracts$0.FrozenCommentsQuery): $CancellablePromise<contracts$0.FrozenCommentsResponse> {
    return $Call.ByID(249898922, query);
}

export function QueryFrozenParticipants(query: contracts$0.FrozenParticipantsQuery): $CancellablePromise<contracts$0.FrozenParticipantsResponse> {
    return $Call.ByID(2295428962, query);
}

export function Rerun(request: contracts$0.CollectionCommandRequest): $CancellablePromise<contracts$0.CollectionResponse> {
    return $Call.ByID(2028294364, request);
}

export function RetryRound(request: contracts$0.CollectionCommandRequest): $CancellablePromise<contracts$0.CollectionResponse> {
    return $Call.ByID(672253356, request);
}

export function SetSchedule(request: contracts$0.CollectionCommandRequest): $CancellablePromise<contracts$0.CollectionResponse> {
    return $Call.ByID(1523402347, request);
}
