// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service owns the bootstrap and durable recovery enumeration boundary.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contracts$0 from "../contracts/models.js";

export function Bootstrap(): $CancellablePromise<contracts$0.BootstrapResponse> {
    return $Call.ByID(3877523074);
}

export function ListPendingOperations(request: contracts$0.PendingOperationsRequest): $CancellablePromise<contracts$0.PendingOperationsResponse> {
    return $Call.ByID(1909730405, request);
}
