import { expect,it } from "@effect/vitest";
import { Deferred, Effect, Exit, Scope } from "effect";
import { DomError,DomPlatform,makeDomPlatform } from "../../src/platform/dom";
import { ClientIds,clientIdsFrom } from "../../src/platform/ids";
import { makeCreateWorkspace } from "../../src/screens/create/productOwner";
import { mountCreateProduct } from "../../src/features/create/view";
import { commandHarness,draft } from "../helpers/productCommands";

function environment(fault=0){
 let token=0;const frames=new Map<number,FrameRequestCallback>();const state={active:0,acquired:0,released:0};
 const native=makeDomPlatform({request:(callback)=>{frames.set(++token,callback);return token;},cancel:(id)=>{frames.delete(id);}},()=> "visible");
 const dom:typeof DomPlatform.Service={...native,listen:(...args)=>Effect.gen(function*(){yield* native.listen(...args);yield* Effect.acquireRelease(Effect.sync(()=>{state.active++;state.acquired++;}),()=>Effect.sync(()=>{state.active--;state.released++;}));if(fault===-1||fault===state.acquired)return yield* Effect.fail(new DomError());})};
 return {dom,state,frames,failOnNext:()=>{fault=state.acquired+1;},pulse:()=>{const ready=[...frames.values()];frames.clear();for(const callback of ready)callback(0);}};
}
function harness(initial=draft(),fault=0){return Effect.gen(function*(){
 const app=yield* Scope.make();const route=yield* Scope.fork(app,"sequential");const port=yield* commandHarness(initial);
 let prizeId=0;const work:Array<Effect.Effect<void>>=[];const workspace=yield* makeCreateWorkspace(port.commands,(effect)=>{work.push(effect);}).pipe(Scope.provide(app),Effect.provideService(ClientIds,clientIdsFrom(()=> "extra-prize-"+(++prizeId))));
 const env=environment(fault);const host=document.createElement("main");document.body.append(host);const navigated:string[]=[];
 const mount=mountCreateProduct(host,port.commands,workspace,(id)=>{navigated.push(id);}).pipe(Scope.provide(route),Effect.provideService(DomPlatform,env.dom));
 const pump=Effect.gen(function*(){for(let turn=0;turn<12;turn++){for(const effect of work.splice(0))yield* effect.pipe(Effect.forkIn(app));for(let tick=0;tick<20;tick++)yield* Effect.yieldNow;env.pulse();}});
 const close=Scope.close(app,Exit.void).pipe(Effect.andThen(port.close),Effect.andThen(Effect.sync(()=>host.remove())));
 return {app,route,port,workspace,env,host,navigated,mount,pump,close};
});}
function button(host:HTMLElement,text:string){const target=[...host.querySelectorAll("button")].find((node)=>node.textContent===text||node.getAttribute("aria-label")===text);if(target===undefined)throw Error("button missing: "+text);return target;}
function field(host:HTMLElement,label:string){const target=[...host.querySelectorAll("label")].find((node)=>node.textContent===label);if(target===undefined)throw Error("label missing "+label);const value=host.querySelector<HTMLInputElement>("#"+target.htmlFor);if(value===null)throw Error("input missing "+label);return value;}
it.effect("six compact category controls default uniform with one legacy anonymous checkbox and stable original IDs",()=>Effect.gen(function*(){
 const h=yield*harness();try{yield*h.mount;yield*h.pump;
  expect(field(h.host,"디시인사이드 게시글 주소").id).toBe("create-field-1");expect(field(h.host,"글쓴이 제외").id).toBe("create-field-3");expect(h.host.querySelectorAll('label[for="create-field-2"]')).toHaveLength(1);
  expect(h.host.querySelectorAll("[data-badge-category]")).toHaveLength(6);expect(field(h.host,"분류별 당첨 비율 사용").checked).toBe(false);
  for(const label of["고닉","비고닉","주딱","파딱","깡계","유동닉"]){expect(field(h.host,label+" 제외").checked).toBe(false);const input=field(h.host,label+" 당첨 비율");expect(input.value).toBe("100");expect(input.disabled).toBe(true);expect(input.maxLength).toBe(3);}
  expect(h.host.querySelector("details")?.open).toBe(false);expect(h.port.state.edits).toHaveLength(0);expect(h.host.querySelector(".participant-badge[data-category=fixed]")?.textContent).toBe("고닉");
  const toggle=field(h.host,"분류별 당첨 비율 사용");toggle.checked=true;toggle.dispatchEvent(new Event("change"));yield*h.pump;const ratio=field(h.host,"고닉 당첨 비율");expect(ratio.disabled).toBe(false);ratio.value="70";ratio.dispatchEvent(new Event("input"));ratio.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",cancelable:true}));yield*h.pump;
  expect(h.port.state.edits.at(-1)?.filters?.badgeRules?.fixed.weight).toBe(70);const exclude=field(h.host,"고닉 제외");exclude.checked=true;exclude.dispatchEvent(new Event("change"));yield*h.pump;expect(ratio.disabled).toBe(true);expect(h.port.state.edits.at(-1)?.filters?.badgeRules?.fixed.excluded).toBe(true);
  button(h.host,"필터 초기화").click();yield*h.pump;expect(toggle.checked).toBe(false);expect(ratio.value).toBe("100");expect(ratio.disabled).toBe(true);expect(exclude.checked).toBe(false);
 }finally{yield*h.close;}expect(h.env.state.active).toBe(0);expect(h.env.frames.size).toBe(0);expect(h.env.state.acquired).toBe(h.env.state.released);
}));
it.effect("category display uses actual badge rather than identity and cannot invent counts from a partial page",()=>Effect.gen(function*(){
 const h=yield*harness();const original=h.port.commands.queryParticipants;const categories=["fixed","semi_fixed","main_manager","sub_manager","new_account","anonymous"]as const;Object.assign(h.port.commands,{queryParticipants:(request:Parameters<typeof original>[0])=>original(request).pipe(Effect.map(reply=>({...reply,data:{...reply.data,rows:reply.data.rows.map((row,index)=>({...row,badgeCategory:categories[index%6]!}))}})))});
 try{yield*h.mount;yield*h.pump;expect([...h.host.querySelectorAll(".participant-badge")].slice(0,6).map(value=>value.textContent)).toEqual(["고닉","비고닉","주딱","파딱","깡계","유동닉"]);expect([...h.host.querySelectorAll(".badge-rule-row small")].every(value=>(value as HTMLElement).hidden)).toBe(true);expect(h.port.state.edits).toHaveLength(0);
 }finally{yield*h.close;}expect(h.env.state.active).toBe(0);
}));
it.effect("invalid active ratio opens the filter accordion and shows local correction without a reapply mutation",()=>Effect.gen(function*(){
 const h=yield*harness();try{yield*h.mount;yield*h.pump;const toggle=field(h.host,"분류별 당첨 비율 사용");toggle.checked=true;toggle.dispatchEvent(new Event("change"));yield*h.pump;const before=h.port.state.edits.length;const ratio=field(h.host,"고닉 당첨 비율");ratio.value="101";ratio.dispatchEvent(new Event("input"));ratio.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",cancelable:true}));yield*h.pump;
  expect(h.port.state.edits).toHaveLength(before);expect(ratio.value).toBe("101");expect(h.host.querySelector<HTMLDetailsElement>("details")?.open).toBe(true);expect(ratio.getAttribute("aria-invalid")).toBe("true");expect(h.host.querySelector("#"+ratio.id+"-error")?.textContent).toContain("0부터 100");expect(button(h.host,"필터 다시 적용").hidden).toBe(true);
 }finally{yield*h.close;}expect(h.env.state.active).toBe(0);expect(h.env.frames.size).toBe(0);
}));
it.effect("category totals are visible only when the authoritative page contains the full draft population",()=>Effect.gen(function*(){
 const h=yield*harness();const original=h.port.commands.queryParticipants;Object.assign(h.port.commands,{queryParticipants:(request:Parameters<typeof original>[0])=>original(request).pipe(Effect.map(reply=>({...reply,data:{...reply.data,total:3,matched:3,rows:reply.data.rows.slice(0,3).map((row,index)=>({...row,badgeCategory:index<2?"fixed"as const:"main_manager"as const,included:index!==1}))}})))});
 try{yield*h.mount;yield*h.pump;const fixed=h.host.querySelector<HTMLElement>('[data-badge-category="fixed"] small')!,manager=h.host.querySelector<HTMLElement>('[data-badge-category="main_manager"] small')!;expect(fixed.hidden).toBe(false);expect(fixed.textContent).toBe("전체 2명 · 포함 1명");expect(manager.textContent).toBe("전체 1명 · 포함 1명");expect(h.port.state.edits).toHaveLength(0);
 }finally{yield*h.close;}expect(h.env.state.active).toBe(0);
}));
it.effect("actual query contract renders 100 safe native rows and pages without unsafe markup",()=>Effect.gen(function*(){const h=yield* harness();try{yield* h.mount;yield* h.pump;expect(h.port.state.queries[0]?.limit).toBe(100);expect(h.host.querySelectorAll(".create-participants li")).toHaveLength(100);expect(h.host.querySelector("script")).toBeNull();expect(h.host.textContent).toContain("<script>문자열</script>");button(h.host,"다음 100명").click();yield* h.pump;expect(h.port.state.queries.at(-1)?.offset).toBe(100);expect(h.host.textContent).toContain("참가자 100");button(h.host,"다음 100명").click();yield* h.pump;expect(h.host.querySelectorAll(".create-participants li")).toHaveLength(1);expect(button(h.host,"다음 100명").disabled).toBe(true);}finally{yield* h.close;}expect(h.env.state.active).toBe(0);expect(h.env.frames.size).toBe(0);}));
it.effect("every native input has a label and all action buttons avoid implicit form submission",()=>Effect.gen(function*(){const h=yield* harness();try{yield* h.mount;yield* h.pump;for(const input of h.host.querySelectorAll("input,select"))expect(h.host.querySelector('label[for="'+input.id+'"]')).not.toBeNull();for(const element of h.host.querySelectorAll("button"))expect(element.type).toBe("button");expect(h.host.querySelectorAll("[role=status]").length).toBeGreaterThan(0);}finally{yield* h.close;}}));
it.effect("same frame preserves input node focus caret and dirty raw through route remount",()=>Effect.gen(function*(){const h=yield* harness();try{yield* h.mount;yield* h.pump;const input=field(h.host,"상품명 (선택)");input.focus();input.value="편집 중";input.setSelectionRange(2,2);input.dispatchEvent(new Event("input"));yield* h.pump;expect(field(h.host,"상품명 (선택)")).toBe(input);expect(document.activeElement).toBe(input);expect(input.selectionStart).toBe(2);yield* Scope.close(h.route,Exit.void);expect(h.env.state.active).toBe(0);expect(h.workspace.read().editor?.single.name.raw).toBe("편집 중");const next=yield* Scope.fork(h.app,"sequential");yield* mountCreateProduct(h.host,h.port.commands,h.workspace,()=>{}).pipe(Scope.provide(next),Effect.provideService(DomPlatform,h.env.dom));yield* h.pump;expect(field(h.host,"상품명 (선택)").value).toBe("편집 중");}finally{yield* h.close;}expect(h.env.state.active).toBe(0);}));
it.effect("keyword Enter registers literal text without completing IME composition twice",()=>Effect.gen(function*(){const h=yield* harness();try{yield* h.mount;yield* h.pump;const input=field(h.host,"포함 단어");input.dispatchEvent(new CompositionEvent("compositionstart"));input.value="테스트";input.dispatchEvent(new Event("input"));input.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",isComposing:true,keyCode:229,cancelable:true}));yield* h.pump;expect(h.port.state.edits).toHaveLength(0);input.dispatchEvent(new CompositionEvent("compositionend"));input.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",cancelable:true}));yield* h.pump;expect(h.port.state.edits).toHaveLength(0);input.dispatchEvent(new KeyboardEvent("keydown",{key:"Escape"}));input.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",cancelable:true}));yield* h.pump;expect(h.workspace.read().editor?.filters.includeKeywords.raw).toBe("테스트");expect(h.port.state.edits).toHaveLength(1);}finally{yield* h.close;}}));
it.effect("participant detail owns exactly fifty comments and next page has one",()=>Effect.gen(function*(){const h=yield* harness();try{yield* h.mount;yield* h.pump;button(h.host,"댓글 보기").click();yield* h.pump;const dialog=h.host.querySelector("dialog");expect(dialog?.open).toBe(true);expect(h.port.state.comments).toBe(1);expect(dialog?.textContent).toContain("1–50 / 51");button(h.host,"다음 댓글").click();yield* h.pump;expect(h.port.state.comments).toBe(2);expect(dialog?.textContent).toContain("51–51 / 51");button(h.host,"닫기").click();yield* h.pump;expect(h.host.querySelector("dialog")).toBeNull();}finally{yield* h.close;}}));
it.effect("double submit admits one finalization and navigates real returned collection",()=>Effect.gen(function*(){const h=yield* harness();try{yield* h.mount;yield* h.pump;const submit=button(h.host,"추첨 생성");submit.click();submit.click();yield* h.pump;expect(h.port.state.creates).toHaveLength(1);expect(h.navigated).toEqual(["collection"]);expect(h.host.querySelector("dialog")).toBeNull();}finally{yield* h.close;}}));
for(const fault of [1,7,31,-1])it.effect("first Nth continuous listener fault "+fault+" rolls mount back",()=>Effect.gen(function*(){const h=yield* harness(draft(),fault);try{expect((yield* Effect.result(h.mount))._tag).toBe("Failure");expect(h.host.childNodes).toHaveLength(0);expect(h.env.state.active).toBe(0);expect(h.env.frames.size).toBe(0);expect(h.port.state.creates).toHaveLength(0);}finally{yield* h.close;}}));
it.effect("100 screen swaps return nodes listeners frames to baseline and preserve app editor",()=>Effect.gen(function*(){const h=yield* harness();try{for(let index=0;index<100;index++){const scope=yield* Scope.fork(h.app,"sequential");yield* mountCreateProduct(h.host,h.port.commands,h.workspace,()=>{}).pipe(Scope.provide(scope),Effect.provideService(DomPlatform,h.env.dom));yield* Scope.close(scope,Exit.void);expect(h.host.childNodes).toHaveLength(0);expect(h.env.state.active).toBe(0);expect(h.env.frames.size).toBe(0);}expect(h.workspace.read().editor?.identity.draftId).toBe("draft");expect(h.env.state.acquired).toBe(h.env.state.released);}finally{yield* h.close;} }), { timeout: 15_000 });
it.effect("initial editor readiness disables both URL and load until actual ensure succeeds",()=>Effect.gen(function*(){const port=yield* commandHarness(null);const scope=yield* Scope.make();let prizeId=0;const work:Array<Effect.Effect<void>>=[];const workspace=yield* makeCreateWorkspace(port.commands,(effect)=>work.push(effect)).pipe(Scope.provide(scope),Effect.provideService(ClientIds,clientIdsFrom(()=>"id")));const env=environment();const host=document.createElement("main");document.body.append(host);try{yield* mountCreateProduct(host,port.commands,workspace,()=>{}).pipe(Scope.provide(scope),Effect.provideService(DomPlatform,env.dom));expect(field(host,"디시인사이드 게시글 주소").disabled).toBe(true);expect(button(host,"게시글 불러오기").disabled).toBe(true);for(const effect of work.splice(0))yield* effect.pipe(Effect.forkIn(scope));for(let i=0;i<20;i++)yield* Effect.yieldNow;env.pulse();for(let i=0;i<20;i++)yield* Effect.yieldNow;expect(field(host,"디시인사이드 게시글 주소").disabled).toBe(false);expect(button(host,"게시글 불러오기").disabled).toBe(false);}finally{yield* Scope.close(scope,Exit.void);yield* port.close;host.remove();}expect(env.state.active).toBe(0);expect(env.frames.size).toBe(0);}));

it.effect("visible name fill count fill mode change and direct finalization retain submitted name",()=>Effect.gen(function*(){const h=yield* harness();try{yield* h.mount;yield* h.pump;const name=field(h.host,"상품명 (선택)");name.value="E2E 상품";name.dispatchEvent(new Event("input"));const count=field(h.host,"당첨 인원");count.value="1";count.dispatchEvent(new Event("input"));const mode=h.host.querySelector<HTMLSelectElement>('select#'+[...h.host.querySelectorAll("label")].find((label)=>label.textContent==="추첨 방식")?.htmlFor);if(mode===null)throw Error("draw mode absent");mode.value="immediate";mode.dispatchEvent(new Event("change"));yield* h.pump;expect(h.port.state.edits[0]?.prizes?.single.name).toBe("E2E 상품");button(h.host,"추첨 생성").click();yield* h.pump;expect(h.port.state.creates).toHaveLength(1);expect(h.port.state.edits.at(-1)?.prizes?.single.name).toBe("E2E 상품");}finally{yield* h.close;}}));

it.effect("duplicate participant detail requests keep one fifty-comment dialog and release latch on close",()=>Effect.gen(function*(){const h=yield* harness();try{yield* h.mount;yield* h.pump;const open=button(h.host,"댓글 보기");open.click();open.click();yield* h.pump;expect(h.host.querySelectorAll("dialog")).toHaveLength(1);expect(h.port.state.comments).toBe(1);expect(h.host.querySelector("dialog")?.textContent).toContain("1–50 / 51");button(h.host,"닫기").click();yield* h.pump;expect(h.host.querySelectorAll("dialog")).toHaveLength(0);open.click();yield* h.pump;expect(h.host.querySelectorAll("dialog")).toHaveLength(1);expect(h.port.state.comments).toBe(2);yield* Scope.close(h.route,Exit.void);expect(h.host.childNodes).toHaveLength(0);expect(h.env.state.active).toBe(0);expect(h.env.frames.size).toBe(0);}finally{yield* h.close;}}));
it.effect("participant detail mount fault releases latch and partial listeners before retry",()=>Effect.gen(function*(){const h=yield* harness();try{yield* h.mount;yield* h.pump;const baseline=h.env.state.active;h.env.failOnNext();button(h.host,"댓글 보기").click();yield* h.pump;expect(h.host.querySelectorAll("dialog")).toHaveLength(0);expect(h.env.state.active).toBe(baseline);expect(h.port.state.comments).toBe(0);button(h.host,"댓글 보기").click();yield* h.pump;expect(h.host.querySelectorAll("dialog")).toHaveLength(1);expect(h.port.state.comments).toBe(1);button(h.host,"닫기").click();yield* h.pump;expect(h.env.state.active).toBe(baseline);}finally{yield* h.close;}expect(h.env.state.active).toBe(0);expect(h.env.frames.size).toBe(0);}));
it.effect("global write gate blocks callbacks before paint preserves raw and leaves participant reads enabled",()=>Effect.gen(function*(){
 const h=yield*harness();try{yield*h.mount;yield*h.pump;const input=field(h.host,"디시인사이드 게시글 주소");input.value="https://evil.invalid/secret";input.dispatchEvent(new Event("input"));
 h.workspace.setWritesBlocked(true);button(h.host,"게시글 불러오기").dispatchEvent(new Event("click"));button(h.host,"추첨 생성").dispatchEvent(new Event("click"));input.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",cancelable:true}));yield*h.pump;
 expect(h.port.state.loads).toHaveLength(0);expect(h.port.state.creates).toHaveLength(0);expect(h.workspace.read().error).toBeNull();expect(input.disabled).toBe(false);expect(button(h.host,"게시글 불러오기").disabled).toBe(true);
 for(const fieldset of h.host.querySelectorAll("fieldset"))expect(fieldset.disabled).toBe(false);expect(field(h.host,"참가자 검색").disabled).toBe(false);
 const before=h.port.state.queries.length;button(h.host,"다음 100명").click();yield*h.pump;expect(h.port.state.queries.length).toBeGreaterThan(before);button(h.host,"댓글 보기").click();yield*h.pump;expect(h.port.state.comments).toBe(1);button(h.host,"닫기").click();yield*h.pump;
 h.workspace.setWritesBlocked(false);yield*h.pump;expect(field(h.host,"디시인사이드 게시글 주소")).toBe(input);expect(input.value).toBe("https://evil.invalid/secret");expect(input.disabled).toBe(false);
 button(h.host,"게시글 불러오기").click();yield*h.pump;expect(h.port.state.loads).toEqual(["https://evil.invalid/secret"]);
 }finally{yield*h.close;}expect(h.env.state.active).toBe(0);expect(h.env.frames.size).toBe(0);
}));
it.effect("global write gate permits cancellation of an already loading article",()=>Effect.gen(function*(){
 const h=yield*harness(draft({load:{operationId:"load",sequence:1,pages:1,comments:3,state:"loading",failureCode:null}}));try{yield*h.mount;yield*h.pump;h.workspace.setWritesBlocked(true);yield*h.pump;
 expect(button(h.host,"게시글 불러오기").disabled).toBe(true);expect(button(h.host,"수집 취소").disabled).toBe(false);button(h.host,"수집 취소").click();yield*h.pump;expect(h.port.state.cancelled).toBe(1);
 }finally{yield*h.close;}expect(h.env.state.active).toBe(0);
}));
it.effect("same session write gate preserves focused raw caret and blocks Enter without a server edit",()=>Effect.gen(function*(){const h=yield*harness();try{yield*h.mount;yield*h.pump;const name=field(h.host,"상품명 (선택)");name.focus();name.value="원문";name.setSelectionRange(1,1);name.dispatchEvent(new Event("input"));h.workspace.setWritesBlocked(true);yield*h.pump;expect(name.disabled).toBe(false);expect(document.activeElement).toBe(name);expect(name.selectionStart).toBe(1);name.value="원문 계속";name.setSelectionRange(3,3);name.dispatchEvent(new Event("input"));name.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",cancelable:true}));yield*h.pump;expect(h.port.state.edits).toHaveLength(0);expect(h.workspace.read().editor?.single.name.raw).toBe("원문 계속");h.workspace.setWritesBlocked(false);yield*h.pump;expect(document.activeElement).toBe(name);expect(name.selectionStart).toBe(3);name.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",cancelable:true}));yield*h.pump;expect(h.port.state.edits).toHaveLength(1);expect(h.port.state.edits[0]?.prizes?.single.name).toBe("원문 계속");}finally{yield*h.close;}expect(h.env.state.active).toBe(0);expect(h.env.frames.size).toBe(0);}));
it.effect("single count native increment decrement enforce one eligible and ten boundaries without rewriting invalid raw",()=>Effect.gen(function*(){const h=yield*harness(draft({participants:10,included:10}));try{yield*h.mount;yield*h.pump;const down=button(h.host,"당첨 인원 줄이기");const up=button(h.host,"당첨 인원 늘리기");expect(down.textContent).toBe("−");expect(up.textContent).toBe("+");expect(down.getAttribute("aria-label")).toBe("당첨 인원 줄이기");expect(up.getAttribute("aria-label")).toBe("당첨 인원 늘리기");expect(down.disabled).toBe(true);up.click();yield*h.pump;expect(field(h.host,"당첨 인원").value).toBe("2");down.click();yield*h.pump;expect(field(h.host,"당첨 인원").value).toBe("1");const input=field(h.host,"당첨 인원");input.value="10";input.dispatchEvent(new Event("input"));yield*h.pump;expect(up.disabled).toBe(true);down.click();yield*h.pump;expect(input.value).toBe("9");input.value="";input.dispatchEvent(new Event("input"));yield*h.pump;expect(up.disabled).toBe(true);expect(down.disabled).toBe(true);up.dispatchEvent(new Event("click"));yield*h.pump;expect(input.value).toBe("");}finally{yield*h.close;}}));
it.effect("nickname comment projection switches safely without altering query selection or keyed rows",()=>Effect.gen(function*(){const h=yield*harness();try{yield*h.mount;yield*h.pump;const row=h.host.querySelector(".create-participants li");const queries=h.port.state.queries.length;const select=h.host.querySelector<HTMLSelectElement>("#create-preview-mode")!;expect(h.host.textContent).toContain("<script>문자열</script>");select.value="nicknames";select.dispatchEvent(new Event("change"));yield*h.pump;expect(h.host.textContent).not.toContain("<script>문자열</script>");expect(h.host.querySelector(".create-participants li")).toBe(row);expect(h.port.state.queries.length).toBe(queries);expect(h.port.state.edits).toHaveLength(0);select.value="comments";select.dispatchEvent(new Event("change"));yield*h.pump;expect(h.host.textContent).toContain("<script>문자열</script>");expect(h.host.querySelector("script")).toBeNull();}finally{yield*h.close;}}));
it.effect("author unavailable and accepted absolute cutoff are shown with group and match counts",()=>Effect.gen(function*(){const initial=draft({authorIdentifiable:false,filters:{...draft().filters,timeCut:"2026-10-06T03:31:00Z"}});const h=yield*harness(initial);try{yield*h.mount;yield*h.pump;expect(field(h.host,"글쓴이 제외").disabled).toBe(true);expect(h.host.textContent).toContain("작성자를 식별할 수 없어 작성자 제외가 적용되지 않습니다.");expect(h.host.textContent).toContain("확정 시간컷:");expect(h.host.textContent).toContain("12:30까지 (한국 시간)");expect(h.host.textContent).toContain("그룹 전체 201명 · 검색 결과 201명");expect(h.workspace.read().draft?.filters.timeCut).toBe("2026-10-06T03:31:00Z");}finally{yield*h.close;}}));
it.effect("draft comment preview renders three literal bodies without full comment query or rewriting keyed row",()=>Effect.gen(function*(){const h=yield*harness();try{const original=h.port.commands.queryParticipants;Object.assign(h.port.commands,{queryParticipants:(request:Parameters<typeof original>[0])=>original(request).pipe(Effect.map(reply=>({...reply,data:{...reply.data,rows:reply.data.rows.map(row=>({...row,previews:["<script>first</script>","second","third"]}))}})))});yield*h.mount;yield*h.pump;expect(h.host.textContent).toContain("<script>first</script> · second · third");expect(h.host.querySelector("script")).toBeNull();expect(h.port.state.comments).toBe(0);const row=h.host.querySelector(".create-participants li");const select=h.host.querySelector<HTMLSelectElement>("#create-preview-mode")!;select.value="nicknames";select.dispatchEvent(new Event("change"));yield*h.pump;expect(h.host.textContent).not.toContain("second · third");expect(h.host.querySelector(".create-participants li")).toBe(row);}finally{yield*h.close;}expect(h.env.state.active).toBe(0);expect(h.env.frames.size).toBe(0);}));
it.effect("optimistic prize row stays disabled through delayed structural commit and resync without enable flash",()=>Effect.gen(function*(){const initial=draft({participants:10,included:10,prizes:{...draft().prizes,mode:"multiple"}});const h=yield*harness(initial);const entered=yield*Deferred.make<void>();const release=yield*Deferred.make<void>();const original=h.port.commands.commitThrough;let commits=0;Object.assign(h.port.commands,{commitThrough:(receipt:Parameters<typeof original>[0])=>++commits===1?Deferred.succeed(entered,undefined).pipe(Effect.andThen(Deferred.await(release)),Effect.andThen(original(receipt))):original(receipt)});try{yield*h.mount;yield*h.pump;button(h.host,"상품 추가").click();yield*h.pump;yield*Deferred.await(entered);expect([...h.host.querySelectorAll("button")].filter(button=>button.textContent==="상품 삭제")).toHaveLength(2);expect(button(h.host,"상품 추가").disabled).toBe(true);const modeLabel=[...h.host.querySelectorAll("label")].find(label=>label.textContent==="상품 구성")!;expect(h.host.querySelector<HTMLSelectElement>("#"+modeLabel.htmlFor)!.disabled).toBe(true);h.workspace.setWritesBlocked(true);yield*h.pump;h.workspace.setWritesBlocked(false);yield*h.pump;expect(button(h.host,"상품 추가").disabled).toBe(true);yield*Deferred.succeed(release,undefined);yield*h.pump;expect(button(h.host,"상품 추가").disabled).toBe(false);button(h.host,"상품 추가").click();yield*h.pump;expect([...h.host.querySelectorAll("button")].filter(button=>button.textContent==="상품 삭제")).toHaveLength(3);expect(h.port.state.edits).toHaveLength(2);}finally{yield*h.close;}expect(h.env.state.active).toBe(0);expect(h.env.frames.size).toBe(0);}));
it.effect("ten prize text inputs followed by author change retain filter intent through older prize confirmation",()=>Effect.gen(function*(){
 const prizes=Array.from({length:10},(_,index)=>({id:"many-"+index,name:"",count:1}));const h=yield*harness(draft({participants:10,included:10,prizes:{...draft().prizes,mode:"multiple",multiple:prizes}}));const entered=yield*Deferred.make<void>();const release=yield*Deferred.make<void>();const original=h.port.commands.commitThrough;let first=true;
 Object.assign(h.port.commands,{commitThrough:(receipt:Parameters<typeof original>[0])=>{if(!first)return original(receipt);first=false;return Deferred.succeed(entered,undefined).pipe(Effect.andThen(Deferred.await(release)),Effect.andThen(original(receipt)));}});
 try{yield*h.mount;yield*h.pump;const names=[...h.host.querySelectorAll<HTMLInputElement>('fieldset input[maxlength="20"]')].slice(1);expect(names).toHaveLength(10);for(const[index,input]of names.entries()){input.focus();input.value="상품 "+index;input.dispatchEvent(new Event("input"));}
 names[9]!.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",cancelable:true}));yield*h.pump;yield*Deferred.await(entered);const author=field(h.host,"글쓴이 제외");author.checked=false;author.dispatchEvent(new Event("change"));yield*h.pump;expect(h.workspace.read().editor?.filters.excludeAuthor.raw).toBe(false);expect(h.workspace.read().editor?.filters.excludeAuthor.dirty).toBe(true);
 yield*Deferred.succeed(release,undefined);yield*h.pump;expect(h.port.state.edits.map(intent=>intent.kind)).toEqual(["SetPrizes","UpdateFilters"]);expect(h.port.state.edits[1]?.filters?.excludeAuthor).toBe(false);expect(h.workspace.read().draft?.filters.excludeAuthor).toBe(false);expect(author.checked).toBe(false);expect(h.workspace.read().editor?.filters.excludeAuthor.dirty).toBe(false);expect(h.workspace.read().draft?.prizes.multiple.map(prize=>prize.name)).toEqual(prizes.map((_,index)=>"상품 "+index));
 }finally{yield*h.close;}expect(h.env.state.active).toBe(0);expect(h.env.frames.size).toBe(0);
}));

for(const mode of ["immediate","reservation"] as const)it.effect("create button directly finalizes "+mode+" without a credential dialog",()=>Effect.gen(function*(){
 const initial=draft({prizes:{...draft().prizes,drawMode:mode}});const h=yield*harness(initial);try{
  yield*h.mount;yield*h.pump;expect(h.host.querySelector('input[type=password]')).toBeNull();
  const create=button(h.host,"추첨 생성");create.click();create.click();yield*h.pump;
  expect(h.port.state.creates).toEqual([{afterSequence:0,mode}]);expect(h.navigated).toEqual(["collection"]);expect(h.host.querySelector("dialog")).toBeNull();
 }finally{yield*h.close;}expect(h.env.state.active).toBe(0);expect(h.env.frames.size).toBe(0);
}));
it.effect("unknown direct finalization retains its lock and does not navigate or admit a second command",()=>Effect.gen(function*(){
 const h=yield*harness();try{h.port.state.unknown=true;yield*h.mount;yield*h.pump;const create=button(h.host,"추첨 생성");create.click();yield*h.pump;
  expect(h.workspace.read().editor?.lock?.kind).toBe("finalization");expect(h.navigated).toEqual([]);expect(create.disabled).toBe(true);create.click();yield*h.pump;expect(h.port.state.creates).toHaveLength(1);expect(h.host.querySelector("dialog")).toBeNull();
 }finally{yield*h.close;}expect(h.env.state.active).toBe(0);expect(h.env.frames.size).toBe(0);
}));
it.effect("initial create layout keeps optional filters closed and pairs participants with final settings",()=>Effect.gen(function*(){
 const h=yield* harness();
 try{
  yield* h.mount;yield* h.pump;
  const filters=h.host.querySelector<HTMLDetailsElement>("details[data-filter-accordion]")!;
  expect(filters.open).toBe(false);expect(filters.firstElementChild?.tagName).toBe("SUMMARY");
  expect(filters.querySelector("summary")?.textContent).toContain("자동 분류 필터");
  expect(filters.querySelector("summary")?.getAttribute("role")).toBeNull();
  expect(filters.querySelector("fieldset legend")?.textContent).toBe("자동 분류 필터");
  expect(field(h.host,"디시인사이드 게시글 주소").closest(".create-article-toolbar")).not.toBeNull();
  expect(button(h.host,"게시글 초기화").closest(".create-article-toolbar")).not.toBeNull();
  const workspace=h.host.querySelector(".create-workspace")!;
  expect(workspace.children[0]?.classList.contains("create-selection")).toBe(true);
  expect(workspace.children[1]?.classList.contains("create-prizes")).toBe(true);
  expect(button(h.host,"추첨 생성").closest(".create-prizes")).toBe(workspace.children[1]);expect(button(h.host,"추첨 생성").closest(".create-footer")?.nextElementSibling?.textContent).toContain("상품은 최대 10개");
  expect(h.port.state.edits).toHaveLength(0);expect(h.port.state.creates).toHaveLength(0);
 }finally{yield* h.close;}
 expect(h.env.state.active).toBe(0);expect(h.env.frames.size).toBe(0);
}));
it.effect("native filter folding retains raw caret IDs and keyed rows without mutation or remount",()=>Effect.gen(function*(){
 const h=yield* harness();
 try{
  yield* h.mount;yield* h.pump;
  const filters=h.host.querySelector<HTMLDetailsElement>("details[data-filter-accordion]")!;
  const summary=filters.querySelector("summary")!;
  summary.click();expect(filters.open).toBe(true);
  const input=field(h.host,"포함 단어");const id=input.id;const row=h.host.querySelector(".create-participants li");
  input.value="아직 입력한 단어";input.dispatchEvent(new Event("input"));input.setSelectionRange(2,5);yield* h.pump;
  const before=h.workspace.read();const queries=h.port.state.queries.length;
  summary.click();expect(filters.open).toBe(false);yield* h.pump;
  summary.click();expect(filters.open).toBe(true);yield* h.pump;
  expect(field(h.host,"포함 단어")).toBe(input);expect(input.id).toBe(id);
  expect(input.value).toBe("아직 입력한 단어");expect([input.selectionStart,input.selectionEnd]).toEqual([2,5]);
  expect(h.workspace.read().editor).toBe(before.editor);expect(h.workspace.read().keywordRaw).toEqual(before.keywordRaw);
  expect(h.host.querySelector(".create-participants li")).toBe(row);
  expect(h.port.state.queries).toHaveLength(queries);expect(h.port.state.edits).toHaveLength(0);
  yield* Scope.close(h.route,Exit.void);expect(h.host.children).toHaveLength(0);
  input.dispatchEvent(new Event("input"));summary.click();yield* h.pump;expect(h.port.state.edits).toHaveLength(0);
 }finally{yield* h.close;}
 expect(h.env.state.active).toBe(0);expect(h.env.frames.size).toBe(0);
}));
